// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_producer_p_p_producer_write_port: vest_1prod_1cons::ArrayOfByte,
  pub api_sched_state: hamr::SchedState,
  pub api_sched_schedule: hamr::Schedule
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_producer_p_p_producer_write_port(container.api_producer_p_p_producer_write_port);
  put_sched_state(container.api_sched_state);
  put_sched_schedule(container.api_sched_schedule);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  producer_p_p_producer_write_port: vest_1prod_1cons::ArrayOfByte,
  sched_state: hamr::SchedState,
  sched_schedule: hamr::Schedule)
{
  put_producer_p_p_producer_write_port(producer_p_p_producer_write_port);
  put_sched_state(sched_state);
  put_sched_schedule(sched_schedule);
}

/// setter for IN DataPort
pub fn put_producer_p_p_producer_write_port(value: vest_1prod_1cons::ArrayOfByte)
{
  *extern_api::IN_producer_p_p_producer_write_port.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_sched_state(value: hamr::SchedState)
{
  *extern_api::IN_sched_state.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_sched_schedule(value: hamr::Schedule)
{
  *extern_api::IN_sched_schedule.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}
