#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool myStructArray_is_empty(void);
bool get_myStructArray_poll(sb_event_counter_t *numDropped, Gumbo_Structs_Arrays_MyStructArray_i *data);
bool get_myStructArray(Gumbo_Structs_Arrays_MyStructArray_i *data);
bool MyArrayStruct_is_empty(void);
bool get_MyArrayStruct_poll(sb_event_counter_t *numDropped, Gumbo_Structs_Arrays_MyArrayStruct *data);
bool get_MyArrayStruct(Gumbo_Structs_Arrays_MyArrayStruct *data);
bool MyArrayInt32_is_empty(void);
bool get_MyArrayInt32_poll(sb_event_counter_t *numDropped, Gumbo_Structs_Arrays_MyArrayInt32 *data);
bool get_MyArrayInt32(Gumbo_Structs_Arrays_MyArrayInt32 *data);
