// #Sireum

package sysml

import org.sireum._
import art._
import art.PortMode._
import art.DispatchPropertyProtocol._
import art.Art.BridgeId._
import art.Art.PortId._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Arch {
  val Sys_i_Instance_producer_producer : sysml.Gubmo_Structs_Arrays.ProducerThr_i_producer_producer_Bridge = {
    val p_myArrayInt32_DataPort = Port[Gubmo_Structs_Arrays.MyArrayInt32] (id = portId"0", name = "Sys_i_Instance_producer_producer_p_myArrayInt32_DataPort", mode = DataOut)
    val p_myArrayStruct_DataPort = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"1", name = "Sys_i_Instance_producer_producer_p_myArrayStruct_DataPort", mode = DataOut)
    val p_myStructArray_DataPort = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"2", name = "Sys_i_Instance_producer_producer_p_myStructArray_DataPort", mode = DataOut)
    val p_myArrayInt32_EventDataPort = Port[Gubmo_Structs_Arrays.MyArrayInt32] (id = portId"3", name = "Sys_i_Instance_producer_producer_p_myArrayInt32_EventDataPort", mode = EventOut)
    val p_myArrayStruct_EventDataPort = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"4", name = "Sys_i_Instance_producer_producer_p_myArrayStruct_EventDataPort", mode = EventOut)
    val p_myStructArray_EventDataPort = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"5", name = "Sys_i_Instance_producer_producer_p_myStructArray_EventDataPort", mode = EventOut)

    sysml.Gubmo_Structs_Arrays.ProducerThr_i_producer_producer_Bridge(
      id = bridgeId"0",
      name = "Sys_i_Instance_producer_producer",
      dispatchProtocol = Periodic(period = 1000),
      dispatchTriggers = None(),

      p_myArrayInt32_DataPort = p_myArrayInt32_DataPort,
      p_myArrayStruct_DataPort = p_myArrayStruct_DataPort,
      p_myStructArray_DataPort = p_myStructArray_DataPort,
      p_myArrayInt32_EventDataPort = p_myArrayInt32_EventDataPort,
      p_myArrayStruct_EventDataPort = p_myArrayStruct_EventDataPort,
      p_myStructArray_EventDataPort = p_myStructArray_EventDataPort
    )
  }
  val Sys_i_Instance_consumer_consumer : sysml.Gubmo_Structs_Arrays.ConsumerThr_i_consumer_consumer_Bridge = {
    val c_myArrayInt32_DataPort = Port[Gubmo_Structs_Arrays.MyArrayInt32] (id = portId"6", name = "Sys_i_Instance_consumer_consumer_c_myArrayInt32_DataPort", mode = DataIn)
    val c_myArrayStruct_DataPort = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"7", name = "Sys_i_Instance_consumer_consumer_c_myArrayStruct_DataPort", mode = DataIn)
    val c_myStructArray_DataPort = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"8", name = "Sys_i_Instance_consumer_consumer_c_myStructArray_DataPort", mode = DataIn)
    val c_myArrayInt32_EventDataPort = Port[Gubmo_Structs_Arrays.MyArrayInt32] (id = portId"9", name = "Sys_i_Instance_consumer_consumer_c_myArrayInt32_EventDataPort", mode = EventIn)
    val c_myArrayStruct_EventDataPort = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"10", name = "Sys_i_Instance_consumer_consumer_c_myArrayStruct_EventDataPort", mode = EventIn)
    val c_myStructArray_EventDataPort = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"11", name = "Sys_i_Instance_consumer_consumer_c_myStructArray_EventDataPort", mode = EventIn)

    sysml.Gubmo_Structs_Arrays.ConsumerThr_i_consumer_consumer_Bridge(
      id = bridgeId"1",
      name = "Sys_i_Instance_consumer_consumer",
      dispatchProtocol = Periodic(period = 1000),
      dispatchTriggers = None(),

      c_myArrayInt32_DataPort = c_myArrayInt32_DataPort,
      c_myArrayStruct_DataPort = c_myArrayStruct_DataPort,
      c_myStructArray_DataPort = c_myStructArray_DataPort,
      c_myArrayInt32_EventDataPort = c_myArrayInt32_EventDataPort,
      c_myArrayStruct_EventDataPort = c_myArrayStruct_EventDataPort,
      c_myStructArray_EventDataPort = c_myStructArray_EventDataPort
    )
  }

  val ad : ArchitectureDescription = {

    ArchitectureDescription(
      components = IS[Art.BridgeId, Bridge] (Sys_i_Instance_producer_producer, Sys_i_Instance_consumer_consumer),

      connections = IS[Art.ConnectionId, UConnection] (Connection(from = Sys_i_Instance_producer_producer.p_myArrayInt32_DataPort, to = Sys_i_Instance_consumer_consumer.c_myArrayInt32_DataPort),
                                                       Connection(from = Sys_i_Instance_producer_producer.p_myArrayStruct_DataPort, to = Sys_i_Instance_consumer_consumer.c_myArrayStruct_DataPort),
                                                       Connection(from = Sys_i_Instance_producer_producer.p_myStructArray_DataPort, to = Sys_i_Instance_consumer_consumer.c_myStructArray_DataPort),
                                                       Connection(from = Sys_i_Instance_producer_producer.p_myArrayInt32_EventDataPort, to = Sys_i_Instance_consumer_consumer.c_myArrayInt32_EventDataPort),
                                                       Connection(from = Sys_i_Instance_producer_producer.p_myArrayStruct_EventDataPort, to = Sys_i_Instance_consumer_consumer.c_myArrayStruct_EventDataPort),
                                                       Connection(from = Sys_i_Instance_producer_producer.p_myStructArray_EventDataPort, to = Sys_i_Instance_consumer_consumer.c_myStructArray_EventDataPort))
    )
  }
}
