// #Sireum

package sysml

import org.sireum._
import art._
import art.PortMode._
import art.DispatchPropertyProtocol._
import art.Art.BridgeId._
import art.Art.PortId._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Arch {
  val Sys_i_Instance_producer_producer : sysml.Gubmo_Structs_Arrays.ProducerThr_i_producer_producer_Bridge = {
    val myStructArray = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"0", name = "Sys_i_Instance_producer_producer_myStructArray", mode = EventOut)
    val MyArrayStruct = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"1", name = "Sys_i_Instance_producer_producer_MyArrayStruct", mode = EventOut)

    sysml.Gubmo_Structs_Arrays.ProducerThr_i_producer_producer_Bridge(
      id = bridgeId"0",
      name = "Sys_i_Instance_producer_producer",
      dispatchProtocol = Periodic(period = 1000),
      dispatchTriggers = None(),

      myStructArray = myStructArray,
      MyArrayStruct = MyArrayStruct
    )
  }
  val Sys_i_Instance_consumer_consumer : sysml.Gubmo_Structs_Arrays.ConsumerThr_i_consumer_consumer_Bridge = {
    val myArrayInt32_DataPort = Port[Gubmo_Structs_Arrays.MyArrayInt32] (id = portId"2", name = "Sys_i_Instance_consumer_consumer_myArrayInt32_DataPort", mode = DataIn)
    val myArrayStruct_DataPort = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"3", name = "Sys_i_Instance_consumer_consumer_myArrayStruct_DataPort", mode = DataIn)
    val myStructArray_DataPort = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"4", name = "Sys_i_Instance_consumer_consumer_myStructArray_DataPort", mode = DataIn)
    val myArrayInt32_EventDataPort = Port[Gubmo_Structs_Arrays.MyArrayInt32] (id = portId"5", name = "Sys_i_Instance_consumer_consumer_myArrayInt32_EventDataPort", mode = EventIn)
    val myArrayStruct_EventDataPort = Port[Gubmo_Structs_Arrays.MyArrayStruct] (id = portId"6", name = "Sys_i_Instance_consumer_consumer_myArrayStruct_EventDataPort", mode = EventIn)
    val myStructArray_EventDataPort = Port[Gubmo_Structs_Arrays.MyStructArray_i] (id = portId"7", name = "Sys_i_Instance_consumer_consumer_myStructArray_EventDataPort", mode = EventIn)

    sysml.Gubmo_Structs_Arrays.ConsumerThr_i_consumer_consumer_Bridge(
      id = bridgeId"1",
      name = "Sys_i_Instance_consumer_consumer",
      dispatchProtocol = Periodic(period = 1000),
      dispatchTriggers = None(),

      myArrayInt32_DataPort = myArrayInt32_DataPort,
      myArrayStruct_DataPort = myArrayStruct_DataPort,
      myStructArray_DataPort = myStructArray_DataPort,
      myArrayInt32_EventDataPort = myArrayInt32_EventDataPort,
      myArrayStruct_EventDataPort = myArrayStruct_EventDataPort,
      myStructArray_EventDataPort = myStructArray_EventDataPort
    )
  }

  val ad : ArchitectureDescription = {

    ArchitectureDescription(
      components = IS[Art.BridgeId, Bridge] (Sys_i_Instance_producer_producer, Sys_i_Instance_consumer_consumer),

      connections = IS[Art.ConnectionId, UConnection] (Connection(from = Sys_i_Instance_producer_producer.myStructArray, to = Sys_i_Instance_consumer_consumer.myStructArray_EventDataPort),
                                                       Connection(from = Sys_i_Instance_producer_producer.MyArrayStruct, to = Sys_i_Instance_consumer_consumer.myArrayStruct_EventDataPort))
    )
  }
}
