// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct MyStruct2_i {
    pub fieldSChar: u8
  }

  impl Default for MyStruct2_i {
    fn default() -> Self
    {
      Self { fieldSChar: 0 }
    }
  }
}