// #Sireum

package firewall.SW

import org.sireum._
import firewall.util.Profile
import firewall.util.EmptyContainer
import firewall.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@msig trait Firewall_Impl_Firewall_Firewall_Profile_Trait extends Profile

@record class Firewall_Impl_Firewall_Firewall_Profile (
  val name: String,
) extends Firewall_Impl_Firewall_Firewall_Profile_Trait {

  override def next: EmptyContainer = {
    return EmptyContainer()
  }
}

// Profile with generators for incoming ports
@msig trait Firewall_Impl_Firewall_Firewall_Profile_P_Trait extends Profile {
  def api_EthernetFramesRxIn: RandomLib // random lib for generating SW.RawEthernetMessage
  def api_EthernetFramesTxIn: RandomLib // random lib for generating SW.RawEthernetMessage
}

@record class Firewall_Impl_Firewall_Firewall_Profile_P(
  val name: String,
  var api_EthernetFramesRxIn: RandomLib, // random lib for generating SW.RawEthernetMessage
  var api_EthernetFramesTxIn: RandomLib // random lib for generating SW.RawEthernetMessage
  ) extends Firewall_Impl_Firewall_Firewall_Profile_P_Trait {

  override def next: Firewall_Impl_Firewall_Firewall_PreState_Container_P = {
    return (Firewall_Impl_Firewall_Firewall_PreState_Container_P (
      api_EthernetFramesRxIn = api_EthernetFramesRxIn.nextOptionSWRawEthernetMessage(),
      api_EthernetFramesTxIn = api_EthernetFramesTxIn.nextOptionSWRawEthernetMessage()))
  }
}

// Profile with generators for state variables and incoming ports
@msig trait Firewall_Impl_Firewall_Firewall_Profile_PS_Trait extends Firewall_Impl_Firewall_Firewall_Profile_P_Trait {
  def api_EthernetFramesRxIn: RandomLib // random lib for generating SW.RawEthernetMessage
  def api_EthernetFramesTxIn: RandomLib // random lib for generating SW.RawEthernetMessage
}

@record class Firewall_Impl_Firewall_Firewall_Profile_PS(
  val name: String,
  var api_EthernetFramesRxIn: RandomLib, // random lib for generating SW.RawEthernetMessage
  var api_EthernetFramesTxIn: RandomLib // random lib for generating SW.RawEthernetMessage
  ) extends Firewall_Impl_Firewall_Firewall_Profile_PS_Trait {

  override def next: Firewall_Impl_Firewall_Firewall_PreState_Container_PS = {
    return (Firewall_Impl_Firewall_Firewall_PreState_Container_PS (
      api_EthernetFramesRxIn = api_EthernetFramesRxIn.nextOptionSWRawEthernetMessage(),
      api_EthernetFramesTxIn = api_EthernetFramesTxIn.nextOptionSWRawEthernetMessage()))
  }
}
