# This file will not be overwritten if codegen is rerun

[toolchain]
channel = "1.85.1-x86_64-unknown-linux-gnu"
components = [ "rustfmt", "rust-src", "rustc-dev", "llvm-tools-preview", "rust-analyzer" ]
