#include <microkit.h>
#include <sddf/util/printf.h>
#define printf sddf_dprintf

// Do not edit this file as it will be overwritten if codegen is rerun

#define SCHEDULER_CH 0

#define USER_PD 1

void partition_init();
void partition_startup();

void init(void) {
  printf("%s | INIT!\n", microkit_name);
  partition_init();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case SCHEDULER_CH:
      partition_startup();
      microkit_notify(USER_PD);
      break;
    case USER_PD:
      // THIS SHOULD ONLY BE FOR THE USER PD TO SIGNAL ITS FINISHED INIT
      microkit_notify(SCHEDULER_CH);
  }
}
