#pragma once

// Do not edit this file as it will be overwritten if codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_event_data_2_prod_2_cons_ArrayOfStruct_1.h>
#include <sb_queue_event_data_2_prod_2_cons_ArrayOfStruct_1.h>
