// #Sireum

package firewall.SW

import org.sireum._
import firewall._
import firewall.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait ArduPilot_Impl_ArduPilot_ArduPilot_GumboX_TestHarness extends ArduPilot_Impl_ArduPilot_ArduPilot_TestApi {
  def verbose: B

  /** Contract-based test harness for the initialise entry point
    */
  def testInitialiseCB(
      ): GumboXResult.Type = {

    if (verbose) {
      println(st"""Pre State Values:
                  """.render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testInitialise()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_EthernetFramesTx: Option[SW.RawEthernetMessage] = get_EthernetFramesTx()

    if (verbose) {
      println(st"""Post State Values:
                  |  api_EthernetFramesTx = ${api_EthernetFramesTx.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = firewall.SW.ArduPilot_Impl_ArduPilot_ArduPilot_GumboX.inititialize_IEP_Post(api_EthernetFramesTx)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }

  def testComputeCBJ(json: String): GumboXResult.Type = {
    firewall.JSON.toSWArduPilot_Impl_ArduPilot_ArduPilot_PreState_Container(json) match {
      case Either.Left(o) => return testComputeCBV(o)
      case Either.Right(msg) => halt(msg.string)
    }
  }

  def testComputeCBV(o: ArduPilot_Impl_ArduPilot_ArduPilot_PreState_Container): GumboXResult.Type = {
    return testComputeCB(o.api_EthernetFramesRx)
  }

  /** Contract-based test harness for the compute entry point
    * @param api_EthernetFramesRx incoming event data port
    */
  def testComputeCB(
      api_EthernetFramesRx: Option[SW.RawEthernetMessage]): GumboXResult.Type = {

    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    //   ArduPilot does not have incoming ports or state variables

    // [CheckPre]: check/filter based on pre-condition.
    val CEP_Pre_Result: B = firewall.SW.ArduPilot_Impl_ArduPilot_ArduPilot_GumboX.compute_CEP_Pre (api_EthernetFramesRx)
    if (!CEP_Pre_Result) {
      return GumboXResult.Pre_Condition_Unsat
    }

    // [PutInPorts]: put values on the input ports
    if (api_EthernetFramesRx.nonEmpty) {
      put_EthernetFramesRx(api_EthernetFramesRx.get)
    }

    if (verbose) {
      println(st"""Pre State Values:
                  |  api_EthernetFramesRx = ${api_EthernetFramesRx.string}""".render)
    }

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_EthernetFramesTx: Option[SW.RawEthernetMessage] = get_EthernetFramesTx()

    if (verbose) {
      println(st"""Post State Values:
                  |  api_EthernetFramesTx = ${api_EthernetFramesTx.string}""".render)
    }

    // [CheckPost]: invoke the oracle function
    val postResult = firewall.SW.ArduPilot_Impl_ArduPilot_ArduPilot_GumboX.compute_CEP_Post(api_EthernetFramesRx, api_EthernetFramesTx)
    val result: GumboXResult.Type =
      if (!postResult) GumboXResult.Post_Condition_Fail
      else GumboXResult.Post_Condition_Pass

    return result
  }
}
