// #Sireum

package firewall.SW

import org.sireum._
import firewall.util.Profile
import firewall.util.EmptyContainer
import firewall.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@msig trait ArduPilot_Impl_ArduPilot_ArduPilot_Profile_Trait extends Profile

@record class ArduPilot_Impl_ArduPilot_ArduPilot_Profile (
  val name: String,
) extends ArduPilot_Impl_ArduPilot_ArduPilot_Profile_Trait {

  override def next: EmptyContainer = {
    return EmptyContainer()
  }
}

// Profile with generators for incoming ports
@msig trait ArduPilot_Impl_ArduPilot_ArduPilot_Profile_P_Trait extends Profile {
  def api_EthernetFramesRx: RandomLib // random lib for generating SW.RawEthernetMessage
}

@record class ArduPilot_Impl_ArduPilot_ArduPilot_Profile_P(
  val name: String,
  var api_EthernetFramesRx: RandomLib // random lib for generating SW.RawEthernetMessage
  ) extends ArduPilot_Impl_ArduPilot_ArduPilot_Profile_P_Trait {

  override def next: ArduPilot_Impl_ArduPilot_ArduPilot_PreState_Container_P = {
    return (ArduPilot_Impl_ArduPilot_ArduPilot_PreState_Container_P (
      api_EthernetFramesRx = api_EthernetFramesRx.nextOptionSWRawEthernetMessage()))
  }
}

// Profile with generators for state variables and incoming ports
@msig trait ArduPilot_Impl_ArduPilot_ArduPilot_Profile_PS_Trait extends ArduPilot_Impl_ArduPilot_ArduPilot_Profile_P_Trait {
  def api_EthernetFramesRx: RandomLib // random lib for generating SW.RawEthernetMessage
}

@record class ArduPilot_Impl_ArduPilot_ArduPilot_Profile_PS(
  val name: String,
  var api_EthernetFramesRx: RandomLib // random lib for generating SW.RawEthernetMessage
  ) extends ArduPilot_Impl_ArduPilot_ArduPilot_Profile_PS_Trait {

  override def next: ArduPilot_Impl_ArduPilot_ArduPilot_PreState_Container_PS = {
    return (ArduPilot_Impl_ArduPilot_ArduPilot_PreState_Container_PS (
      api_EthernetFramesRx = api_EthernetFramesRx.nextOptionSWRawEthernetMessage()))
  }
}
