// #Sireum

package firewall.SW

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import firewall.GumboXUtil.GumboXResult
import firewall.util.{Container, Profile, UnitTestConfigurationBatch}
import firewall.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object Firewall_Impl_Firewall_Firewall_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultInitializeProfile = Firewall_Impl_Firewall_Firewall_Profile

  def defaultInitializeConfig: Firewall_Impl_Firewall_Firewall_Initialize_UnitTestConfiguration = {
    return (Firewall_Impl_Firewall_Firewall_Initialize_UnitTestConfiguration (
      verbose = F,
      name = "Default_Initialize_Config",
      description = "Default Initialize Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Firewall_Impl_Firewall_Firewall_Profile (
        name = "Initialize_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => None())
    )
  }

  type DefaultComputeProfile = Firewall_Impl_Firewall_Firewall_Profile_P

  def defaultComputeConfig: Firewall_Impl_Firewall_Firewall_Compute_UnitTestConfiguration = {
    return (Firewall_Impl_Firewall_Firewall_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Firewall_Impl_Firewall_Firewall_Profile_P (
        name = "Compute_Default_Profile",
        api_EthernetFramesRxIn = freshRandomLib,
        api_EthernetFramesTxIn = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = firewall.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${firewall.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = firewall.JSON.toSWFirewall_Impl_Firewall_Firewall_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class Firewall_Impl_Firewall_Firewall_Initialize_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Firewall_Impl_Firewall_Firewall_Profile_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Firewall_Impl_Firewall_Firewall_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testInitialiseCB()
  }
}

@record class Firewall_Impl_Firewall_Firewall_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Firewall_Impl_Firewall_Firewall_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Firewall_Impl_Firewall_Firewall_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[Firewall_Impl_Firewall_Firewall_PreState_Container])
  }
}
