#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool put_upper_alarm_temp(const base_Isolette_Data_Model_Temp_i *data);
bool put_lower_alarm_temp(const base_Isolette_Data_Model_Temp_i *data);
bool put_monitor_status(const base_Isolette_Data_Model_Status_Type *data);
bool put_interface_failure(const base_Isolette_Data_Model_Failure_Flag_i *data);
bool get_monitor_mode(base_Isolette_Data_Model_Monitor_Mode_Type *data);
bool get_lower_alarm_tempWstatus(base_Isolette_Data_Model_TempWstatus_i *data);
bool get_upper_alarm_tempWstatus(base_Isolette_Data_Model_TempWstatus_i *data);
bool get_current_tempWstatus(base_Isolette_Data_Model_TempWstatus_i *data);
