// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum FanCmd {
    pub On = 0,
    pub Off = 1,
  }

  impl Default for FanCmd {
    fn default() -> Self
    {
      FanCmd::On
    }
  }

}

// Memory layout as HAMR computes it
const _: () = assert!(core::mem::size_of::<FanCmd>() == 4);
const _: () = assert!(core::mem::align_of::<FanCmd>() == 4);
