// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_ArduPilot_ArduPilot_EthernetFramesTx: Option<SW::StructuredEthernetMessage_i>,
  pub api_Firewall_Firewall_EthernetFramesRxOut: Option<SW::StructuredEthernetMessage_i>,
  pub api_Firewall_Firewall_EthernetFramesTxOut: Option<SW::StructuredEthernetMessage_i>,
  pub api_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx: Option<SW::StructuredEthernetMessage_i>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_ArduPilot_ArduPilot_EthernetFramesTx(container.api_ArduPilot_ArduPilot_EthernetFramesTx);
  put_Firewall_Firewall_EthernetFramesRxOut(container.api_Firewall_Firewall_EthernetFramesRxOut);
  put_Firewall_Firewall_EthernetFramesTxOut(container.api_Firewall_Firewall_EthernetFramesTxOut);
  put_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(container.api_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  ArduPilot_ArduPilot_EthernetFramesTx: Option<SW::StructuredEthernetMessage_i>,
  Firewall_Firewall_EthernetFramesRxOut: Option<SW::StructuredEthernetMessage_i>,
  Firewall_Firewall_EthernetFramesTxOut: Option<SW::StructuredEthernetMessage_i>,
  LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx: Option<SW::StructuredEthernetMessage_i>)
{
  put_ArduPilot_ArduPilot_EthernetFramesTx(ArduPilot_ArduPilot_EthernetFramesTx);
  put_Firewall_Firewall_EthernetFramesRxOut(Firewall_Firewall_EthernetFramesRxOut);
  put_Firewall_Firewall_EthernetFramesTxOut(Firewall_Firewall_EthernetFramesTxOut);
  put_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx);
}

/// setter for IN EventDataPort
pub fn put_ArduPilot_ArduPilot_EthernetFramesTx(value: Option<SW::StructuredEthernetMessage_i>)
{
  *extern_api::IN_ArduPilot_ArduPilot_EthernetFramesTx.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_Firewall_Firewall_EthernetFramesRxOut(value: Option<SW::StructuredEthernetMessage_i>)
{
  *extern_api::IN_Firewall_Firewall_EthernetFramesRxOut.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_Firewall_Firewall_EthernetFramesTxOut(value: Option<SW::StructuredEthernetMessage_i>)
{
  *extern_api::IN_Firewall_Firewall_EthernetFramesTxOut.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(value: Option<SW::StructuredEthernetMessage_i>)
{
  *extern_api::IN_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx.lock().unwrap_or_else(|e| e.into_inner()) = value
}
