// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_sample(value: *mut i32) -> bool;
  fn put_observed_sample(value: *mut i32) -> bool;
}

pub fn unsafe_get_sample() -> Option<i32>
{
  unsafe {
    let value: *mut i32 = &mut 0;
    if (get_sample(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

pub fn unsafe_put_observed_sample(value: &i32) -> bool
{
  unsafe {
    return put_observed_sample(value as *const i32 as *mut i32);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_sample: Mutex<Option<i32>> = Mutex::new(None);
  pub static ref OUT_observed_sample: Mutex<Option<i32>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_sample.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_observed_sample.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_sample(value: *mut i32) -> bool
{
  unsafe {
    match *IN_sample.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}

#[cfg(test)]
pub fn put_observed_sample(value: *mut i32) -> bool
{
  unsafe {
    *OUT_observed_sample.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
