// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

#[verus_verify]
#[repr(C)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Heat {
  Dummy_Head_Enum = 0,
}

#[verus_verify]
impl Default for Heat {
  fn default() -> Self
  {
    Heat::Dummy_Head_Enum
  }
}
