// #Sireum

package base.Gubmo_Structs_Arrays

import org.sireum._
import base._
import base.util.Container

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait ConsumerThr_i_consumer_consumer_PreState_Container extends Container {
  def api_myArrayInt32_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayInt32]
  def api_myArrayStruct_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayStruct]
  def api_myStructArray_EventDataPort: Option[Gubmo_Structs_Arrays.MyStructArray_i]
  def api_myArrayInt32_DataPort: Gubmo_Structs_Arrays.MyArrayInt32
  def api_myArrayStruct_DataPort: Gubmo_Structs_Arrays.MyArrayStruct
  def api_myStructArray_DataPort: Gubmo_Structs_Arrays.MyStructArray_i
}

// container for incoming ports
@datatype class ConsumerThr_i_consumer_consumer_PreState_Container_P (
  val api_myArrayInt32_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayInt32],
  val api_myArrayStruct_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayStruct],
  val api_myStructArray_EventDataPort: Option[Gubmo_Structs_Arrays.MyStructArray_i],
  val api_myArrayInt32_DataPort: Gubmo_Structs_Arrays.MyArrayInt32,
  val api_myArrayStruct_DataPort: Gubmo_Structs_Arrays.MyArrayStruct,
  val api_myStructArray_DataPort: Gubmo_Structs_Arrays.MyStructArray_i) extends ConsumerThr_i_consumer_consumer_PreState_Container

// container for incoming ports and state variables
@datatype class ConsumerThr_i_consumer_consumer_PreState_Container_PS (
  val In_myArrayInt32_StateVar: Gubmo_Structs_Arrays.MyArrayInt32,
  val In_myArrayStruct_StateVar: Gubmo_Structs_Arrays.MyArrayStruct,
  val In_myStructArray_StateVar: Gubmo_Structs_Arrays.MyStructArray_i,
  val api_myArrayInt32_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayInt32],
  val api_myArrayStruct_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayStruct],
  val api_myStructArray_EventDataPort: Option[Gubmo_Structs_Arrays.MyStructArray_i],
  val api_myArrayInt32_DataPort: Gubmo_Structs_Arrays.MyArrayInt32,
  val api_myArrayStruct_DataPort: Gubmo_Structs_Arrays.MyArrayStruct,
  val api_myStructArray_DataPort: Gubmo_Structs_Arrays.MyStructArray_i) extends ConsumerThr_i_consumer_consumer_PreState_Container

@sig trait ConsumerThr_i_consumer_consumer_PostState_Container extends Container {
}

// container for outgoing ports
@datatype class ConsumerThr_i_consumer_consumer_PostState_Container_P (
  ) extends ConsumerThr_i_consumer_consumer_PostState_Container

// container for outgoing ports and state variables
@datatype class ConsumerThr_i_consumer_consumer_PostState_Container_PS (
  val myArrayInt32_StateVar: Gubmo_Structs_Arrays.MyArrayInt32,
  val myArrayStruct_StateVar: Gubmo_Structs_Arrays.MyArrayStruct,
  val myStructArray_StateVar: Gubmo_Structs_Arrays.MyStructArray_i) extends ConsumerThr_i_consumer_consumer_PostState_Container
