[env]
# Maximum number of output verdicts that can be returned at a single timestamp
R2U2_MAX_OUTPUT_VERDICTS = { value = "2", force = true }

# Maximum number of output contract statuses that can be returned at a single timestamp (only utilized when aux_string_specs feature is enabled)
R2U2_MAX_OUTPUT_CONTRACTS = { value = "0", force = true }

# Maximum number of formulas being monitored. Only reserved if R2U2_AUX_STRING_SPECS feature is enabled.
R2U2_AUX_MAX_FORMULAS = { value = "1", force = true }

# Maximum number of assume-guarantee contracts being monitored. Only reserved if R2U2_AUX_STRING_SPECS feature is enabled.
R2U2_AUX_MAX_CONTRACTS = { value = "0", force = true }

# Maximum number of input signals
R2U2_MAX_SIGNALS = { value = "1", force = true }

# Maximum number of Booleans passed from the frontend (from the booleanizer or directly loaded atomics) to the temporal logic engine
R2U2_MAX_ATOMICS = { value = "1", force = true }

# Maximum number of booleanizer instructions. Reserved for the booleanizer engine.
R2U2_MAX_BZ_INSTRUCTIONS = { value = "2", force = true }

# Maximum number of temporal logic instructions. Reserved for the temporal logic engine.
R2U2_MAX_TL_INSTRUCTIONS = { value = "3", force = true }

# Maximum number of SCQ slots for both future-time and past-time reasoning
R2U2_MAX_QUEUE_SLOTS = { value = "3", force = true }

