// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  pub const hamr_ScheduleChannels_DIM_0: usize = 128;

  pub type ScheduleChannels = [u32; hamr_ScheduleChannels_DIM_0];

}

// Memory layout as HAMR computes it
const _: () = assert!(core::mem::size_of::<ScheduleChannels>() == 512);
const _: () = assert!(core::mem::align_of::<ScheduleChannels>() == 4);
