#![cfg_attr(not(test), no_std)]

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#![allow(dead_code)]
#![allow(unreachable_code)]
#![allow(unreachable_patterns)]
#![allow(unused_imports)]
#![allow(unused_macros)]
#![allow(unused_parens)]
#![allow(unused_variables)]

// Required by the Verus build of the containers; unused on a plain cargo build.
#![allow(unused_features)]
#![allow(unexpected_cfgs)]

#![feature(proc_macro_hygiene)]
#![cfg_attr(not(verus_keep_ghost), feature(stmt_expr_attributes))]

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Contract checks shared by the gumbo and sys-assert monitor PDs and the test
//! controller (TestScheduler-design.md, stage 7).  Each consumer supplies a
//! SystemView to read ports and state variables through, a ViolationSink to
//! report to, and the thread each check is about.

pub mod gumbox;
pub mod components;
#[macro_use]
pub mod sys_assert_functions;
pub mod sys_nominal;

use data::*;

/// The model's threads.  Channel ids belong to an MSD variant; each consumer maps
/// its own channels onto these.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Thread {
  tsp_tst,
  tcp_tct,
  fp_ft,
}

/// How the checks read ports and state variables.  Each getter returns what the
/// monitors' API getter of the same name returns.
pub trait SystemView {
  fn get_tcp_tct_sv_currentFanState(&mut self) -> TempControl_SysVerif::FanCmd;
  fn get_tcp_tct_sv_currentSetPoint(&mut self) -> TempControl_SysVerif::SetPoint;
  fn get_tcp_tct_sv_fanError(&mut self) -> bool;
  fn get_tcp_tct_sv_latestTemp(&mut self) -> TempControl_SysVerif::Temperature;
  fn get_tcp_tct_fanCmd(&mut self) -> Option<TempControl_SysVerif::FanCmd>;
  fn get_tsp_tst_currentTemp(&mut self) -> Option<TempControl_SysVerif::Temperature>;
  fn get_fp_ft_fanAck(&mut self) -> Option<TempControl_SysVerif::FanAck>;
  fn get_tcp_tct_setPoint(&mut self) -> Option<TempControl_SysVerif::SetPoint>;
}

/// A check's outcome worth reporting.
pub enum Event<'a> {
  IepPostViolation { thread: &'static str, post: &'a dyn core::fmt::Debug },
  CepPreViolation { thread: &'static str, pre: &'a dyn core::fmt::Debug },
  CepPostViolation { thread: &'static str, pre: &'a dyn core::fmt::Debug, post: &'a dyn core::fmt::Debug },
  /// No pre-state was saved for the completing dispatch.
  CepPostSkipped { thread: &'static str },
  /// The dispatch's CEP_Pre failed and excuse_post_on_failed_pre is set.
  CepPostExcused { thread: &'static str },
  SysAssertViolation { property: &'static str, point: &'static str },
  ScheduleNoTransition { ch: u32, timeslice: usize },
  ScheduleNoEnd { ready: u64 },
  ScheduleConformance { violations: u32 },
}

pub trait ViolationSink {
  fn report(&mut self, e: Event);
}
