// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! The system assertions of composition `nominal`, checked along the
//! schedule's workflow net: a place is an assertion point, a transition is a
//! thread's dispatch or a control point (split/join).

use data::*;
use crate::sys_assert_functions::*;
use crate::{Event, SystemView, ViolationSink};

const PLACE_START: u64 = 1u64 << 0;
const PLACE_AFTER_SENSOR: u64 = 1u64 << 1;
const PLACE_AFTER_CONTROL: u64 = 1u64 << 2;
const PLACE_AFTER_FAN: u64 = 1u64 << 3;
const PLACE_END: u64 = 1u64 << 4;

const CP_TRANSITIONS: [(u64, u64); 1] = [
  (PLACE_AFTER_FAN, PLACE_END)
];

/// Component transitions as (thread, in_mask, out_mask).
const COMPONENT_TRANSITIONS: [(crate::Thread, u64, u64); 3] = [
  (crate::Thread::tsp_tst, PLACE_START, PLACE_AFTER_SENSOR),
  (crate::Thread::tcp_tct, PLACE_AFTER_SENSOR, PLACE_AFTER_CONTROL),
  (crate::Thread::fp_ft, PLACE_AFTER_CONTROL, PLACE_AFTER_FAN)
];

/// Fires every enabled control-point transition until none is enabled.  The
/// marking is a bitmask with one bit per place; firing a transition removes its
/// in-place bits and sets its out-place bits.
fn cascade(mut ready: u64) -> u64 {
  let mut changed = true;
  while changed {
    changed = false;
    for &(in_mask, out_mask) in CP_TRANSITIONS.iter() {
      if (ready & in_mask) == in_mask {
        ready = (ready & !in_mask) | out_mask;
        changed = true;
      }
    }
  }
  ready
}

/// As [`cascade`], also returning every place it entered -- the out-places of
/// each transition it fired.  A place that was already marked and stays marked
/// (waiting at a join, say) is not among them.
fn cascade_acc(mut ready: u64) -> (u64, u64) {
  let mut entered = 0u64;
  let mut changed = true;
  while changed {
    changed = false;
    for &(in_mask, out_mask) in CP_TRANSITIONS.iter() {
      if (ready & in_mask) == in_mask {
        ready = (ready & !in_mask) | out_mask;
        entered |= out_mask;
        changed = true;
      }
    }
  }
  (ready, entered)
}

pub struct SysAssert_nominal {
  ready: u64,
}

impl SysAssert_nominal {
  pub const fn new() -> Self {
    SysAssert_nominal { ready: 0 }
  }

  /// Walks the whole net over one hyperperiod of the schedule -- its first
  /// `num_timeslices` slots' channels and user-partition bits -- checking that every
  /// user slot of a thread in the composition has an enabled transition and that the
  /// walk reaches END.  Threads the composition leaves out are passed over.
  /// Takes plain slices rather than a `hamr::Schedule`: the test controller has its
  /// own copy of the schedule, and without runtime monitoring the data crate has no
  /// `hamr` module at all.
  pub fn validate_schedule<S: ViolationSink>(num_timeslices: usize,
                                            timeslice_ch: &[u32],
                                            is_user_partition: &[bool],
                                            thread_of: fn(u32) -> Option<crate::Thread>,
                                            out: &mut S) {
    let n = core::cmp::min(num_timeslices, core::cmp::min(timeslice_ch.len(), is_user_partition.len()));
    let mut ready: u64 = PLACE_START;
    ready = cascade(ready);
    let mut violations = 0u32;

    for i in 0..n {
      if !is_user_partition[i] {
        continue;
      }
      let ch = timeslice_ch[i];
      let th = thread_of(ch);
      // A thread the composition leaves out is not part of what it claims, so its
      // slots are passed over: the composition may describe part of the system.
      if !COMPONENT_TRANSITIONS.iter().any(|&(t_th, _, _)| th == Some(t_th)) {
        continue;
      }

      let mut fired = false;
      for &(t_th, in_mask, out_mask) in COMPONENT_TRANSITIONS.iter() {
        if th == Some(t_th) && (ready & in_mask) == in_mask {
          ready = (ready & !in_mask) | out_mask;
          ready = cascade(ready);
          fired = true;
          break;
        }
      }

      if !fired {
        out.report(Event::ScheduleNoTransition { ch: ch, timeslice: i });
        violations += 1;
      }
    }

    if ready != PLACE_END {
      out.report(Event::ScheduleNoEnd { ready: ready });
      violations += 1;
    }

    out.report(Event::ScheduleConformance { violations: violations });
  }

  /// Puts the marking at START, fires the initial cascade, and checks the
  /// assertions at the places it entered.
  pub fn on_init<V: SystemView, S: ViolationSink>(&mut self, s: &mut V, out: &mut S) {
    let entered = self.restart();
    Self::check(entered, s, out);
  }

  /// Marks START and cascades; returns the places entered.
  fn restart(&mut self) -> u64 {
    let (ready, entered) = cascade_acc(PLACE_START);
    self.ready = ready;
    PLACE_START | entered
  }

  /// `prev` has completed a dispatch: fire its transition, cascade, and check
  /// the assertions at every place entered on the way -- the places this completion
  /// reached, not every place still marked.  An assertion "after X" is about the
  /// moment X completes; checking it again at later, unrelated completions while its
  /// place waits at a join would compare X's outputs with inputs that have moved on.
  ///
  /// When this completion ends the frame, the next one starts here.  Events belong to
  /// the frame they arrived in, so what START sees is only what arrives from here on.
  pub fn on_complete<V: SystemView, S: ViolationSink>(&mut self, prev: crate::Thread, s: &mut V, out: &mut S) {
    if self.complete(prev, s, out) {
      s.frame_ended(0);
      self.restart_frame(s, out);
    }
  }

  /// The first half of `on_complete`: fire, cascade and check; returns whether the
  /// marking reached END.  Each composition keeps its own frame: its end is reported
  /// to the view as `frame_ended` for this composition alone, before `restart_frame`.
  pub fn complete<V: SystemView, S: ViolationSink>(&mut self, prev: crate::Thread, s: &mut V, out: &mut S) -> bool {
    // the out-places of the transition this completion fired
    let entered: u64 = match prev {
      crate::Thread::tsp_tst => {
        self.ready = (self.ready & !PLACE_START) | PLACE_AFTER_SENSOR;
        PLACE_AFTER_SENSOR
      }
      crate::Thread::tcp_tct => {
        self.ready = (self.ready & !PLACE_AFTER_SENSOR) | PLACE_AFTER_CONTROL;
        PLACE_AFTER_CONTROL
      }
      crate::Thread::fp_ft => {
        self.ready = (self.ready & !PLACE_AFTER_CONTROL) | PLACE_AFTER_FAN;
        PLACE_AFTER_FAN
      }
      _ => {
        return false;
      }
    };

    let (final_ready, cascaded) = cascade_acc(self.ready);
    self.ready = final_ready;
    Self::check(entered | cascaded, s, out);
    self.ready == PLACE_END
  }

  /// The second half of `on_complete`, once the frame has ended: mark START, cascade,
  /// and check the assertions at the places entered.
  pub fn restart_frame<V: SystemView, S: ViolationSink>(&mut self, s: &mut V, out: &mut S) {
    let started = self.restart();
    Self::check(started, s, out);
  }

  /// Checks the assertions at the places in `visited`.
  fn check<V: SystemView, S: ViolationSink>(visited: u64, s: &mut V, out: &mut S) {
    if visited & PLACE_START != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_01", point: "at START" });
      }
    }
    if visited & PLACE_AFTER_SENSOR != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_01", point: "after sensor" });
      }
    }
    if visited & PLACE_AFTER_CONTROL != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On))) &
             (impliesL!(
               s.get_tsp_tst_currentTemp().is_some() &&
                 !s.get_tcp_tct_sv_fanError() &
                   (s.get_tsp_tst_currentTemp().unwrap().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_01", point: "after control" });
      }
    }
    if visited & PLACE_AFTER_FAN != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_01", point: "after fan" });
      }
    }
    if visited & PLACE_END != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_01", point: "at END" });
      }
    }
    if visited & PLACE_START != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_02", point: "at START" });
      }
    }
    if visited & PLACE_AFTER_SENSOR != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_02", point: "after sensor" });
      }
    }
    if visited & PLACE_AFTER_CONTROL != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On))) &
             (impliesL!(
               s.get_tsp_tst_currentTemp().is_some() &&
                 !s.get_tcp_tct_sv_fanError() &
                   (s.get_tsp_tst_currentTemp().unwrap().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_02", point: "after control" });
      }
    }
    if visited & PLACE_AFTER_FAN != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_02", point: "after fan" });
      }
    }
    if visited & PLACE_END != 0 {
      s.focus(None);
      s.focus_system(0);
      if !((impliesL!(
             !s.get_tcp_tct_sv_fanError() &
               (s.get_tcp_tct_sv_latestTemp().degrees < s.get_tcp_tct_sv_currentSetPoint().low.degrees),
             (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::Off))) &
             (impliesL!(
               !s.get_tcp_tct_sv_fanError() &
                 (s.get_tcp_tct_sv_latestTemp().degrees > s.get_tcp_tct_sv_currentSetPoint().high.degrees),
               (s.get_tcp_tct_sv_currentFanState() == TempControl_SysVerif::FanCmd::On)))) && !s.missing() {
        out.report(crate::Event::SysAssertViolation { property: "TC_Req_02", point: "at END" });
      }
    }
  }
}
