#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// The C base types, laid out as HAMR computes them
_Static_assert(sizeof(bool) == 1, "bool: memory layout differs from HAMR's");
_Static_assert(_Alignof(bool) == 1, "bool: memory layout differs from HAMR's");

_Static_assert(sizeof(char) == 1, "char: memory layout differs from HAMR's");
_Static_assert(_Alignof(char) == 1, "char: memory layout differs from HAMR's");

_Static_assert(sizeof(int8_t) == 1, "int8_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(int8_t) == 1, "int8_t: memory layout differs from HAMR's");

_Static_assert(sizeof(int16_t) == 2, "int16_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(int16_t) == 2, "int16_t: memory layout differs from HAMR's");

_Static_assert(sizeof(int32_t) == 4, "int32_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(int32_t) == 4, "int32_t: memory layout differs from HAMR's");

_Static_assert(sizeof(int64_t) == 8, "int64_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(int64_t) == 8, "int64_t: memory layout differs from HAMR's");

_Static_assert(sizeof(uint8_t) == 1, "uint8_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(uint8_t) == 1, "uint8_t: memory layout differs from HAMR's");

_Static_assert(sizeof(uint16_t) == 2, "uint16_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(uint16_t) == 2, "uint16_t: memory layout differs from HAMR's");

_Static_assert(sizeof(uint32_t) == 4, "uint32_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(uint32_t) == 4, "uint32_t: memory layout differs from HAMR's");

_Static_assert(sizeof(uint64_t) == 8, "uint64_t: memory layout differs from HAMR's");
_Static_assert(_Alignof(uint64_t) == 8, "uint64_t: memory layout differs from HAMR's");

_Static_assert(sizeof(float) == 4, "float: memory layout differs from HAMR's");
_Static_assert(_Alignof(float) == 4, "float: memory layout differs from HAMR's");

_Static_assert(sizeof(double) == 8, "double: memory layout differs from HAMR's");
_Static_assert(_Alignof(double) == 8, "double: memory layout differs from HAMR's");


// Validity of a value read from shared memory (D6).  Only bool, and the enums and the
// records and arrays containing them, have invalid bit patterns; the rest are always
// valid.  A bool is read as a byte, since reading a bool object that holds neither 0 nor
// 1 is itself undefined.
static inline bool bool_is_valid(const bool *v) { return *(const uint8_t *) v <= 1; }
static inline bool char_is_valid(const char *v) { (void) v; return true; }
static inline bool int8_t_is_valid(const int8_t *v) { (void) v; return true; }
static inline bool int16_t_is_valid(const int16_t *v) { (void) v; return true; }
static inline bool int32_t_is_valid(const int32_t *v) { (void) v; return true; }
static inline bool int64_t_is_valid(const int64_t *v) { (void) v; return true; }
static inline bool uint8_t_is_valid(const uint8_t *v) { (void) v; return true; }
static inline bool uint16_t_is_valid(const uint16_t *v) { (void) v; return true; }
static inline bool uint32_t_is_valid(const uint32_t *v) { (void) v; return true; }
static inline bool uint64_t_is_valid(const uint64_t *v) { (void) v; return true; }
static inline bool float_is_valid(const float *v) { (void) v; return true; }
static inline bool double_is_valid(const double *v) { (void) v; return true; }

#define data_1_prod_2_cons_struct_ArrayOfInts_DIM_0 10

typedef int32_t data_1_prod_2_cons_struct_ArrayOfInts [data_1_prod_2_cons_struct_ArrayOfInts_DIM_0];

#define data_1_prod_2_cons_struct_ArrayOfInts_BYTE_SIZE (sizeof(data_1_prod_2_cons_struct_ArrayOfInts))

_Static_assert(sizeof(data_1_prod_2_cons_struct_ArrayOfInts) == 40, "data_1_prod_2_cons_struct_ArrayOfInts: memory layout differs from HAMR's");
_Static_assert(_Alignof(data_1_prod_2_cons_struct_ArrayOfInts) == 4, "data_1_prod_2_cons_struct_ArrayOfInts: memory layout differs from HAMR's");


static inline bool data_1_prod_2_cons_struct_ArrayOfInts_is_valid(const data_1_prod_2_cons_struct_ArrayOfInts *v) {
  for (size_t i = 0; i < data_1_prod_2_cons_struct_ArrayOfInts_DIM_0; i++) {
    if (!int32_t_is_valid(&(*v)[i])) {
      return false;
    }
  }
  return true;
}

typedef struct data_1_prod_2_cons_struct_struct_i {
  int32_t size;
  data_1_prod_2_cons_struct_ArrayOfInts elements;
} data_1_prod_2_cons_struct_struct_i;

_Static_assert(sizeof(data_1_prod_2_cons_struct_struct_i) == 44, "data_1_prod_2_cons_struct_struct_i: memory layout differs from HAMR's");
_Static_assert(_Alignof(data_1_prod_2_cons_struct_struct_i) == 4, "data_1_prod_2_cons_struct_struct_i: memory layout differs from HAMR's");
_Static_assert(offsetof(data_1_prod_2_cons_struct_struct_i, size) == 0, "data_1_prod_2_cons_struct_struct_i: memory layout differs from HAMR's");
_Static_assert(offsetof(data_1_prod_2_cons_struct_struct_i, elements) == 4, "data_1_prod_2_cons_struct_struct_i: memory layout differs from HAMR's");

static inline bool data_1_prod_2_cons_struct_struct_i_is_valid(const data_1_prod_2_cons_struct_struct_i *v) {
  return int32_t_is_valid(&v->size) &&
                  data_1_prod_2_cons_struct_ArrayOfInts_is_valid(&v->elements);
}
