// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait producer_p_p1_producer_Api {}

  pub trait producer_p_p1_producer_Put_Api: producer_p_p1_producer_Api {
    #[verifier::external_body]
    fn unverified_put_write_port(&mut self)
    {
      extern_api::unsafe_put_write_port();
    }
  }

  pub trait producer_p_p1_producer_Get_Api: producer_p_p1_producer_Api {
  }

  pub trait producer_p_p1_producer_Full_Api: producer_p_p1_producer_Put_Api + producer_p_p1_producer_Get_Api {}

  pub struct producer_p_p1_producer_Application_Api<API: producer_p_p1_producer_Api> {
    pub api: API,

    pub ghost write_port: Option<u8>
  }

  impl<API: producer_p_p1_producer_Put_Api> producer_p_p1_producer_Application_Api<API> {
    pub fn put_write_port(&mut self)
      ensures
        self.write_port == Some(0u8),
    {
      self.api.unverified_put_write_port();
      self.write_port = Some(0u8);
    }
  }

  impl<API: producer_p_p1_producer_Get_Api> producer_p_p1_producer_Application_Api<API> {
  }

  pub struct producer_p_p1_producer_Initialization_Api;
  impl producer_p_p1_producer_Api for producer_p_p1_producer_Initialization_Api {}
  impl producer_p_p1_producer_Put_Api for producer_p_p1_producer_Initialization_Api {}

  pub const fn init_api() -> producer_p_p1_producer_Application_Api<producer_p_p1_producer_Initialization_Api> {
    return producer_p_p1_producer_Application_Api {
      api: producer_p_p1_producer_Initialization_Api {},

      write_port: None
    }
  }

  pub struct producer_p_p1_producer_Compute_Api;
  impl producer_p_p1_producer_Api for producer_p_p1_producer_Compute_Api {}
  impl producer_p_p1_producer_Put_Api for producer_p_p1_producer_Compute_Api {}
  impl producer_p_p1_producer_Get_Api for producer_p_p1_producer_Compute_Api {}
  impl producer_p_p1_producer_Full_Api for producer_p_p1_producer_Compute_Api {}

  pub const fn compute_api() -> producer_p_p1_producer_Application_Api<producer_p_p1_producer_Compute_Api> {
    return producer_p_p1_producer_Application_Api {
      api: producer_p_p1_producer_Compute_Api {},

      write_port: None
    }
  }
}