// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Write frames -- per component, the global frame constrains every
//! SystemState field outside the component's write set to be unchanged
//! across its firing; the local frame is `true`.

#![allow(non_snake_case)]

use vstd::prelude::*;

use crate::system_state::SystemState;

verus! {

/** SENSOR writes: sensedTemp.
  * Everything else must be unchanged.
  */
pub open spec fn sensor_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.setPoint == post.setPoint
  && pre.fanCmd == post.fanCmd
  && pre.sv_currentSetPoint == post.sv_currentSetPoint
  && pre.sv_currentFanState == post.sv_currentFanState
  && pre.sv_latestTemp == post.sv_latestTemp
  && pre.sv_fanError == post.sv_fanError
  && pre.fanAck == post.fanAck
}

/** SENSOR local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn sensor_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** CONTROL writes: fanCmd, sv_currentSetPoint, sv_currentFanState, sv_latestTemp, sv_fanError.
  * Everything else must be unchanged.
  */
pub open spec fn control_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.sensedTemp == post.sensedTemp
  && pre.setPoint == post.setPoint
  && pre.fanAck == post.fanAck
}

/** CONTROL local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn control_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** FAN writes: fanAck.
  * Everything else must be unchanged.
  */
pub open spec fn fan_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.sensedTemp == post.sensedTemp
  && pre.setPoint == post.setPoint
  && pre.fanCmd == post.fanCmd
  && pre.sv_currentSetPoint == post.sv_currentSetPoint
  && pre.sv_currentFanState == post.sv_currentFanState
  && pre.sv_latestTemp == post.sv_latestTemp
  && pre.sv_fanError == post.sv_fanError
}

/** FAN local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn fan_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** DOMAIN_MONITOR_THREAD writes: nothing.
  * Everything else must be unchanged.
  */
pub open spec fn domain_monitor_thread_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.sensedTemp == post.sensedTemp
  && pre.setPoint == post.setPoint
  && pre.fanCmd == post.fanCmd
  && pre.sv_currentSetPoint == post.sv_currentSetPoint
  && pre.sv_currentFanState == post.sv_currentFanState
  && pre.sv_latestTemp == post.sv_latestTemp
  && pre.sv_fanError == post.sv_fanError
  && pre.fanAck == post.fanAck
}

/** DOMAIN_MONITOR_THREAD local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn domain_monitor_thread_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

} // verus!
