#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool ArduPilot_ArduPilot_EthernetFramesTx_is_empty(void);
bool get_ArduPilot_ArduPilot_EthernetFramesTx_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_ArduPilot_ArduPilot_EthernetFramesTx(SW_RawEthernetMessage *data);
bool Firewall_Firewall_EthernetFramesRxOut_is_empty(void);
bool get_Firewall_Firewall_EthernetFramesRxOut_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_Firewall_Firewall_EthernetFramesRxOut(SW_RawEthernetMessage *data);
bool Firewall_Firewall_EthernetFramesTxOut_is_empty(void);
bool get_Firewall_Firewall_EthernetFramesTxOut_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_Firewall_Firewall_EthernetFramesTxOut(SW_RawEthernetMessage *data);
bool LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx_is_empty(void);
bool get_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(SW_RawEthernetMessage *data);
