// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn Gubmo_Structs_Arrays_MyEnum_strategy_default() -> impl Strategy<Value = Gubmo_Structs_Arrays::MyEnum>
{
  Gubmo_Structs_Arrays_MyEnum_strategy_cust(1, 1)
}

pub fn Gubmo_Structs_Arrays_MyEnum_strategy_cust(
  On_bias: u32,
  Off_bias: u32) -> impl Strategy<Value = Gubmo_Structs_Arrays::MyEnum>
{
  prop_oneof![
    On_bias => Just(Gubmo_Structs_Arrays::MyEnum::On),
    Off_bias => Just(Gubmo_Structs_Arrays::MyEnum::Off)
  ]
}

pub fn Gubmo_Structs_Arrays_MyArrayInt32_strategy_default() -> impl Strategy<Value = Gubmo_Structs_Arrays::MyArrayInt32>
{
  Gubmo_Structs_Arrays_MyArrayInt32_strategy_cust(any::<i32>())
}

pub fn Gubmo_Structs_Arrays_MyArrayInt32_strategy_cust<i32_strategy: Strategy<Value = i32>> (base_strategy: i32_strategy) -> impl Strategy<Value = Gubmo_Structs_Arrays::MyArrayInt32>
{
  proptest::collection::vec(base_strategy, Gubmo_Structs_Arrays::Gubmo_Structs_Arrays_MyArrayInt32_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[i32; Gubmo_Structs_Arrays::Gubmo_Structs_Arrays_MyArrayInt32_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Gubmo_Structs_Arrays_MyStruct2_i_strategy_default() -> impl Strategy<Value = Gubmo_Structs_Arrays::MyStruct2_i>
{
  Gubmo_Structs_Arrays_MyStruct2_i_strategy_cust(
    any::<i32>()
  )
}

pub fn Gubmo_Structs_Arrays_MyStruct2_i_strategy_cust<fieldSInt32_i32_strategy: Strategy<Value = i32>> (fieldSInt32_strategy: fieldSInt32_i32_strategy) -> impl Strategy<Value = Gubmo_Structs_Arrays::MyStruct2_i>
{
  (fieldSInt32_strategy).prop_map(|(fieldSInt32)| {
    Gubmo_Structs_Arrays::MyStruct2_i { fieldSInt32 }
  })
}

pub fn Gubmo_Structs_Arrays_MyArrayStruct_strategy_default() -> impl Strategy<Value = Gubmo_Structs_Arrays::MyArrayStruct>
{
  Gubmo_Structs_Arrays_MyArrayStruct_strategy_cust(Gubmo_Structs_Arrays_MyStruct2_i_strategy_default())
}

pub fn Gubmo_Structs_Arrays_MyArrayStruct_strategy_cust<Gubmo_Structs_Arrays_MyStruct2_i_strategy: Strategy<Value = Gubmo_Structs_Arrays::MyStruct2_i>> (base_strategy: Gubmo_Structs_Arrays_MyStruct2_i_strategy) -> impl Strategy<Value = Gubmo_Structs_Arrays::MyArrayStruct>
{
  proptest::collection::vec(base_strategy, Gubmo_Structs_Arrays::Gubmo_Structs_Arrays_MyArrayStruct_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[Gubmo_Structs_Arrays::MyStruct2_i; Gubmo_Structs_Arrays::Gubmo_Structs_Arrays_MyArrayStruct_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Gubmo_Structs_Arrays_MyStructArray_i_strategy_default() -> impl Strategy<Value = Gubmo_Structs_Arrays::MyStructArray_i>
{
  Gubmo_Structs_Arrays_MyStructArray_i_strategy_cust(
    any::<i64>(),
    Gubmo_Structs_Arrays_MyStruct2_i_strategy_default(),
    Gubmo_Structs_Arrays_MyArrayStruct_strategy_default(),
    Gubmo_Structs_Arrays_MyEnum_strategy_default()
  )
}

pub fn Gubmo_Structs_Arrays_MyStructArray_i_strategy_cust
  <fieldInt64_i64_strategy: Strategy<Value = i64>, 
   fieldRec_Gubmo_Structs_Arrays_MyStruct2_i_strategy: Strategy<Value = Gubmo_Structs_Arrays::MyStruct2_i>, 
   fieldArray_Gubmo_Structs_Arrays_MyArrayStruct_strategy: Strategy<Value = Gubmo_Structs_Arrays::MyArrayStruct>, 
   fieldEnum_Gubmo_Structs_Arrays_MyEnum_strategy: Strategy<Value = Gubmo_Structs_Arrays::MyEnum>> (
  fieldInt64_strategy: fieldInt64_i64_strategy,
  fieldRec_strategy: fieldRec_Gubmo_Structs_Arrays_MyStruct2_i_strategy,
  fieldArray_strategy: fieldArray_Gubmo_Structs_Arrays_MyArrayStruct_strategy,
  fieldEnum_strategy: fieldEnum_Gubmo_Structs_Arrays_MyEnum_strategy) -> impl Strategy<Value = Gubmo_Structs_Arrays::MyStructArray_i>
{
  (fieldInt64_strategy, fieldRec_strategy, fieldArray_strategy, fieldEnum_strategy).prop_map(|(fieldInt64, fieldRec, fieldArray, fieldEnum)| {
    Gubmo_Structs_Arrays::MyStructArray_i { fieldInt64, fieldRec, fieldArray, fieldEnum }
  })
}
