// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_c_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
  pub api_c_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
  pub api_c_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  pub api_c_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
  pub api_c_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
  pub api_c_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_myArrayInt32_StateVar: Gubmo_Structs_Arrays::MyArrayInt32,
  pub In_myArrayStruct_StateVar: Gubmo_Structs_Arrays::MyArrayStruct,
  pub In_myStructArray_StateVar: Gubmo_Structs_Arrays::MyStructArray_i,
  pub api_c_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
  pub api_c_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
  pub api_c_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  pub api_c_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
  pub api_c_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
  pub api_c_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_c_myArrayInt32_DataPort(container.api_c_myArrayInt32_DataPort);
  put_c_myArrayStruct_DataPort(container.api_c_myArrayStruct_DataPort);
  put_c_myStructArray_DataPort(container.api_c_myStructArray_DataPort);
  put_c_myArrayInt32_EventDataPort(container.api_c_myArrayInt32_EventDataPort);
  put_c_myArrayStruct_EventDataPort(container.api_c_myArrayStruct_EventDataPort);
  put_c_myStructArray_EventDataPort(container.api_c_myStructArray_EventDataPort);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_myStructArray_StateVar(container.In_myStructArray_StateVar);
  put_myArrayStruct_StateVar(container.In_myArrayStruct_StateVar);
  put_myArrayInt32_StateVar(container.In_myArrayInt32_StateVar);
  put_c_myArrayInt32_DataPort(container.api_c_myArrayInt32_DataPort);
  put_c_myArrayStruct_DataPort(container.api_c_myArrayStruct_DataPort);
  put_c_myStructArray_DataPort(container.api_c_myStructArray_DataPort);
  put_c_myArrayInt32_EventDataPort(container.api_c_myArrayInt32_EventDataPort);
  put_c_myArrayStruct_EventDataPort(container.api_c_myArrayStruct_EventDataPort);
  put_c_myStructArray_EventDataPort(container.api_c_myStructArray_EventDataPort);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  c_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
  c_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
  c_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  c_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
  c_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
  c_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>)
{
  put_c_myArrayInt32_DataPort(c_myArrayInt32_DataPort);
  put_c_myArrayStruct_DataPort(c_myArrayStruct_DataPort);
  put_c_myStructArray_DataPort(c_myStructArray_DataPort);
  put_c_myArrayInt32_EventDataPort(c_myArrayInt32_EventDataPort);
  put_c_myArrayStruct_EventDataPort(c_myArrayStruct_EventDataPort);
  put_c_myStructArray_EventDataPort(c_myStructArray_EventDataPort);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_myArrayInt32_StateVar: Gubmo_Structs_Arrays::MyArrayInt32,
  In_myArrayStruct_StateVar: Gubmo_Structs_Arrays::MyArrayStruct,
  In_myStructArray_StateVar: Gubmo_Structs_Arrays::MyStructArray_i,
  c_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
  c_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
  c_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  c_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
  c_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
  c_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>)
{
  put_myStructArray_StateVar(In_myStructArray_StateVar);
  put_myArrayStruct_StateVar(In_myArrayStruct_StateVar);
  put_myArrayInt32_StateVar(In_myArrayInt32_StateVar);
  put_c_myArrayInt32_DataPort(c_myArrayInt32_DataPort);
  put_c_myArrayStruct_DataPort(c_myArrayStruct_DataPort);
  put_c_myStructArray_DataPort(c_myStructArray_DataPort);
  put_c_myArrayInt32_EventDataPort(c_myArrayInt32_EventDataPort);
  put_c_myArrayStruct_EventDataPort(c_myArrayStruct_EventDataPort);
  put_c_myStructArray_EventDataPort(c_myStructArray_EventDataPort);
}

/// setter for IN DataPort
pub fn put_c_myArrayInt32_DataPort(value: Gubmo_Structs_Arrays::MyArrayInt32)
{
  *extern_api::IN_c_myArrayInt32_DataPort.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_c_myArrayStruct_DataPort(value: Gubmo_Structs_Arrays::MyArrayStruct)
{
  *extern_api::IN_c_myArrayStruct_DataPort.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_c_myStructArray_DataPort(value: Gubmo_Structs_Arrays::MyStructArray_i)
{
  *extern_api::IN_c_myStructArray_DataPort.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN EventDataPort
pub fn put_c_myArrayInt32_EventDataPort(value: Option<Gubmo_Structs_Arrays::MyArrayInt32>)
{
  *extern_api::IN_c_myArrayInt32_EventDataPort.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_c_myArrayStruct_EventDataPort(value: Option<Gubmo_Structs_Arrays::MyArrayStruct>)
{
  *extern_api::IN_c_myArrayStruct_EventDataPort.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_c_myStructArray_EventDataPort(value: Option<Gubmo_Structs_Arrays::MyStructArray_i>)
{
  *extern_api::IN_c_myStructArray_EventDataPort.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for GUMBO State Variable
pub fn get_myArrayInt32_StateVar() -> Gubmo_Structs_Arrays::MyArrayInt32
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.myArrayInt32_StateVar,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_myArrayInt32_StateVar(value: Gubmo_Structs_Arrays::MyArrayInt32)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.myArrayInt32_StateVar = value,
      None => panic!("The app is None")
    }
  }
}

/// getter for GUMBO State Variable
pub fn get_myArrayStruct_StateVar() -> Gubmo_Structs_Arrays::MyArrayStruct
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.myArrayStruct_StateVar,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_myArrayStruct_StateVar(value: Gubmo_Structs_Arrays::MyArrayStruct)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.myArrayStruct_StateVar = value,
      None => panic!("The app is None")
    }
  }
}

/// getter for GUMBO State Variable
pub fn get_myStructArray_StateVar() -> Gubmo_Structs_Arrays::MyStructArray_i
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.myStructArray_StateVar,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_myStructArray_StateVar(value: Gubmo_Structs_Arrays::MyStructArray_i)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.myStructArray_StateVar = value,
      None => panic!("The app is None")
    }
  }
}
