// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

use super::Base_Types::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct MyStruct_i {
    pub fieldInt64: i64,
    pub fieldStr: String,
    pub fieldEnum: MyEnum,
    pub fieldRec: MyStruct2_i,
    pub fieldArray: MyArrayOneDim
  }

  impl Default for MyStruct_i {
    fn default() -> Self 
    {
      Self { fieldInt64: 0, fieldStr: [0; Base_Types::Base_Types_String_DIM_0], fieldEnum: Aadl_Datatypes::MyEnum::default(), fieldRec: Aadl_Datatypes::MyStruct2_i::default(), fieldArray: [0; Aadl_Datatypes::Aadl_Datatypes_MyArrayOneDim_DIM_0] }
    }
  }
}