// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

/// default proptest strategy for i64: any value of the type
pub fn i64_strategy_default() -> impl Strategy<Value = i64>
{
  any::<i64>()
}

/// custom proptest strategy for i64 restricted to an inclusive range
pub fn i64_strategy_cust(range: core::ops::RangeInclusive<i64>) -> impl Strategy<Value = i64>
{
  range
}

pub fn Gumbo_Structs_Arrays_MyEnum_strategy_default() -> impl Strategy<Value = Gumbo_Structs_Arrays::MyEnum>
{
  Gumbo_Structs_Arrays_MyEnum_strategy_cust(1, 1)
}

pub fn Gumbo_Structs_Arrays_MyEnum_strategy_cust(
  On_bias: u32,
  Off_bias: u32) -> impl Strategy<Value = Gumbo_Structs_Arrays::MyEnum>
{
  prop_oneof![
    On_bias => Just(Gumbo_Structs_Arrays::MyEnum::On),
    Off_bias => Just(Gumbo_Structs_Arrays::MyEnum::Off)
  ]
}

/// default proptest strategy for i32: any value of the type
pub fn i32_strategy_default() -> impl Strategy<Value = i32>
{
  any::<i32>()
}

/// custom proptest strategy for i32 restricted to an inclusive range
pub fn i32_strategy_cust(range: core::ops::RangeInclusive<i32>) -> impl Strategy<Value = i32>
{
  range
}

/// default proptest strategy for bool: any value of the type
pub fn bool_strategy_default() -> impl Strategy<Value = bool>
{
  any::<bool>()
}

/// default proptest strategy for i8: any value of the type
pub fn i8_strategy_default() -> impl Strategy<Value = i8>
{
  any::<i8>()
}

/// custom proptest strategy for i8 restricted to an inclusive range
pub fn i8_strategy_cust(range: core::ops::RangeInclusive<i8>) -> impl Strategy<Value = i8>
{
  range
}

/// default proptest strategy for i16: any value of the type
pub fn i16_strategy_default() -> impl Strategy<Value = i16>
{
  any::<i16>()
}

/// custom proptest strategy for i16 restricted to an inclusive range
pub fn i16_strategy_cust(range: core::ops::RangeInclusive<i16>) -> impl Strategy<Value = i16>
{
  range
}

/// default proptest strategy for u8: any value of the type
pub fn u8_strategy_default() -> impl Strategy<Value = u8>
{
  any::<u8>()
}

/// custom proptest strategy for u8 restricted to an inclusive range
pub fn u8_strategy_cust(range: core::ops::RangeInclusive<u8>) -> impl Strategy<Value = u8>
{
  range
}

/// default proptest strategy for u16: any value of the type
pub fn u16_strategy_default() -> impl Strategy<Value = u16>
{
  any::<u16>()
}

/// custom proptest strategy for u16 restricted to an inclusive range
pub fn u16_strategy_cust(range: core::ops::RangeInclusive<u16>) -> impl Strategy<Value = u16>
{
  range
}

/// default proptest strategy for u32: any value of the type
pub fn u32_strategy_default() -> impl Strategy<Value = u32>
{
  any::<u32>()
}

/// custom proptest strategy for u32 restricted to an inclusive range
pub fn u32_strategy_cust(range: core::ops::RangeInclusive<u32>) -> impl Strategy<Value = u32>
{
  range
}

/// default proptest strategy for u64: any value of the type
pub fn u64_strategy_default() -> impl Strategy<Value = u64>
{
  any::<u64>()
}

/// custom proptest strategy for u64 restricted to an inclusive range
pub fn u64_strategy_cust(range: core::ops::RangeInclusive<u64>) -> impl Strategy<Value = u64>
{
  range
}

pub fn Gumbo_Structs_Arrays_MyStruct2_i_strategy_default() -> impl Strategy<Value = Gumbo_Structs_Arrays::MyStruct2_i>
{
  Gumbo_Structs_Arrays_MyStruct2_i_strategy_cust(
    any::<i32>()
  )
}

pub fn Gumbo_Structs_Arrays_MyStruct2_i_strategy_cust<fieldSInt32_i32_strategy: Strategy<Value = i32>> (fieldSInt32_strategy: fieldSInt32_i32_strategy) -> impl Strategy<Value = Gumbo_Structs_Arrays::MyStruct2_i>
{
  (fieldSInt32_strategy).prop_map(|(fieldSInt32)| {
    Gumbo_Structs_Arrays::MyStruct2_i { fieldSInt32 }
  })
}

pub fn Gumbo_Structs_Arrays_MyArrayInt32_strategy_default() -> impl Strategy<Value = Gumbo_Structs_Arrays::MyArrayInt32>
{
  Gumbo_Structs_Arrays_MyArrayInt32_strategy_cust(any::<i32>())
}

pub fn Gumbo_Structs_Arrays_MyArrayInt32_strategy_cust<i32_strategy: Strategy<Value = i32>> (base_strategy: i32_strategy) -> impl Strategy<Value = Gumbo_Structs_Arrays::MyArrayInt32>
{
  proptest::collection::vec(base_strategy, Gumbo_Structs_Arrays::Gumbo_Structs_Arrays_MyArrayInt32_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[i32; Gumbo_Structs_Arrays::Gumbo_Structs_Arrays_MyArrayInt32_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Gumbo_Structs_Arrays_MyArrayStruct_strategy_default() -> impl Strategy<Value = Gumbo_Structs_Arrays::MyArrayStruct>
{
  Gumbo_Structs_Arrays_MyArrayStruct_strategy_cust(Gumbo_Structs_Arrays_MyStruct2_i_strategy_default())
}

pub fn Gumbo_Structs_Arrays_MyArrayStruct_strategy_cust<Gumbo_Structs_Arrays_MyStruct2_i_strategy: Strategy<Value = Gumbo_Structs_Arrays::MyStruct2_i>> (base_strategy: Gumbo_Structs_Arrays_MyStruct2_i_strategy) -> impl Strategy<Value = Gumbo_Structs_Arrays::MyArrayStruct>
{
  proptest::collection::vec(base_strategy, Gumbo_Structs_Arrays::Gumbo_Structs_Arrays_MyArrayStruct_DIM_0)
    .prop_map(|v| {
      let boxed: Box<[Gumbo_Structs_Arrays::MyStruct2_i; Gumbo_Structs_Arrays::Gumbo_Structs_Arrays_MyArrayStruct_DIM_0]> = v.into_boxed_slice().try_into().unwrap();
      *boxed
  })
}

pub fn Gumbo_Structs_Arrays_MyStructArray_i_strategy_default() -> impl Strategy<Value = Gumbo_Structs_Arrays::MyStructArray_i>
{
  Gumbo_Structs_Arrays_MyStructArray_i_strategy_cust(
    any::<i64>(),
    Gumbo_Structs_Arrays_MyEnum_strategy_default(),
    Gumbo_Structs_Arrays_MyStruct2_i_strategy_default(),
    Gumbo_Structs_Arrays_MyArrayStruct_strategy_default()
  )
}

pub fn Gumbo_Structs_Arrays_MyStructArray_i_strategy_cust
  <fieldInt64_i64_strategy: Strategy<Value = i64>, 
   fieldEnum_Gumbo_Structs_Arrays_MyEnum_strategy: Strategy<Value = Gumbo_Structs_Arrays::MyEnum>, 
   fieldRec_Gumbo_Structs_Arrays_MyStruct2_i_strategy: Strategy<Value = Gumbo_Structs_Arrays::MyStruct2_i>, 
   fieldArray_Gumbo_Structs_Arrays_MyArrayStruct_strategy: Strategy<Value = Gumbo_Structs_Arrays::MyArrayStruct>> (
  fieldInt64_strategy: fieldInt64_i64_strategy,
  fieldEnum_strategy: fieldEnum_Gumbo_Structs_Arrays_MyEnum_strategy,
  fieldRec_strategy: fieldRec_Gumbo_Structs_Arrays_MyStruct2_i_strategy,
  fieldArray_strategy: fieldArray_Gumbo_Structs_Arrays_MyArrayStruct_strategy) -> impl Strategy<Value = Gumbo_Structs_Arrays::MyStructArray_i>
{
  (fieldInt64_strategy, fieldEnum_strategy, fieldRec_strategy, fieldArray_strategy).prop_map(|(fieldInt64, fieldEnum, fieldRec, fieldArray)| {
    Gumbo_Structs_Arrays::MyStructArray_i { fieldInt64, fieldEnum, fieldRec, fieldArray }
  })
}
