// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  pub const SW_EthernetMessages_BYTE_SIZE: usize = 204800;
  pub const SW_EthernetMessages_DIM_0: usize = 128;

  pub type EthernetMessages = [RawEthernetMessage; SW_EthernetMessages_DIM_0];
}

