#include "seL4_ArduPilot_ArduPilot.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void seL4_ArduPilot_ArduPilot_initialize(void);
void seL4_ArduPilot_ArduPilot_notify(microkit_channel channel);
void seL4_ArduPilot_ArduPilot_timeTriggered(void);

volatile sb_queue_base_SW_StructuredEthernetMessage_i_1_t *EthernetFramesTx_queue_1;
volatile sb_queue_base_SW_StructuredEthernetMessage_i_1_t *EthernetFramesRx_queue_1;
sb_queue_base_SW_StructuredEthernetMessage_i_1_Recv_t EthernetFramesRx_recv_queue;

#define PORT_FROM_MON 60

bool put_EthernetFramesTx(const base_SW_StructuredEthernetMessage_i *data) {
  sb_queue_base_SW_StructuredEthernetMessage_i_1_enqueue((sb_queue_base_SW_StructuredEthernetMessage_i_1_t *) EthernetFramesTx_queue_1, (base_SW_StructuredEthernetMessage_i *) data);

  return true;
}

bool EthernetFramesRx_is_empty(void) {
  return sb_queue_base_SW_StructuredEthernetMessage_i_1_is_empty(&EthernetFramesRx_recv_queue);
}

bool get_EthernetFramesRx_poll(sb_event_counter_t *numDropped, base_SW_StructuredEthernetMessage_i *data) {
  return sb_queue_base_SW_StructuredEthernetMessage_i_1_dequeue((sb_queue_base_SW_StructuredEthernetMessage_i_1_Recv_t *) &EthernetFramesRx_recv_queue, numDropped, data);
}

bool get_EthernetFramesRx(base_SW_StructuredEthernetMessage_i *data) {
  sb_event_counter_t numDropped;
  return get_EthernetFramesRx_poll (&numDropped, data);
}

void init(void) {
  sb_queue_base_SW_StructuredEthernetMessage_i_1_init((sb_queue_base_SW_StructuredEthernetMessage_i_1_t *) EthernetFramesTx_queue_1);

  sb_queue_base_SW_StructuredEthernetMessage_i_1_Recv_init(&EthernetFramesRx_recv_queue, (sb_queue_base_SW_StructuredEthernetMessage_i_1_t *) EthernetFramesRx_queue_1);

  seL4_ArduPilot_ArduPilot_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      seL4_ArduPilot_ArduPilot_timeTriggered();
      break;
    default:
      seL4_ArduPilot_ArduPilot_notify(channel);
  }
}
