// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Independence VCs for every MHIP transition pair: Non-Blocking and
//! Preservation (per direction whose firing member is a component) and
//! Commutativity (once per component-component pair).
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]

use vstd::prelude::*;

use crate::actions::*;
use crate::assertions::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[29]: Non-Blocking -- OI firing does not block TS (MHIP pair t0/t1) */
pub proof fn vc_non_blocking_oi_ts(pre: SystemState, post: SystemState)
  requires
    true /* pre_oi_1 has no assertion */,
    true /* pre_ts_2 has no assertion */,
    oi_global_write_frame(pre, post),
  ensures
    true /* pre_ts_2 has no assertion */,
{}

/** VC[30]: Non-Blocking -- TS firing does not block OI (MHIP pair t0/t1) */
pub proof fn vc_non_blocking_ts_oi(pre: SystemState, post: SystemState)
  requires
    true /* pre_oi_1 has no assertion */,
    true /* pre_ts_2 has no assertion */,
    ts_global_write_frame(pre, post),
  ensures
    true /* pre_oi_1 has no assertion */,
{}

/** VC[31]: Preservation -- OI firing preserves TS's post-assertions (MHIP pair t0/t1) */
pub proof fn vc_preservation_oi_ts(pre: SystemState, post: SystemState)
  requires
    true /* pre_oi_1 has no assertion */,
    true /* post_ts_3 has no assertion */,
    oi_global_write_frame(pre, post),
  ensures
    true /* post_ts_3 has no assertion */,
{}

/** VC[32]: Preservation -- TS firing preserves OI's post-assertions (MHIP pair t0/t1) */
pub proof fn vc_preservation_ts_oi(pre: SystemState, post: SystemState)
  requires
    true /* pre_ts_2 has no assertion */,
    sys_assert_END_OI_Assert(pre),
    ts_global_write_frame(pre, post),
  ensures
    sys_assert_END_OI_Assert(post),
{}

/** VC[33]: Commutativity (execIndependent) -- firing OI then TS
  * yields the same state as TS then OI (MHIP pair t0/t1).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_oi_ts(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    true /* pre_oi_1 has no assertion */,
    true /* pre_ts_2 has no assertion */,
    oi_fire(st, mid_a),
    ts_fire(mid_a, post_a),
    ts_fire(st, mid_b),
    oi_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[34]: Non-Blocking -- DRF firing does not block DMF (MHIP pair t4/t8) */
pub proof fn vc_non_blocking_drf_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_START_Monitor_Assert(post),
{}

/** VC[35]: Non-Blocking -- DMF firing does not block DRF (MHIP pair t4/t8) */
pub proof fn vc_non_blocking_dmf_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_START_Regulator_Assert(post),
{}

/** VC[36]: Preservation -- DRF firing preserves DMF's post-assertions (MHIP pair t4/t8) */
pub proof fn vc_preservation_drf_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[37]: Preservation -- DMF firing preserves DRF's post-assertions (MHIP pair t4/t8) */
pub proof fn vc_preservation_dmf_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Monitor_Assert(pre),
    sys_assert_Post_DRF_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[38]: Commutativity (execIndependent) -- firing DRF then DMF
  * yields the same state as DMF then DRF (MHIP pair t4/t8).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_drf_dmf(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_START_Regulator_Assert(st),
    sys_assert_START_Monitor_Assert(st),
    drf_fire(st, mid_a),
    dmf_fire(mid_a, post_a),
    dmf_fire(st, mid_b),
    drf_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[39]: Non-Blocking -- MRI firing does not block DMF (MHIP pair t5/t8) */
pub proof fn vc_non_blocking_mri_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_START_Monitor_Assert(post),
{}

/** VC[40]: Non-Blocking -- DMF firing does not block MRI (MHIP pair t5/t8) */
pub proof fn vc_non_blocking_dmf_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[41]: Preservation -- MRI firing preserves DMF's post-assertions (MHIP pair t5/t8) */
pub proof fn vc_preservation_mri_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[42]: Preservation -- DMF firing preserves MRI's post-assertions (MHIP pair t5/t8) */
pub proof fn vc_preservation_dmf_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Monitor_Assert(pre),
    sys_assert_Post_MRI_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[43]: Commutativity (execIndependent) -- firing MRI then DMF
  * yields the same state as DMF then MRI (MHIP pair t5/t8).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mri_dmf(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_DRF_Assert(st),
    sys_assert_START_Monitor_Assert(st),
    mri_fire(st, mid_a),
    dmf_fire(mid_a, post_a),
    dmf_fire(st, mid_b),
    mri_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[44]: Non-Blocking -- DRF firing does not block MMI (MHIP pair t4/t9) */
pub proof fn vc_non_blocking_drf_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[45]: Non-Blocking -- MMI firing does not block DRF (MHIP pair t4/t9) */
pub proof fn vc_non_blocking_mmi_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_START_Regulator_Assert(post),
{}

/** VC[46]: Preservation -- DRF firing preserves MMI's post-assertions (MHIP pair t4/t9) */
pub proof fn vc_preservation_drf_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[47]: Preservation -- MMI firing preserves DRF's post-assertions (MHIP pair t4/t9) */
pub proof fn vc_preservation_mmi_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DMF_Assert(pre),
    sys_assert_Post_DRF_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[48]: Commutativity (execIndependent) -- firing DRF then MMI
  * yields the same state as MMI then DRF (MHIP pair t4/t9).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_drf_mmi(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_START_Regulator_Assert(st),
    sys_assert_Post_DMF_Assert(st),
    drf_fire(st, mid_a),
    mmi_fire(mid_a, post_a),
    mmi_fire(st, mid_b),
    drf_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[49]: Non-Blocking -- MRM firing does not block DMF (MHIP pair t6/t8) */
pub proof fn vc_non_blocking_mrm_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_START_Monitor_Assert(post),
{}

/** VC[50]: Non-Blocking -- DMF firing does not block MRM (MHIP pair t6/t8) */
pub proof fn vc_non_blocking_dmf_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[51]: Preservation -- MRM firing preserves DMF's post-assertions (MHIP pair t6/t8) */
pub proof fn vc_preservation_mrm_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[52]: Preservation -- DMF firing preserves MRM's post-assertions (MHIP pair t6/t8) */
pub proof fn vc_preservation_dmf_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Monitor_Assert(pre),
    sys_assert_Post_MRM_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[53]: Commutativity (execIndependent) -- firing MRM then DMF
  * yields the same state as DMF then MRM (MHIP pair t6/t8).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mrm_dmf(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRI_Assert(st),
    sys_assert_START_Monitor_Assert(st),
    mrm_fire(st, mid_a),
    dmf_fire(mid_a, post_a),
    dmf_fire(st, mid_b),
    mrm_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[54]: Non-Blocking -- MRI firing does not block MMI (MHIP pair t5/t9) */
pub proof fn vc_non_blocking_mri_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[55]: Non-Blocking -- MMI firing does not block MRI (MHIP pair t5/t9) */
pub proof fn vc_non_blocking_mmi_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[56]: Preservation -- MRI firing preserves MMI's post-assertions (MHIP pair t5/t9) */
pub proof fn vc_preservation_mri_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[57]: Preservation -- MMI firing preserves MRI's post-assertions (MHIP pair t5/t9) */
pub proof fn vc_preservation_mmi_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DMF_Assert(pre),
    sys_assert_Post_MRI_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[58]: Commutativity (execIndependent) -- firing MRI then MMI
  * yields the same state as MMI then MRI (MHIP pair t5/t9).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mri_mmi(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_DRF_Assert(st),
    sys_assert_Post_DMF_Assert(st),
    mri_fire(st, mid_a),
    mmi_fire(mid_a, post_a),
    mmi_fire(st, mid_b),
    mri_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[59]: Non-Blocking -- DRF firing does not block MMM (MHIP pair t4/t10) */
pub proof fn vc_non_blocking_drf_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[60]: Non-Blocking -- MMM firing does not block DRF (MHIP pair t4/t10) */
pub proof fn vc_non_blocking_mmm_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_START_Regulator_Assert(post),
{}

/** VC[61]: Preservation -- DRF firing preserves MMM's post-assertions (MHIP pair t4/t10) */
pub proof fn vc_preservation_drf_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[62]: Preservation -- MMM firing preserves DRF's post-assertions (MHIP pair t4/t10) */
pub proof fn vc_preservation_mmm_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMI_Assert(pre),
    sys_assert_Post_DRF_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[63]: Commutativity (execIndependent) -- firing DRF then MMM
  * yields the same state as MMM then DRF (MHIP pair t4/t10).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_drf_mmm(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_START_Regulator_Assert(st),
    sys_assert_Post_MMI_Assert(st),
    drf_fire(st, mid_a),
    mmm_fire(mid_a, post_a),
    mmm_fire(st, mid_b),
    drf_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[64]: Non-Blocking -- MHS firing does not block DMF (MHIP pair t7/t8) */
pub proof fn vc_non_blocking_mhs_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_START_Monitor_Assert(post),
{}

/** VC[65]: Non-Blocking -- DMF firing does not block MHS (MHIP pair t7/t8) */
pub proof fn vc_non_blocking_dmf_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_START_Monitor_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[66]: Preservation -- MHS firing preserves DMF's post-assertions (MHIP pair t7/t8) */
pub proof fn vc_preservation_mhs_dmf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[67]: Preservation -- DMF firing preserves MHS's post-assertions (MHIP pair t7/t8) */
pub proof fn vc_preservation_dmf_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Monitor_Assert(pre),
    sys_assert_END_Regulator_Assert(pre),
    dmf_global_write_frame(pre, post),
  ensures
    sys_assert_END_Regulator_Assert(post),
{}

/** VC[68]: Commutativity (execIndependent) -- firing MHS then DMF
  * yields the same state as DMF then MHS (MHIP pair t7/t8).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mhs_dmf(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRM_Assert(st),
    sys_assert_START_Monitor_Assert(st),
    mhs_fire(st, mid_a),
    dmf_fire(mid_a, post_a),
    dmf_fire(st, mid_b),
    mhs_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[69]: Non-Blocking -- MRM firing does not block MMI (MHIP pair t6/t9) */
pub proof fn vc_non_blocking_mrm_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[70]: Non-Blocking -- MMI firing does not block MRM (MHIP pair t6/t9) */
pub proof fn vc_non_blocking_mmi_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[71]: Preservation -- MRM firing preserves MMI's post-assertions (MHIP pair t6/t9) */
pub proof fn vc_preservation_mrm_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[72]: Preservation -- MMI firing preserves MRM's post-assertions (MHIP pair t6/t9) */
pub proof fn vc_preservation_mmi_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DMF_Assert(pre),
    sys_assert_Post_MRM_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[73]: Commutativity (execIndependent) -- firing MRM then MMI
  * yields the same state as MMI then MRM (MHIP pair t6/t9).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mrm_mmi(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRI_Assert(st),
    sys_assert_Post_DMF_Assert(st),
    mrm_fire(st, mid_a),
    mmi_fire(mid_a, post_a),
    mmi_fire(st, mid_b),
    mrm_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[74]: Non-Blocking -- MRI firing does not block MMM (MHIP pair t5/t10) */
pub proof fn vc_non_blocking_mri_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[75]: Non-Blocking -- MMM firing does not block MRI (MHIP pair t5/t10) */
pub proof fn vc_non_blocking_mmm_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[76]: Preservation -- MRI firing preserves MMM's post-assertions (MHIP pair t5/t10) */
pub proof fn vc_preservation_mri_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[77]: Preservation -- MMM firing preserves MRI's post-assertions (MHIP pair t5/t10) */
pub proof fn vc_preservation_mmm_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMI_Assert(pre),
    sys_assert_Post_MRI_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[78]: Commutativity (execIndependent) -- firing MRI then MMM
  * yields the same state as MMM then MRI (MHIP pair t5/t10).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mri_mmm(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_DRF_Assert(st),
    sys_assert_Post_MMI_Assert(st),
    mri_fire(st, mid_a),
    mmm_fire(mid_a, post_a),
    mmm_fire(st, mid_b),
    mri_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[79]: Non-Blocking -- DRF firing does not block MA (MHIP pair t4/t11) */
pub proof fn vc_non_blocking_drf_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[80]: Non-Blocking -- MA firing does not block DRF (MHIP pair t4/t11) */
pub proof fn vc_non_blocking_ma_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_START_Regulator_Assert(post),
{}

/** VC[81]: Preservation -- DRF firing preserves MA's post-assertions (MHIP pair t4/t11) */
pub proof fn vc_preservation_drf_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_START_Regulator_Assert(pre),
    sys_assert_END_Monitor_Assert(pre),
    drf_global_write_frame(pre, post),
  ensures
    sys_assert_END_Monitor_Assert(post),
{}

/** VC[82]: Preservation -- MA firing preserves DRF's post-assertions (MHIP pair t4/t11) */
pub proof fn vc_preservation_ma_drf(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMM_Assert(pre),
    sys_assert_Post_DRF_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[83]: Commutativity (execIndependent) -- firing DRF then MA
  * yields the same state as MA then DRF (MHIP pair t4/t11).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_drf_ma(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_START_Regulator_Assert(st),
    sys_assert_Post_MMM_Assert(st),
    drf_fire(st, mid_a),
    ma_fire(mid_a, post_a),
    ma_fire(st, mid_b),
    drf_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[84]: Non-Blocking -- MHS firing does not block MMI (MHIP pair t7/t9) */
pub proof fn vc_non_blocking_mhs_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DMF_Assert(post),
{}

/** VC[85]: Non-Blocking -- MMI firing does not block MHS (MHIP pair t7/t9) */
pub proof fn vc_non_blocking_mmi_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_DMF_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[86]: Preservation -- MHS firing preserves MMI's post-assertions (MHIP pair t7/t9) */
pub proof fn vc_preservation_mhs_mmi(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[87]: Preservation -- MMI firing preserves MHS's post-assertions (MHIP pair t7/t9) */
pub proof fn vc_preservation_mmi_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DMF_Assert(pre),
    sys_assert_END_Regulator_Assert(pre),
    mmi_global_write_frame(pre, post),
  ensures
    sys_assert_END_Regulator_Assert(post),
{}

/** VC[88]: Commutativity (execIndependent) -- firing MHS then MMI
  * yields the same state as MMI then MHS (MHIP pair t7/t9).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mhs_mmi(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRM_Assert(st),
    sys_assert_Post_DMF_Assert(st),
    mhs_fire(st, mid_a),
    mmi_fire(mid_a, post_a),
    mmi_fire(st, mid_b),
    mhs_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[89]: Non-Blocking -- MRM firing does not block MMM (MHIP pair t6/t10) */
pub proof fn vc_non_blocking_mrm_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[90]: Non-Blocking -- MMM firing does not block MRM (MHIP pair t6/t10) */
pub proof fn vc_non_blocking_mmm_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[91]: Preservation -- MRM firing preserves MMM's post-assertions (MHIP pair t6/t10) */
pub proof fn vc_preservation_mrm_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[92]: Preservation -- MMM firing preserves MRM's post-assertions (MHIP pair t6/t10) */
pub proof fn vc_preservation_mmm_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMI_Assert(pre),
    sys_assert_Post_MRM_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[93]: Commutativity (execIndependent) -- firing MRM then MMM
  * yields the same state as MMM then MRM (MHIP pair t6/t10).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mrm_mmm(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRI_Assert(st),
    sys_assert_Post_MMI_Assert(st),
    mrm_fire(st, mid_a),
    mmm_fire(mid_a, post_a),
    mmm_fire(st, mid_b),
    mrm_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[94]: Non-Blocking -- MRI firing does not block MA (MHIP pair t5/t11) */
pub proof fn vc_non_blocking_mri_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[95]: Non-Blocking -- MA firing does not block MRI (MHIP pair t5/t11) */
pub proof fn vc_non_blocking_ma_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_Post_DRF_Assert(post),
{}

/** VC[96]: Preservation -- MRI firing preserves MA's post-assertions (MHIP pair t5/t11) */
pub proof fn vc_preservation_mri_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_DRF_Assert(pre),
    sys_assert_END_Monitor_Assert(pre),
    mri_global_write_frame(pre, post),
  ensures
    sys_assert_END_Monitor_Assert(post),
{}

/** VC[97]: Preservation -- MA firing preserves MRI's post-assertions (MHIP pair t5/t11) */
pub proof fn vc_preservation_ma_mri(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMM_Assert(pre),
    sys_assert_Post_MRI_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[98]: Commutativity (execIndependent) -- firing MRI then MA
  * yields the same state as MA then MRI (MHIP pair t5/t11).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mri_ma(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_DRF_Assert(st),
    sys_assert_Post_MMM_Assert(st),
    mri_fire(st, mid_a),
    ma_fire(mid_a, post_a),
    ma_fire(st, mid_b),
    mri_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[99]: Non-Blocking -- MHS firing does not block MMM (MHIP pair t7/t10) */
pub proof fn vc_non_blocking_mhs_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMI_Assert(post),
{}

/** VC[100]: Non-Blocking -- MMM firing does not block MHS (MHIP pair t7/t10) */
pub proof fn vc_non_blocking_mmm_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_MMI_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[101]: Preservation -- MHS firing preserves MMM's post-assertions (MHIP pair t7/t10) */
pub proof fn vc_preservation_mhs_mmm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[102]: Preservation -- MMM firing preserves MHS's post-assertions (MHIP pair t7/t10) */
pub proof fn vc_preservation_mmm_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMI_Assert(pre),
    sys_assert_END_Regulator_Assert(pre),
    mmm_global_write_frame(pre, post),
  ensures
    sys_assert_END_Regulator_Assert(post),
{}

/** VC[103]: Commutativity (execIndependent) -- firing MHS then MMM
  * yields the same state as MMM then MHS (MHIP pair t7/t10).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mhs_mmm(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRM_Assert(st),
    sys_assert_Post_MMI_Assert(st),
    mhs_fire(st, mid_a),
    mmm_fire(mid_a, post_a),
    mmm_fire(st, mid_b),
    mhs_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[104]: Non-Blocking -- MRM firing does not block MA (MHIP pair t6/t11) */
pub proof fn vc_non_blocking_mrm_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[105]: Non-Blocking -- MA firing does not block MRM (MHIP pair t6/t11) */
pub proof fn vc_non_blocking_ma_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRI_Assert(post),
{}

/** VC[106]: Preservation -- MRM firing preserves MA's post-assertions (MHIP pair t6/t11) */
pub proof fn vc_preservation_mrm_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRI_Assert(pre),
    sys_assert_END_Monitor_Assert(pre),
    mrm_global_write_frame(pre, post),
  ensures
    sys_assert_END_Monitor_Assert(post),
{}

/** VC[107]: Preservation -- MA firing preserves MRM's post-assertions (MHIP pair t6/t11) */
pub proof fn vc_preservation_ma_mrm(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMM_Assert(pre),
    sys_assert_Post_MRM_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[108]: Commutativity (execIndependent) -- firing MRM then MA
  * yields the same state as MA then MRM (MHIP pair t6/t11).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mrm_ma(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRI_Assert(st),
    sys_assert_Post_MMM_Assert(st),
    mrm_fire(st, mid_a),
    ma_fire(mid_a, post_a),
    ma_fire(st, mid_b),
    mrm_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[109]: Non-Blocking -- MHS firing does not block MA (MHIP pair t7/t11) */
pub proof fn vc_non_blocking_mhs_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MMM_Assert(post),
{}

/** VC[110]: Non-Blocking -- MA firing does not block MHS (MHIP pair t7/t11) */
pub proof fn vc_non_blocking_ma_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_Post_MMM_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_Post_MRM_Assert(post),
{}

/** VC[111]: Preservation -- MHS firing preserves MA's post-assertions (MHIP pair t7/t11) */
pub proof fn vc_preservation_mhs_ma(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MRM_Assert(pre),
    sys_assert_END_Monitor_Assert(pre),
    mhs_global_write_frame(pre, post),
  ensures
    sys_assert_END_Monitor_Assert(post),
{}

/** VC[112]: Preservation -- MA firing preserves MHS's post-assertions (MHIP pair t7/t11) */
pub proof fn vc_preservation_ma_mhs(pre: SystemState, post: SystemState)
  requires
    sys_assert_Post_MMM_Assert(pre),
    sys_assert_END_Regulator_Assert(pre),
    ma_global_write_frame(pre, post),
  ensures
    sys_assert_END_Regulator_Assert(post),
{}

/** VC[113]: Commutativity (execIndependent) -- firing MHS then MA
  * yields the same state as MA then MHS (MHIP pair t7/t11).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_mhs_ma(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    sys_assert_Post_MRM_Assert(st),
    sys_assert_Post_MMM_Assert(st),
    mhs_fire(st, mid_a),
    ma_fire(mid_a, post_a),
    ma_fire(st, mid_b),
    mhs_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

} // verus!
