// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait monitor_monitor_Api {}

  pub trait monitor_monitor_Put_Api: monitor_monitor_Api {
    #[verifier::external_body]
    fn unverified_put_healthy(
      &mut self,
      value: bool)
    {
      extern_api::unsafe_put_healthy(&value);
    }

    #[verifier::external_body]
    fn unverified_put_echo(
      &mut self,
      value: i32)
    {
      extern_api::unsafe_put_echo(&value);
    }

    #[verifier::external_body]
    fn unverified_put_alert_result(
      &mut self,
      value: bool)
    {
      extern_api::unsafe_put_alert_result(&value);
    }

    #[verifier::external_body]
    fn unverified_put_ack(&mut self)
    {
      extern_api::unsafe_put_ack();
    }
  }

  pub trait monitor_monitor_Get_Api: monitor_monitor_Api {
    #[verifier::external_body]
    fn unverified_get_level(
      &mut self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_level();
    }

    #[verifier::external_body]
    fn unverified_get_boolean_value(
      &mut self,
      value: &Ghost<bool>) -> (res : bool)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_boolean_value();
    }

    #[verifier::external_body]
    fn unverified_get_character_value(
      &mut self,
      value: &Ghost<u8>) -> (res : u8)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_character_value();
    }

    #[verifier::external_body]
    fn unverified_get_signed_8_value(
      &mut self,
      value: &Ghost<i8>) -> (res : i8)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_signed_8_value();
    }

    #[verifier::external_body]
    fn unverified_get_signed_16_value(
      &mut self,
      value: &Ghost<i16>) -> (res : i16)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_signed_16_value();
    }

    #[verifier::external_body]
    fn unverified_get_unsigned_8_value(
      &mut self,
      value: &Ghost<u8>) -> (res : u8)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_unsigned_8_value();
    }

    #[verifier::external_body]
    fn unverified_get_unsigned_16_value(
      &mut self,
      value: &Ghost<u16>) -> (res : u16)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_unsigned_16_value();
    }

    #[verifier::external_body]
    fn unverified_get_sample(
      &mut self,
      value: &Ghost<Option<i32>>) -> (res : Option<i32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_sample();
    }

    #[verifier::external_body]
    fn unverified_get_flag(
      &mut self,
      value: &Ghost<Option<bool>>) -> (res : Option<bool>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_flag();
    }

    #[verifier::external_body]
    fn unverified_get_operating_state(
      &mut self,
      value: &Ghost<Option<Exhaustive_Monitor::OperatingState>>) -> (res : Option<Exhaustive_Monitor::OperatingState>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_operating_state();
    }

    #[verifier::external_body]
    fn unverified_get_samples(
      &mut self,
      value: &Ghost<Option<Exhaustive_Monitor::Samples>>) -> (res : Option<Exhaustive_Monitor::Samples>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_samples();
    }

    #[verifier::external_body]
    fn unverified_get_telemetry(
      &mut self,
      value: &Ghost<Option<Exhaustive_Monitor::Telemetry_i>>) -> (res : Option<Exhaustive_Monitor::Telemetry_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_telemetry();
    }

    #[verifier::external_body]
    fn unverified_get_pulse(
      &mut self,
      value: &Ghost<Option<u8>>) -> (res : bool)
      ensures
        res == value@.is_some(),
    {
      return extern_api::unsafe_get_pulse();
    }

    #[verifier::external_body]
    fn unverified_peek_level(
      &self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_level();
    }

    #[verifier::external_body]
    fn unverified_peek_boolean_value(
      &self,
      value: &Ghost<bool>) -> (res : bool)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_boolean_value();
    }

    #[verifier::external_body]
    fn unverified_peek_character_value(
      &self,
      value: &Ghost<u8>) -> (res : u8)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_character_value();
    }

    #[verifier::external_body]
    fn unverified_peek_signed_8_value(
      &self,
      value: &Ghost<i8>) -> (res : i8)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_signed_8_value();
    }

    #[verifier::external_body]
    fn unverified_peek_signed_16_value(
      &self,
      value: &Ghost<i16>) -> (res : i16)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_signed_16_value();
    }

    #[verifier::external_body]
    fn unverified_peek_unsigned_8_value(
      &self,
      value: &Ghost<u8>) -> (res : u8)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_unsigned_8_value();
    }

    #[verifier::external_body]
    fn unverified_peek_unsigned_16_value(
      &self,
      value: &Ghost<u16>) -> (res : u16)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_unsigned_16_value();
    }

    #[verifier::external_body]
    fn unverified_peek_healthy(
      &self,
      value: &Ghost<bool>) -> (res : bool)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_healthy();
    }

    #[verifier::external_body]
    fn unverified_peek_sample(
      &self,
      value: &Ghost<Option<i32>>) -> (res : Option<i32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_sample();
    }

    #[verifier::external_body]
    fn unverified_peek_flag(
      &self,
      value: &Ghost<Option<bool>>) -> (res : Option<bool>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_flag();
    }

    #[verifier::external_body]
    fn unverified_peek_operating_state(
      &self,
      value: &Ghost<Option<Exhaustive_Monitor::OperatingState>>) -> (res : Option<Exhaustive_Monitor::OperatingState>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_operating_state();
    }

    #[verifier::external_body]
    fn unverified_peek_samples(
      &self,
      value: &Ghost<Option<Exhaustive_Monitor::Samples>>) -> (res : Option<Exhaustive_Monitor::Samples>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_samples();
    }

    #[verifier::external_body]
    fn unverified_peek_telemetry(
      &self,
      value: &Ghost<Option<Exhaustive_Monitor::Telemetry_i>>) -> (res : Option<Exhaustive_Monitor::Telemetry_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_telemetry();
    }

    #[verifier::external_body]
    fn unverified_peek_echo(
      &self,
      value: &Ghost<Option<i32>>) -> (res : Option<i32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_echo();
    }

    #[verifier::external_body]
    fn unverified_peek_alert_result(
      &self,
      value: &Ghost<Option<bool>>) -> (res : Option<bool>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_alert_result();
    }

    #[verifier::external_body]
    fn unverified_peek_pulse(
      &self,
      value: &Ghost<Option<u8>>) -> (res : bool)
      ensures
        res == value@.is_some(),
    {
      return extern_api::unsafe_peek_pulse();
    }

    #[verifier::external_body]
    fn unverified_peek_ack(
      &self,
      value: &Ghost<Option<u8>>) -> (res : bool)
      ensures
        res == value@.is_some(),
    {
      return extern_api::unsafe_peek_ack();
    }
  }

  pub trait monitor_monitor_Full_Api: monitor_monitor_Put_Api + monitor_monitor_Get_Api {}

  pub struct monitor_monitor_Application_Api<API: monitor_monitor_Api> {
    pub api: API,

    pub ghost level: i32,
    pub ghost boolean_value: bool,
    pub ghost character_value: u8,
    pub ghost signed_8_value: i8,
    pub ghost signed_16_value: i16,
    pub ghost unsigned_8_value: u8,
    pub ghost unsigned_16_value: u16,
    pub ghost sample: Option<i32>,
    pub ghost flag: Option<bool>,
    pub ghost operating_state: Option<Exhaustive_Monitor::OperatingState>,
    pub ghost samples: Option<Exhaustive_Monitor::Samples>,
    pub ghost telemetry: Option<Exhaustive_Monitor::Telemetry_i>,
    pub ghost pulse: Option<u8>,
    pub ghost healthy: bool,
    pub ghost echo: Option<i32>,
    pub ghost alert_result: Option<bool>,
    pub ghost ack: Option<u8>,
  }

  impl<API: monitor_monitor_Put_Api> monitor_monitor_Application_Api<API> {
    pub fn put_healthy(
      &mut self,
      value: bool)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        self.healthy == value,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_put_healthy(value);
      self.healthy = value;
    }
    pub fn put_echo(
      &mut self,
      value: i32)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        self.echo == Some(value),
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_put_echo(value);
      self.echo = Some(value);
    }
    pub fn put_alert_result(
      &mut self,
      value: bool)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        self.alert_result == Some(value),
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_put_alert_result(value);
      self.alert_result = Some(value);
    }
    pub fn put_ack(&mut self)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        self.ack == Some(0u8),
    {
      self.api.unverified_put_ack();
      self.ack = Some(0u8);
    }
  }

  impl<API: monitor_monitor_Get_Api> monitor_monitor_Application_Api<API> {
    pub fn get_level(&mut self) -> (res : i32)
      ensures
        old(self).level == self.level,
        res == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_level(&Ghost(self.level))
    }
    pub fn get_boolean_value(&mut self) -> (res : bool)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        res == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_boolean_value(&Ghost(self.boolean_value))
    }
    pub fn get_character_value(&mut self) -> (res : u8)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        res == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_character_value(&Ghost(self.character_value))
    }
    pub fn get_signed_8_value(&mut self) -> (res : i8)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        res == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_signed_8_value(&Ghost(self.signed_8_value))
    }
    pub fn get_signed_16_value(&mut self) -> (res : i16)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        res == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_signed_16_value(&Ghost(self.signed_16_value))
    }
    pub fn get_unsigned_8_value(&mut self) -> (res : u8)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        res == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_unsigned_8_value(&Ghost(self.unsigned_8_value))
    }
    pub fn get_unsigned_16_value(&mut self) -> (res : u16)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        res == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_unsigned_16_value(&Ghost(self.unsigned_16_value))
    }
    pub fn get_sample(&mut self) -> (res : Option<i32>)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        res == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_sample(&Ghost(self.sample))
    }
    pub fn get_flag(&mut self) -> (res : Option<bool>)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        res == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_flag(&Ghost(self.flag))
    }
    pub fn get_operating_state(&mut self) -> (res : Option<Exhaustive_Monitor::OperatingState>)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        res == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_operating_state(&Ghost(self.operating_state))
    }
    pub fn get_samples(&mut self) -> (res : Option<Exhaustive_Monitor::Samples>)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        res == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_samples(&Ghost(self.samples))
    }
    pub fn get_telemetry(&mut self) -> (res : Option<Exhaustive_Monitor::Telemetry_i>)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        res == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        old(self).ack == self.ack,
    {
      self.api.unverified_get_telemetry(&Ghost(self.telemetry))
    }
    pub fn get_pulse(&mut self) -> (res : bool)
      ensures
        old(self).level == self.level,
        old(self).boolean_value == self.boolean_value,
        old(self).character_value == self.character_value,
        old(self).signed_8_value == self.signed_8_value,
        old(self).signed_16_value == self.signed_16_value,
        old(self).unsigned_8_value == self.unsigned_8_value,
        old(self).unsigned_16_value == self.unsigned_16_value,
        old(self).healthy == self.healthy,
        old(self).sample == self.sample,
        old(self).flag == self.flag,
        old(self).operating_state == self.operating_state,
        old(self).samples == self.samples,
        old(self).telemetry == self.telemetry,
        old(self).echo == self.echo,
        old(self).alert_result == self.alert_result,
        old(self).pulse == self.pulse,
        res == self.pulse.is_some(),
        old(self).ack == self.ack,
    {
      self.api.unverified_get_pulse(&Ghost(self.pulse))
    }
    pub fn peek_level(&self) -> (res : i32)
      ensures
        res == self.level,
    {
      self.api.unverified_peek_level(&Ghost(self.level))
    }
    pub fn peek_boolean_value(&self) -> (res : bool)
      ensures
        res == self.boolean_value,
    {
      self.api.unverified_peek_boolean_value(&Ghost(self.boolean_value))
    }
    pub fn peek_character_value(&self) -> (res : u8)
      ensures
        res == self.character_value,
    {
      self.api.unverified_peek_character_value(&Ghost(self.character_value))
    }
    pub fn peek_signed_8_value(&self) -> (res : i8)
      ensures
        res == self.signed_8_value,
    {
      self.api.unverified_peek_signed_8_value(&Ghost(self.signed_8_value))
    }
    pub fn peek_signed_16_value(&self) -> (res : i16)
      ensures
        res == self.signed_16_value,
    {
      self.api.unverified_peek_signed_16_value(&Ghost(self.signed_16_value))
    }
    pub fn peek_unsigned_8_value(&self) -> (res : u8)
      ensures
        res == self.unsigned_8_value,
    {
      self.api.unverified_peek_unsigned_8_value(&Ghost(self.unsigned_8_value))
    }
    pub fn peek_unsigned_16_value(&self) -> (res : u16)
      ensures
        res == self.unsigned_16_value,
    {
      self.api.unverified_peek_unsigned_16_value(&Ghost(self.unsigned_16_value))
    }
    pub fn peek_healthy(&self) -> (res : bool)
      ensures
        res == self.healthy,
    {
      self.api.unverified_peek_healthy(&Ghost(self.healthy))
    }
    pub fn peek_sample(&self) -> (res : Option<i32>)
      ensures
        res == self.sample,
    {
      self.api.unverified_peek_sample(&Ghost(self.sample))
    }
    pub fn peek_flag(&self) -> (res : Option<bool>)
      ensures
        res == self.flag,
    {
      self.api.unverified_peek_flag(&Ghost(self.flag))
    }
    pub fn peek_operating_state(&self) -> (res : Option<Exhaustive_Monitor::OperatingState>)
      ensures
        res == self.operating_state,
    {
      self.api.unverified_peek_operating_state(&Ghost(self.operating_state))
    }
    pub fn peek_samples(&self) -> (res : Option<Exhaustive_Monitor::Samples>)
      ensures
        res == self.samples,
    {
      self.api.unverified_peek_samples(&Ghost(self.samples))
    }
    pub fn peek_telemetry(&self) -> (res : Option<Exhaustive_Monitor::Telemetry_i>)
      ensures
        res == self.telemetry,
    {
      self.api.unverified_peek_telemetry(&Ghost(self.telemetry))
    }
    pub fn peek_echo(&self) -> (res : Option<i32>)
      ensures
        res == self.echo,
    {
      self.api.unverified_peek_echo(&Ghost(self.echo))
    }
    pub fn peek_alert_result(&self) -> (res : Option<bool>)
      ensures
        res == self.alert_result,
    {
      self.api.unverified_peek_alert_result(&Ghost(self.alert_result))
    }
    pub fn peek_pulse(&self) -> (res : bool)
      ensures
        res == self.pulse.is_some(),
    {
      self.api.unverified_peek_pulse(&Ghost(self.pulse))
    }
    pub fn peek_ack(&self) -> (res : bool)
      ensures
        res == self.ack.is_some(),
    {
      self.api.unverified_peek_ack(&Ghost(self.ack))
    }
  }

  pub struct monitor_monitor_Initialization_Api;
  impl monitor_monitor_Api for monitor_monitor_Initialization_Api {}
  impl monitor_monitor_Put_Api for monitor_monitor_Initialization_Api {}

  pub const fn init_api() -> monitor_monitor_Application_Api<monitor_monitor_Initialization_Api> {
    return monitor_monitor_Application_Api {
      api: monitor_monitor_Initialization_Api {},

      level: 0,
      boolean_value: false,
      character_value: 0,
      signed_8_value: 0,
      signed_16_value: 0,
      unsigned_8_value: 0,
      unsigned_16_value: 0,
      sample: None,
      flag: None,
      operating_state: None,
      samples: None,
      telemetry: None,
      pulse: None,
      healthy: false,
      echo: None,
      alert_result: None,
      ack: None
    }
  }

  pub struct monitor_monitor_Compute_Api;
  impl monitor_monitor_Api for monitor_monitor_Compute_Api {}
  impl monitor_monitor_Put_Api for monitor_monitor_Compute_Api {}
  impl monitor_monitor_Get_Api for monitor_monitor_Compute_Api {}
  impl monitor_monitor_Full_Api for monitor_monitor_Compute_Api {}

  pub const fn compute_api() -> monitor_monitor_Application_Api<monitor_monitor_Compute_Api> {
    return monitor_monitor_Application_Api {
      api: monitor_monitor_Compute_Api {},

      level: 0,
      boolean_value: false,
      character_value: 0,
      signed_8_value: 0,
      signed_16_value: 0,
      unsigned_8_value: 0,
      unsigned_16_value: 0,
      sample: None,
      flag: None,
      operating_state: None,
      samples: None,
      telemetry: None,
      pulse: None,
      healthy: false,
      echo: None,
      alert_result: None,
      ack: None
    }
  }

}