// #Sireum

package sysml.Gubmo_Structs_Arrays

import org.sireum._
import art._
import sysml._
import sysml.Gubmo_Structs_Arrays.MyArrayInt32.FB4CC3
import org.sireum.S32._
import sysml.Gubmo_Structs_Arrays.MyArrayStruct.I30F6A8

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object ConsumerThr_i_Api {
  // assume integrationArrayInt32_DataPort
  @strictpure def integrationArrayInt32_DataPort(c_myArrayInt32_DataPort: Gubmo_Structs_Arrays.MyArrayInt32): B =
    c_myArrayInt32_DataPort.value.size == 10 &&
      c_myArrayInt32_DataPort.value(FB4CC3(0)) == s32"1" &
      GumboLib.GUMBO__Library.normalLibraryFunction(c_myArrayInt32_DataPort)

  // assume integrationArrayInt32_EventDataPort
  @strictpure def integrationArrayInt32_EventDataPort(c_myArrayInt32_EventDataPort: Gubmo_Structs_Arrays.MyArrayInt32): B =
    ∀(0 to c_myArrayInt32_EventDataPort.value.size - 2)(i => c_myArrayInt32_EventDataPort.value(FB4CC3(i)) <= c_myArrayInt32_EventDataPort.value(FB4CC3(i + 1)))

  // assume integrationStructArray_EventDataPort
  @strictpure def integrationStructArray_EventDataPort(c_myStructArray_EventDataPort: Gubmo_Structs_Arrays.MyStructArray_i): B =
    ∀(0 to c_myStructArray_EventDataPort.fieldArray.value.size - 2)(i => c_myStructArray_EventDataPort.fieldArray.value(I30F6A8(i)).fieldSInt32 <= c_myStructArray_EventDataPort.fieldArray.value(I30F6A8(i + 1)).fieldSInt32)
}

import ConsumerThr_i_Api._

@sig trait ConsumerThr_i_Api {
  def id: Art.BridgeId
  def c_myArrayInt32_DataPort_Id : Art.PortId
  def c_myArrayStruct_DataPort_Id : Art.PortId
  def c_myStructArray_DataPort_Id : Art.PortId
  def c_myArrayInt32_EventDataPort_Id : Art.PortId
  def c_myArrayStruct_EventDataPort_Id : Art.PortId
  def c_myStructArray_EventDataPort_Id : Art.PortId


  def logInfo(msg: String): Unit = {
    Art.logInfo(id, msg)
  }

  def logDebug(msg: String): Unit = {
    Art.logDebug(id, msg)
  }

  def logError(msg: String): Unit = {
    Art.logError(id, msg)
  }
}

@datatype class ConsumerThr_i_Initialization_Api (
  val id: Art.BridgeId,
  val c_myArrayInt32_DataPort_Id : Art.PortId,
  val c_myArrayStruct_DataPort_Id : Art.PortId,
  val c_myStructArray_DataPort_Id : Art.PortId,
  val c_myArrayInt32_EventDataPort_Id : Art.PortId,
  val c_myArrayStruct_EventDataPort_Id : Art.PortId,
  val c_myStructArray_EventDataPort_Id : Art.PortId) extends ConsumerThr_i_Api

@datatype class ConsumerThr_i_Operational_Api (
  val id: Art.BridgeId,
  val c_myArrayInt32_DataPort_Id : Art.PortId,
  val c_myArrayStruct_DataPort_Id : Art.PortId,
  val c_myStructArray_DataPort_Id : Art.PortId,
  val c_myArrayInt32_EventDataPort_Id : Art.PortId,
  val c_myArrayStruct_EventDataPort_Id : Art.PortId,
  val c_myStructArray_EventDataPort_Id : Art.PortId) extends ConsumerThr_i_Api {

  // Logika spec var representing port state for incoming data port
  @spec var c_myArrayInt32_DataPort: Gubmo_Structs_Arrays.MyArrayInt32 = $
  @spec def c_myArrayInt32_DataPort_Inv = Invariant(
    integrationArrayInt32_DataPort(c_myArrayInt32_DataPort)
  )

  def get_c_myArrayInt32_DataPort() : Option[Gubmo_Structs_Arrays.MyArrayInt32] = {
    Contract(
      Ensures(
        integrationArrayInt32_DataPort(c_myArrayInt32_DataPort),
        Res == Some(c_myArrayInt32_DataPort)
      )
    )
    val value : Option[Gubmo_Structs_Arrays.MyArrayInt32] = Art.getValue(c_myArrayInt32_DataPort_Id) match {
      case Some(Gubmo_Structs_Arrays.MyArrayInt32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port c_myArrayInt32_DataPort.  Expecting 'Gubmo_Structs_Arrays.MyArrayInt32_Payload' but received ${v}")
        None[Gubmo_Structs_Arrays.MyArrayInt32]()
      case _ => None[Gubmo_Structs_Arrays.MyArrayInt32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming data port
  @spec var c_myArrayStruct_DataPort: Gubmo_Structs_Arrays.MyArrayStruct = $

  def get_c_myArrayStruct_DataPort() : Option[Gubmo_Structs_Arrays.MyArrayStruct] = {
    Contract(
      Ensures(
        Res == Some(c_myArrayStruct_DataPort)
      )
    )
    val value : Option[Gubmo_Structs_Arrays.MyArrayStruct] = Art.getValue(c_myArrayStruct_DataPort_Id) match {
      case Some(Gubmo_Structs_Arrays.MyArrayStruct_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port c_myArrayStruct_DataPort.  Expecting 'Gubmo_Structs_Arrays.MyArrayStruct_Payload' but received ${v}")
        None[Gubmo_Structs_Arrays.MyArrayStruct]()
      case _ => None[Gubmo_Structs_Arrays.MyArrayStruct]()
    }
    return value
  }

  // Logika spec var representing port state for incoming data port
  @spec var c_myStructArray_DataPort: Gubmo_Structs_Arrays.MyStructArray_i = $

  def get_c_myStructArray_DataPort() : Option[Gubmo_Structs_Arrays.MyStructArray_i] = {
    Contract(
      Ensures(
        Res == Some(c_myStructArray_DataPort)
      )
    )
    val value : Option[Gubmo_Structs_Arrays.MyStructArray_i] = Art.getValue(c_myStructArray_DataPort_Id) match {
      case Some(Gubmo_Structs_Arrays.MyStructArray_i_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port c_myStructArray_DataPort.  Expecting 'Gubmo_Structs_Arrays.MyStructArray_i_Payload' but received ${v}")
        None[Gubmo_Structs_Arrays.MyStructArray_i]()
      case _ => None[Gubmo_Structs_Arrays.MyStructArray_i]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var c_myArrayInt32_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayInt32] = $
  @spec def c_myArrayInt32_EventDataPort_Inv = Invariant(
    c_myArrayInt32_EventDataPort.isEmpty || integrationArrayInt32_EventDataPort(c_myArrayInt32_EventDataPort.get)
  )

  def get_c_myArrayInt32_EventDataPort() : Option[Gubmo_Structs_Arrays.MyArrayInt32] = {
    Contract(
      Ensures(
        c_myArrayInt32_EventDataPort.isEmpty || integrationArrayInt32_EventDataPort(c_myArrayInt32_EventDataPort.get),
        Res == c_myArrayInt32_EventDataPort
      )
    )
    val value : Option[Gubmo_Structs_Arrays.MyArrayInt32] = Art.getValue(c_myArrayInt32_EventDataPort_Id) match {
      case Some(Gubmo_Structs_Arrays.MyArrayInt32_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port c_myArrayInt32_EventDataPort.  Expecting 'Gubmo_Structs_Arrays.MyArrayInt32_Payload' but received ${v}")
        None[Gubmo_Structs_Arrays.MyArrayInt32]()
      case _ => None[Gubmo_Structs_Arrays.MyArrayInt32]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var c_myArrayStruct_EventDataPort: Option[Gubmo_Structs_Arrays.MyArrayStruct] = $

  def get_c_myArrayStruct_EventDataPort() : Option[Gubmo_Structs_Arrays.MyArrayStruct] = {
    Contract(
      Ensures(
        Res == c_myArrayStruct_EventDataPort
      )
    )
    val value : Option[Gubmo_Structs_Arrays.MyArrayStruct] = Art.getValue(c_myArrayStruct_EventDataPort_Id) match {
      case Some(Gubmo_Structs_Arrays.MyArrayStruct_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port c_myArrayStruct_EventDataPort.  Expecting 'Gubmo_Structs_Arrays.MyArrayStruct_Payload' but received ${v}")
        None[Gubmo_Structs_Arrays.MyArrayStruct]()
      case _ => None[Gubmo_Structs_Arrays.MyArrayStruct]()
    }
    return value
  }

  // Logika spec var representing port state for incoming event data port
  @spec var c_myStructArray_EventDataPort: Option[Gubmo_Structs_Arrays.MyStructArray_i] = $
  @spec def c_myStructArray_EventDataPort_Inv = Invariant(
    c_myStructArray_EventDataPort.isEmpty || integrationStructArray_EventDataPort(c_myStructArray_EventDataPort.get)
  )

  def get_c_myStructArray_EventDataPort() : Option[Gubmo_Structs_Arrays.MyStructArray_i] = {
    Contract(
      Ensures(
        c_myStructArray_EventDataPort.isEmpty || integrationStructArray_EventDataPort(c_myStructArray_EventDataPort.get),
        Res == c_myStructArray_EventDataPort
      )
    )
    val value : Option[Gubmo_Structs_Arrays.MyStructArray_i] = Art.getValue(c_myStructArray_EventDataPort_Id) match {
      case Some(Gubmo_Structs_Arrays.MyStructArray_i_Payload(v)) => Some(v)
      case Some(v) =>
        Art.logError(id, s"Unexpected payload on port c_myStructArray_EventDataPort.  Expecting 'Gubmo_Structs_Arrays.MyStructArray_i_Payload' but received ${v}")
        None[Gubmo_Structs_Arrays.MyStructArray_i]()
      case _ => None[Gubmo_Structs_Arrays.MyStructArray_i]()
    }
    return value
  }
}
