// #Sireum

package sysml.Gubmo_Structs_Arrays

import org.sireum._
import art._
import sysml._
import sysml.Gubmo_Structs_Arrays.{ProducerThr_i_producer_producer => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class ProducerThr_i_producer_producer_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  p_myArrayInt32_DataPort: Port[Gubmo_Structs_Arrays.MyArrayInt32],
  p_myArrayStruct_DataPort: Port[Gubmo_Structs_Arrays.MyArrayStruct],
  p_myStructArray_DataPort: Port[Gubmo_Structs_Arrays.MyStructArray_i],
  p_myArrayInt32_EventDataPort: Port[Gubmo_Structs_Arrays.MyArrayInt32],
  p_myArrayStruct_EventDataPort: Port[Gubmo_Structs_Arrays.MyArrayStruct],
  p_myStructArray_EventDataPort: Port[Gubmo_Structs_Arrays.MyStructArray_i]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](p_myArrayInt32_DataPort,
                              p_myArrayStruct_DataPort,
                              p_myStructArray_DataPort),

    eventIns = ISZ[art.UPort](),

    eventOuts = ISZ[art.UPort](p_myArrayInt32_EventDataPort,
                               p_myArrayStruct_EventDataPort,
                               p_myStructArray_EventDataPort)
  )

  val initialization_api : ProducerThr_i_Initialization_Api = {
    val api = ProducerThr_i_Initialization_Api(
      id,
      p_myArrayInt32_DataPort.id,
      p_myArrayStruct_DataPort.id,
      p_myStructArray_DataPort.id,
      p_myArrayInt32_EventDataPort.id,
      p_myArrayStruct_EventDataPort.id,
      p_myStructArray_EventDataPort.id
    )
    ProducerThr_i_producer_producer_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : ProducerThr_i_Operational_Api = {
    val api = ProducerThr_i_Operational_Api(
      id,
      p_myArrayInt32_DataPort.id,
      p_myArrayStruct_DataPort.id,
      p_myStructArray_DataPort.id,
      p_myArrayInt32_EventDataPort.id,
      p_myArrayStruct_EventDataPort.id,
      p_myStructArray_EventDataPort.id
    )
    ProducerThr_i_producer_producer_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    ProducerThr_i_producer_producer_Bridge.EntryPoints(
      id,

      p_myArrayInt32_DataPort.id,
      p_myArrayStruct_DataPort.id,
      p_myStructArray_DataPort.id,
      p_myArrayInt32_EventDataPort.id,
      p_myArrayStruct_EventDataPort.id,
      p_myStructArray_EventDataPort.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object ProducerThr_i_producer_producer_Bridge {

  var c_initialization_api: Option[ProducerThr_i_Initialization_Api] = None()
  var c_operational_api: Option[ProducerThr_i_Operational_Api] = None()

  @datatype class EntryPoints(
    ProducerThr_i_producer_producer_BridgeId : Art.BridgeId,
    p_myArrayInt32_DataPort_Id : Art.PortId,
    p_myArrayStruct_DataPort_Id : Art.PortId,
    p_myStructArray_DataPort_Id : Art.PortId,
    p_myArrayInt32_EventDataPort_Id : Art.PortId,
    p_myArrayStruct_EventDataPort_Id : Art.PortId,
    p_myStructArray_EventDataPort_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: ProducerThr_i_Initialization_Api,
    operational_api: ProducerThr_i_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS()

    val dataOutPortIds: ISZ[Art.PortId] = IS(p_myArrayInt32_DataPort_Id,
                                             p_myArrayStruct_DataPort_Id,
                                             p_myStructArray_DataPort_Id)

    val eventOutPortIds: ISZ[Art.PortId] = IS(p_myArrayInt32_EventDataPort_Id,
                                              p_myArrayStruct_EventDataPort_Id,
                                              p_myStructArray_EventDataPort_Id)

    def initialise(): Unit = {
      ProducerThr_i_producer_producer_EntryPoint_Companion.pre_initialise()

      // implement the following method in 'component':  def initialise(api: ProducerThr_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)

      ProducerThr_i_producer_producer_EntryPoint_Companion.post_initialise()

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      ProducerThr_i_producer_producer_Injection_Service.pre_receiveInput()

      Art.receiveInput(eventInPortIds, dataInPortIds)

      ProducerThr_i_producer_producer_EntryPoint_Companion.pre_compute()

      // implement the following in 'component':  def timeTriggered(api: ProducerThr_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      ProducerThr_i_producer_producer_EntryPoint_Companion.post_compute()

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: ProducerThr_i_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: ProducerThr_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: ProducerThr_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}