// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait domain_monitor_process_domain_monitor_thread_Api {}

  pub trait domain_monitor_process_domain_monitor_thread_Put_Api: domain_monitor_process_domain_monitor_thread_Api {
  }

  pub trait domain_monitor_process_domain_monitor_thread_Get_Api: domain_monitor_process_domain_monitor_thread_Api {
    #[verifier::external_body]
    fn unverified_get_seL4_ArduPilot_ArduPilot_EthernetFramesTx(
      &mut self,
      value: &Ghost<Option<SW::StructuredEthernetMessage_i>>) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_seL4_ArduPilot_ArduPilot_EthernetFramesTx();
    }

    #[verifier::external_body]
    fn unverified_get_seL4_Firewall_Firewall_EthernetFramesRxOut(
      &mut self,
      value: &Ghost<Option<SW::StructuredEthernetMessage_i>>) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_seL4_Firewall_Firewall_EthernetFramesRxOut();
    }

    #[verifier::external_body]
    fn unverified_get_seL4_Firewall_Firewall_EthernetFramesTxOut(
      &mut self,
      value: &Ghost<Option<SW::StructuredEthernetMessage_i>>) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_seL4_Firewall_Firewall_EthernetFramesTxOut();
    }

    #[verifier::external_body]
    fn unverified_get_seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(
      &mut self,
      value: &Ghost<Option<SW::StructuredEthernetMessage_i>>) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx();
    }
  }

  pub trait domain_monitor_process_domain_monitor_thread_Full_Api: domain_monitor_process_domain_monitor_thread_Put_Api + domain_monitor_process_domain_monitor_thread_Get_Api {}

  pub struct domain_monitor_process_domain_monitor_thread_Application_Api<API: domain_monitor_process_domain_monitor_thread_Api> {
    pub api: API,

    pub ghost seL4_ArduPilot_ArduPilot_EthernetFramesTx: Option<SW::StructuredEthernetMessage_i>,
    pub ghost seL4_Firewall_Firewall_EthernetFramesRxOut: Option<SW::StructuredEthernetMessage_i>,
    pub ghost seL4_Firewall_Firewall_EthernetFramesTxOut: Option<SW::StructuredEthernetMessage_i>,
    pub ghost seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx: Option<SW::StructuredEthernetMessage_i>
  }

  impl<API: domain_monitor_process_domain_monitor_thread_Put_Api> domain_monitor_process_domain_monitor_thread_Application_Api<API> {
  }

  impl<API: domain_monitor_process_domain_monitor_thread_Get_Api> domain_monitor_process_domain_monitor_thread_Application_Api<API> {
    pub fn get_seL4_ArduPilot_ArduPilot_EthernetFramesTx(&mut self) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        old(self).seL4_ArduPilot_ArduPilot_EthernetFramesTx == self.seL4_ArduPilot_ArduPilot_EthernetFramesTx,
        res == self.seL4_ArduPilot_ArduPilot_EthernetFramesTx,
        old(self).seL4_Firewall_Firewall_EthernetFramesRxOut == self.seL4_Firewall_Firewall_EthernetFramesRxOut,
        old(self).seL4_Firewall_Firewall_EthernetFramesTxOut == self.seL4_Firewall_Firewall_EthernetFramesTxOut,
        old(self).seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx == self.seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx,
    {
      self.api.unverified_get_seL4_ArduPilot_ArduPilot_EthernetFramesTx(&Ghost(self.seL4_ArduPilot_ArduPilot_EthernetFramesTx))
    }
    pub fn get_seL4_Firewall_Firewall_EthernetFramesRxOut(&mut self) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        old(self).seL4_ArduPilot_ArduPilot_EthernetFramesTx == self.seL4_ArduPilot_ArduPilot_EthernetFramesTx,
        old(self).seL4_Firewall_Firewall_EthernetFramesRxOut == self.seL4_Firewall_Firewall_EthernetFramesRxOut,
        res == self.seL4_Firewall_Firewall_EthernetFramesRxOut,
        old(self).seL4_Firewall_Firewall_EthernetFramesTxOut == self.seL4_Firewall_Firewall_EthernetFramesTxOut,
        old(self).seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx == self.seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx,
    {
      self.api.unverified_get_seL4_Firewall_Firewall_EthernetFramesRxOut(&Ghost(self.seL4_Firewall_Firewall_EthernetFramesRxOut))
    }
    pub fn get_seL4_Firewall_Firewall_EthernetFramesTxOut(&mut self) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        old(self).seL4_ArduPilot_ArduPilot_EthernetFramesTx == self.seL4_ArduPilot_ArduPilot_EthernetFramesTx,
        old(self).seL4_Firewall_Firewall_EthernetFramesRxOut == self.seL4_Firewall_Firewall_EthernetFramesRxOut,
        old(self).seL4_Firewall_Firewall_EthernetFramesTxOut == self.seL4_Firewall_Firewall_EthernetFramesTxOut,
        res == self.seL4_Firewall_Firewall_EthernetFramesTxOut,
        old(self).seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx == self.seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx,
    {
      self.api.unverified_get_seL4_Firewall_Firewall_EthernetFramesTxOut(&Ghost(self.seL4_Firewall_Firewall_EthernetFramesTxOut))
    }
    pub fn get_seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(&mut self) -> (res : Option<SW::StructuredEthernetMessage_i>)
      ensures
        old(self).seL4_ArduPilot_ArduPilot_EthernetFramesTx == self.seL4_ArduPilot_ArduPilot_EthernetFramesTx,
        old(self).seL4_Firewall_Firewall_EthernetFramesRxOut == self.seL4_Firewall_Firewall_EthernetFramesRxOut,
        old(self).seL4_Firewall_Firewall_EthernetFramesTxOut == self.seL4_Firewall_Firewall_EthernetFramesTxOut,
        old(self).seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx == self.seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx,
        res == self.seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx,
    {
      self.api.unverified_get_seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx(&Ghost(self.seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx))
    }
  }

  pub struct domain_monitor_process_domain_monitor_thread_Initialization_Api;
  impl domain_monitor_process_domain_monitor_thread_Api for domain_monitor_process_domain_monitor_thread_Initialization_Api {}
  impl domain_monitor_process_domain_monitor_thread_Put_Api for domain_monitor_process_domain_monitor_thread_Initialization_Api {}

  pub const fn init_api() -> domain_monitor_process_domain_monitor_thread_Application_Api<domain_monitor_process_domain_monitor_thread_Initialization_Api> {
    return domain_monitor_process_domain_monitor_thread_Application_Api {
      api: domain_monitor_process_domain_monitor_thread_Initialization_Api {},

      seL4_ArduPilot_ArduPilot_EthernetFramesTx: None,
      seL4_Firewall_Firewall_EthernetFramesRxOut: None,
      seL4_Firewall_Firewall_EthernetFramesTxOut: None,
      seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx: None
    }
  }

  pub struct domain_monitor_process_domain_monitor_thread_Compute_Api;
  impl domain_monitor_process_domain_monitor_thread_Api for domain_monitor_process_domain_monitor_thread_Compute_Api {}
  impl domain_monitor_process_domain_monitor_thread_Put_Api for domain_monitor_process_domain_monitor_thread_Compute_Api {}
  impl domain_monitor_process_domain_monitor_thread_Get_Api for domain_monitor_process_domain_monitor_thread_Compute_Api {}
  impl domain_monitor_process_domain_monitor_thread_Full_Api for domain_monitor_process_domain_monitor_thread_Compute_Api {}

  pub const fn compute_api() -> domain_monitor_process_domain_monitor_thread_Application_Api<domain_monitor_process_domain_monitor_thread_Compute_Api> {
    return domain_monitor_process_domain_monitor_thread_Application_Api {
      api: domain_monitor_process_domain_monitor_thread_Compute_Api {},

      seL4_ArduPilot_ArduPilot_EthernetFramesTx: None,
      seL4_Firewall_Firewall_EthernetFramesRxOut: None,
      seL4_Firewall_Firewall_EthernetFramesTxOut: None,
      seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_EthernetFramesRx: None
    }
  }

}