// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum FrameProtocol {
    pub TCP = 0,
    pub ARP = 1,
  }

  impl Default for FrameProtocol {
    fn default() -> Self
    {
      FrameProtocol::TCP
    }
  }
}