// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  pub const SW_RawEthernetMessage_DIM_0: usize = 1600;

  pub type RawEthernetMessage = [u8; SW_RawEthernetMessage_DIM_0];

}

// Memory layout as HAMR computes it
const _: () = assert!(core::mem::size_of::<RawEthernetMessage>() == 1600);
const _: () = assert!(core::mem::align_of::<RawEthernetMessage>() == 1);
