#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if codegen is rerun

typedef struct event_data_port_port_queues_struct_i {
  int32_t currentEvent;
  int32_t totalEventsSent;
} event_data_port_port_queues_struct_i;

#define event_data_port_port_queues_ArrayOfStruct_BYTE_SIZE 80
#define event_data_port_port_queues_ArrayOfStruct_DIM_0 10

typedef event_data_port_port_queues_struct_i event_data_port_port_queues_ArrayOfStruct [event_data_port_port_queues_ArrayOfStruct_DIM_0];
