#pragma once

// Do not edit this file as it will be overwritten if codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_event_data_port_port_queues_ArrayOfStruct_1.h>
#include <sb_queue_event_data_port_port_queues_ArrayOfStruct_2.h>
#include <sb_queue_event_data_port_port_queues_ArrayOfStruct_5.h>
