# This file will not be overwritten if HAMR codegen is rerun

[package]
name = "data"
version = "0.1.0"
edition = "2021"

[dependencies]
# -----------------------------------------------------------------------------
# Verus crate dependencies
#
# It is recommended to use the Verus release:
# https://github.com/verus-lang/verus/releases/tag/release/0.2026.09.27.3cf1832
# -----------------------------------------------------------------------------
vstd = { version = "=0.0.0-2026-09-20-0158", default-features=false }
verus_builtin = { version = "=0.0.0-2026-09-16-0054" }
verus_builtin_macros = { version = "=0.0.0-2026-09-20-0158" }

[package.metadata.verus]
verify = true

