// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property state_var_alias_exercise -- Pre-Assert and Next-Assert VCs for every schema transition.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::assertions_state_var_alias_exercise::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[1]: Pre-Assert -- before_oi |- OI compute + integration assumes */
pub proof fn vc_pre_assert_oi(st: SystemState)
  requires
    true /* before_oi has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[2]: Next-Assert (task) -- before_oi + frames + OI postcondition |- after_oi */
pub proof fn vc_next_assert_task_oi(pre: SystemState, post: SystemState)
  requires
    true /* before_oi has no assertion */,
    oi_local_write_frame(pre, post),
    oi_global_write_frame(pre, post),
    oi::compute_spec_Allowed_AlarmTempWStatus_Ranges_guarantee(post.lower_alarm_tempWstatus, post.upper_alarm_tempWstatus),
    oi::compute_spec_Desired_Temps_Ordered_guarantee(post.lower_desired_tempWstatus, post.upper_desired_tempWstatus),
    oi::integration_spec_Allowed_LowerAlarmTempWstatus_guarantee(post.lower_alarm_tempWstatus),
    oi::integration_spec_Allowed_UpperAlarmTempWstatus_guarantee(post.upper_alarm_tempWstatus),
  ensures
    sys_assert_state_var_alias_exercise_after_oi(post),
{}

/** VC[3]: Pre-Assert -- trivial: this property does not use TS's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_ts(st: SystemState)
  requires
    true /* before_ts has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[4]: Next-Assert (task) -- before_ts + frames + TS postcondition |- after_ts */
pub proof fn vc_next_assert_task_ts(pre: SystemState, post: SystemState)
  requires
    true /* before_ts has no assertion */,
    ts_local_write_frame(pre, post),
    ts_global_write_frame(pre, post),
  ensures
    true /* after_ts has no assertion */,
{}

/** VC[5]: Next-Assert (control point) -- START |- before_oi, before_ts (state unchanged) */
pub proof fn vc_next_assert_skip_t2(st: SystemState)
  requires
    true /* START has no assertion */,
  ensures
    true /* before_oi has no assertion */,
    true /* before_ts has no assertion */,
{}

/** VC[6]: Next-Assert (control point) -- after_oi, after_ts |- post_join_1 (state unchanged) */
pub proof fn vc_next_assert_skip_t3(st: SystemState)
  requires
    sys_assert_state_var_alias_exercise_after_oi(st),
    true /* after_ts has no assertion */,
  ensures
    true /* post_join_1 has no assertion */,
{}

/** VC[7]: Pre-Assert -- trivial: this property does not use DRF's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_drf(st: SystemState)
  requires
    true /* before_drf has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[8]: Next-Assert (task) -- before_drf + frames + DRF postcondition |- after_drf */
pub proof fn vc_next_assert_task_drf(pre: SystemState, post: SystemState)
  requires
    true /* before_drf has no assertion */,
    drf_local_write_frame(pre, post),
    drf_global_write_frame(pre, post),
  ensures
    true /* after_drf has no assertion */,
{}

/** VC[9]: Pre-Assert -- trivial: this property does not use MRI's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_mri(st: SystemState)
  requires
    true /* after_drf has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[10]: Next-Assert (task) -- after_drf + frames + MRI postcondition |- after_mri */
pub proof fn vc_next_assert_task_mri(pre: SystemState, post: SystemState)
  requires
    true /* after_drf has no assertion */,
    mri_local_write_frame(pre, post),
    mri_global_write_frame(pre, post),
  ensures
    true /* after_mri has no assertion */,
{}

/** VC[11]: Pre-Assert -- trivial: this property does not use MRM's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_mrm(st: SystemState)
  requires
    true /* after_mri has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[12]: Next-Assert (task) -- after_mri + frames + MRM postcondition |- after_mrm */
pub proof fn vc_next_assert_task_mrm(pre: SystemState, post: SystemState)
  requires
    true /* after_mri has no assertion */,
    mrm_local_write_frame(pre, post),
    mrm_global_write_frame(pre, post),
  ensures
    true /* after_mrm has no assertion */,
{}

/** VC[13]: Pre-Assert -- trivial: this property does not use MHS's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_mhs(st: SystemState)
  requires
    true /* after_mrm has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[14]: Next-Assert (task) -- after_mrm + frames + MHS postcondition |- after_mhs */
pub proof fn vc_next_assert_task_mhs(pre: SystemState, post: SystemState)
  requires
    true /* after_mrm has no assertion */,
    mhs_local_write_frame(pre, post),
    mhs_global_write_frame(pre, post),
  ensures
    true /* after_mhs has no assertion */,
{}

/** VC[15]: Pre-Assert -- trivial: this property does not use DMF's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_dmf(st: SystemState)
  requires
    true /* before_dmf has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[16]: Next-Assert (task) -- before_dmf + frames + DMF postcondition |- after_dmf */
pub proof fn vc_next_assert_task_dmf(pre: SystemState, post: SystemState)
  requires
    true /* before_dmf has no assertion */,
    dmf_local_write_frame(pre, post),
    dmf_global_write_frame(pre, post),
  ensures
    true /* after_dmf has no assertion */,
{}

/** VC[17]: Pre-Assert -- trivial: this property does not use MMI's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_mmi(st: SystemState)
  requires
    true /* after_dmf has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[18]: Next-Assert (task) -- after_dmf + frames + MMI postcondition |- after_mmi */
pub proof fn vc_next_assert_task_mmi(pre: SystemState, post: SystemState)
  requires
    true /* after_dmf has no assertion */,
    mmi_local_write_frame(pre, post),
    mmi_global_write_frame(pre, post),
  ensures
    true /* after_mmi has no assertion */,
{}

/** VC[19]: Pre-Assert -- trivial: this property does not use MMM's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_mmm(st: SystemState)
  requires
    true /* after_mmi has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[20]: Next-Assert (task) -- after_mmi + frames + MMM postcondition |- after_mmm */
pub proof fn vc_next_assert_task_mmm(pre: SystemState, post: SystemState)
  requires
    true /* after_mmi has no assertion */,
    mmm_local_write_frame(pre, post),
    mmm_global_write_frame(pre, post),
  ensures
    true /* after_mmm has no assertion */,
{}

/** VC[21]: Pre-Assert -- trivial: this property does not use MA's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_ma(st: SystemState)
  requires
    true /* after_mmm has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[22]: Next-Assert (task) -- after_mmm + frames + MA postcondition |- after_ma */
pub proof fn vc_next_assert_task_ma(pre: SystemState, post: SystemState)
  requires
    true /* after_mmm has no assertion */,
    ma_local_write_frame(pre, post),
    ma_global_write_frame(pre, post),
  ensures
    true /* after_ma has no assertion */,
{}

/** VC[23]: Next-Assert (control point) -- post_join_1 |- before_drf, before_dmf (state unchanged) */
pub proof fn vc_next_assert_skip_t12(st: SystemState)
  requires
    true /* post_join_1 has no assertion */,
  ensures
    true /* before_drf has no assertion */,
    true /* before_dmf has no assertion */,
{}

/** VC[24]: Next-Assert (control point) -- after_mhs, after_ma |- post_join_2 (state unchanged) */
pub proof fn vc_next_assert_skip_t13(st: SystemState)
  requires
    true /* after_mhs has no assertion */,
    true /* after_ma has no assertion */,
  ensures
    true /* post_join_2 has no assertion */,
{}

/** VC[25]: Pre-Assert -- trivial: this property does not use HS's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_hs(st: SystemState)
  requires
    true /* post_join_2 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[26]: Next-Assert (task) -- post_join_2 + frames + HS postcondition |- after_hs */
pub proof fn vc_next_assert_task_hs(pre: SystemState, post: SystemState)
  requires
    true /* post_join_2 has no assertion */,
    hs_local_write_frame(pre, post),
    hs_global_write_frame(pre, post),
  ensures
    true /* after_hs has no assertion */,
{}

/** VC[27]: Next-Assert (control point) -- after_hs |- END (state unchanged) */
pub proof fn vc_next_assert_skip_t15(st: SystemState)
  requires
    true /* after_hs has no assertion */,
  ensures
    true /* END has no assertion */,
{}

} // verus!
