// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::monitor_monitor_api::*;
use data::*;
use super::monitor_monitor_app::monitor_monitor;
use vstd::prelude::*;

verus! {

  impl monitor_monitor {
    #[verifier::external_body]
    pub fn pre_timeTriggered<API: monitor_monitor_Full_Api> (
      &mut self,
      api: &monitor_monitor_Application_Api<API>)
    {
      let sent_sample = api.peek_sent_sample();
      let observed_sample = api.peek_observed_sample();

      r2u2_core::load_bool_signal(&mut self.r2u2_monitor, 0, sent_sample.is_some()); // Loading signal api_sent_sample_nonEmpty into index 0
      r2u2_core::load_bool_signal(&mut self.r2u2_monitor, 1, observed_sample.is_some()); // Loading signal api_observed_sample_nonEmpty into index 1
      r2u2_core::load_int_signal(&mut self.r2u2_monitor, 2, observed_sample.unwrap_or_default().into()); // Loading signal api_observed_sample into index 2
      r2u2_core::load_int_signal(&mut self.r2u2_monitor, 3, sent_sample.unwrap_or_default().into()); // Loading signal api_sent_sample into index 3
    }

    #[verifier::external_body]
    pub fn post_timeTriggered<API: monitor_monitor_Full_Api> (
      &mut self,
      api: &mut monitor_monitor_Application_Api<API>)
    {
      r2u2_core::monitor_step(&mut self.r2u2_monitor);
      for out in r2u2_core::get_output_buffer(&self.r2u2_monitor) {
          log::info!("{}:{},{}", out.spec_num, out.verdict.time, if out.verdict.truth {"T"} else {"F"} );
      }
    }
  }

  #[verifier::external_body]
  pub struct R2U2Monitor { inner: r2u2_core::Monitor }

  #[verifier::external]
  impl core::ops::Deref for R2U2Monitor {
    type Target = r2u2_core::Monitor;
    fn deref(&self) -> &Self::Target { &self.inner }
  }

  #[verifier::external]
  impl core::ops::DerefMut for R2U2Monitor {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.inner }
  }

  #[verifier::external_body]
  pub(super) fn default_r2u2_monitor() -> R2U2Monitor {
    R2U2Monitor { inner: r2u2_core::Monitor::default() }
  }

  #[verifier::external_body]
  pub(super) fn load_spec(monitor: &mut R2U2Monitor) {
    r2u2_core::update_binary_file(include_bytes!("spec.bin"), monitor);
  }

}
