[package]
name = "firewall-core"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = { git = "https://github.com/verus-lang/verus.git", default-features=false }
builtin = { git = "https://github.com/verus-lang/verus.git" }
builtin_macros = { git = "https://github.com/verus-lang/verus.git" }
