// Do not edit this file as it will be overwritten if codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn put_EthernetFramesTx0(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_EthernetFramesTx1(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_EthernetFramesTx2(value: *mut SW::RawEthernetMessage) -> bool;
  fn put_EthernetFramesTx3(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesRx0(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesRx1(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesRx2(value: *mut SW::RawEthernetMessage) -> bool;
  fn get_EthernetFramesRx3(value: *mut SW::RawEthernetMessage) -> bool;
}

pub fn unsafe_put_EthernetFramesTx0(value: &SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     return put_EthernetFramesTx0(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
   }
 }

pub fn unsafe_put_EthernetFramesTx1(value: &SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     return put_EthernetFramesTx1(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
   }
 }

pub fn unsafe_put_EthernetFramesTx2(value: &SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     return put_EthernetFramesTx2(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
   }
 }

pub fn unsafe_put_EthernetFramesTx3(value: &SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     return put_EthernetFramesTx3(value as *const SW::RawEthernetMessage as *mut SW::RawEthernetMessage);
   }
 }

pub fn unsafe_get_EthernetFramesRx0() -> Option<SW::RawEthernetMessage> 
 {
   unsafe {
     let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
     if (get_EthernetFramesRx0(value)) {
       return Some(*value);
     } else {
       return None;
     }
   }
 }

pub fn unsafe_get_EthernetFramesRx1() -> Option<SW::RawEthernetMessage> 
 {
   unsafe {
     let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
     if (get_EthernetFramesRx1(value)) {
       return Some(*value);
     } else {
       return None;
     }
   }
 }

pub fn unsafe_get_EthernetFramesRx2() -> Option<SW::RawEthernetMessage> 
 {
   unsafe {
     let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
     if (get_EthernetFramesRx2(value)) {
       return Some(*value);
     } else {
       return None;
     }
   }
 }

pub fn unsafe_get_EthernetFramesRx3() -> Option<SW::RawEthernetMessage> 
 {
   unsafe {
     let value: *mut SW::RawEthernetMessage = &mut [0; SW::SW_RawEthernetMessage_DIM_0];
     if (get_EthernetFramesRx3(value)) {
       return Some(*value);
     } else {
       return None;
     }
   }
 }

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref OUT_EthernetFramesTx0: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTx1: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTx2: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref OUT_EthernetFramesTx3: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesRx0: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesRx1: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesRx2: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
  pub static ref IN_EthernetFramesRx3: Mutex<Option<SW::RawEthernetMessage>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *OUT_EthernetFramesTx0.lock().unwrap() = None;
    *OUT_EthernetFramesTx1.lock().unwrap() = None;
    *OUT_EthernetFramesTx2.lock().unwrap() = None;
    *OUT_EthernetFramesTx3.lock().unwrap() = None;
    *IN_EthernetFramesRx0.lock().unwrap() = None;
    *IN_EthernetFramesRx1.lock().unwrap() = None;
    *IN_EthernetFramesRx2.lock().unwrap() = None;
    *IN_EthernetFramesRx3.lock().unwrap() = None;
  }
}

#[cfg(test)]
pub fn put_EthernetFramesTx0(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     *OUT_EthernetFramesTx0.lock().unwrap() = Some(*value);
     return true;
   }
 }

#[cfg(test)]
pub fn put_EthernetFramesTx1(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     *OUT_EthernetFramesTx1.lock().unwrap() = Some(*value);
     return true;
   }
 }

#[cfg(test)]
pub fn put_EthernetFramesTx2(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     *OUT_EthernetFramesTx2.lock().unwrap() = Some(*value);
     return true;
   }
 }

#[cfg(test)]
pub fn put_EthernetFramesTx3(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     *OUT_EthernetFramesTx3.lock().unwrap() = Some(*value);
     return true;
   }
 }

#[cfg(test)]
pub fn get_EthernetFramesRx0(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     match *IN_EthernetFramesRx0.lock().unwrap() {
       Some(v) => {
         *value = v;
         return true;
       },
       None => return false,
     }
   }
 }

#[cfg(test)]
pub fn get_EthernetFramesRx1(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     match *IN_EthernetFramesRx1.lock().unwrap() {
       Some(v) => {
         *value = v;
         return true;
       },
       None => return false,
     }
   }
 }

#[cfg(test)]
pub fn get_EthernetFramesRx2(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     match *IN_EthernetFramesRx2.lock().unwrap() {
       Some(v) => {
         *value = v;
         return true;
       },
       None => return false,
     }
   }
 }

#[cfg(test)]
pub fn get_EthernetFramesRx3(value: *mut SW::RawEthernetMessage) -> bool 
 {
   unsafe {
     match *IN_EthernetFramesRx3.lock().unwrap() {
       Some(v) => {
         *value = v;
         return true;
       },
       None => return false,
     }
   }
 }
