// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait seL4_ArduPilot_ArduPilot_Api {}

  pub trait seL4_ArduPilot_ArduPilot_Put_Api: seL4_ArduPilot_ArduPilot_Api {
    #[verifier::external_body]
    fn unverified_put_EthernetFramesTx0(
      &mut self,
      value: SW::RawEthernetMessage) 
    {
      extern_api::unsafe_put_EthernetFramesTx0(&value);
    }

    #[verifier::external_body]
    fn unverified_put_EthernetFramesTx1(
      &mut self,
      value: SW::RawEthernetMessage) 
    {
      extern_api::unsafe_put_EthernetFramesTx1(&value);
    }

    #[verifier::external_body]
    fn unverified_put_EthernetFramesTx2(
      &mut self,
      value: SW::RawEthernetMessage) 
    {
      extern_api::unsafe_put_EthernetFramesTx2(&value);
    }

    #[verifier::external_body]
    fn unverified_put_EthernetFramesTx3(
      &mut self,
      value: SW::RawEthernetMessage) 
    {
      extern_api::unsafe_put_EthernetFramesTx3(&value);
    }
  }

  pub trait seL4_ArduPilot_ArduPilot_Get_Api: seL4_ArduPilot_ArduPilot_Api {
    #[verifier::external_body]
    fn unverified_get_EthernetFramesRx0(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@ 
    {
      return extern_api::unsafe_get_EthernetFramesRx0();
    }

    #[verifier::external_body]
    fn unverified_get_EthernetFramesRx1(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@ 
    {
      return extern_api::unsafe_get_EthernetFramesRx1();
    }

    #[verifier::external_body]
    fn unverified_get_EthernetFramesRx2(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@ 
    {
      return extern_api::unsafe_get_EthernetFramesRx2();
    }

    #[verifier::external_body]
    fn unverified_get_EthernetFramesRx3(
      &mut self,
      value: &Ghost<Option<SW::RawEthernetMessage>>) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        res == value@ 
    {
      return extern_api::unsafe_get_EthernetFramesRx3();
    }
  }

  pub trait seL4_ArduPilot_ArduPilot_Full_Api: seL4_ArduPilot_ArduPilot_Put_Api + seL4_ArduPilot_ArduPilot_Get_Api {}

  pub struct seL4_ArduPilot_ArduPilot_Application_Api<API: seL4_ArduPilot_ArduPilot_Api> {
    pub api: API,

    pub ghost EthernetFramesTx0: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesTx1: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesTx2: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesTx3: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRx0: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRx1: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRx2: Option<SW::RawEthernetMessage>,
    pub ghost EthernetFramesRx3: Option<SW::RawEthernetMessage>
  }

  impl<API: seL4_ArduPilot_ArduPilot_Put_Api> seL4_ArduPilot_ArduPilot_Application_Api<API> {
    pub fn put_EthernetFramesTx0(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        self.EthernetFramesTx0 == Some(value),
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_put_EthernetFramesTx0(value);
      self.EthernetFramesTx0 = Some(value);
    }
    pub fn put_EthernetFramesTx1(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        self.EthernetFramesTx1 == Some(value),
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_put_EthernetFramesTx1(value);
      self.EthernetFramesTx1 = Some(value);
    }
    pub fn put_EthernetFramesTx2(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        self.EthernetFramesTx2 == Some(value),
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_put_EthernetFramesTx2(value);
      self.EthernetFramesTx2 = Some(value);
    }
    pub fn put_EthernetFramesTx3(
      &mut self,
      value: SW::RawEthernetMessage)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        self.EthernetFramesTx3 == Some(value) 
    {
      self.api.unverified_put_EthernetFramesTx3(value);
      self.EthernetFramesTx3 = Some(value);
    }
  }

  impl<API: seL4_ArduPilot_ArduPilot_Get_Api> seL4_ArduPilot_ArduPilot_Application_Api<API> {
    pub fn get_EthernetFramesRx0(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        res == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_get_EthernetFramesRx0(&Ghost(self.EthernetFramesRx0))
    }
    pub fn get_EthernetFramesRx1(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        res == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_get_EthernetFramesRx1(&Ghost(self.EthernetFramesRx1))
    }
    pub fn get_EthernetFramesRx2(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        res == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_get_EthernetFramesRx2(&Ghost(self.EthernetFramesRx2))
    }
    pub fn get_EthernetFramesRx3(&mut self) -> (res : Option<SW::RawEthernetMessage>)
      ensures
        old(self).EthernetFramesRx0 == self.EthernetFramesRx0,
        old(self).EthernetFramesRx1 == self.EthernetFramesRx1,
        old(self).EthernetFramesRx2 == self.EthernetFramesRx2,
        old(self).EthernetFramesRx3 == self.EthernetFramesRx3,
        res == self.EthernetFramesRx3,
        old(self).EthernetFramesTx0 == self.EthernetFramesTx0,
        old(self).EthernetFramesTx1 == self.EthernetFramesTx1,
        old(self).EthernetFramesTx2 == self.EthernetFramesTx2,
        old(self).EthernetFramesTx3 == self.EthernetFramesTx3 
    {
      self.api.unverified_get_EthernetFramesRx3(&Ghost(self.EthernetFramesRx3))
    }
  }

  pub struct seL4_ArduPilot_ArduPilot_Initialization_Api;
  impl seL4_ArduPilot_ArduPilot_Api for seL4_ArduPilot_ArduPilot_Initialization_Api {}
  impl seL4_ArduPilot_ArduPilot_Put_Api for seL4_ArduPilot_ArduPilot_Initialization_Api {}

  pub const fn init_api() -> seL4_ArduPilot_ArduPilot_Application_Api<seL4_ArduPilot_ArduPilot_Initialization_Api> {
    return seL4_ArduPilot_ArduPilot_Application_Api {
      api: seL4_ArduPilot_ArduPilot_Initialization_Api {},

      EthernetFramesTx0: None,
      EthernetFramesTx1: None,
      EthernetFramesTx2: None,
      EthernetFramesTx3: None,
      EthernetFramesRx0: None,
      EthernetFramesRx1: None,
      EthernetFramesRx2: None,
      EthernetFramesRx3: None
    }
  }

  pub struct seL4_ArduPilot_ArduPilot_Compute_Api;
  impl seL4_ArduPilot_ArduPilot_Api for seL4_ArduPilot_ArduPilot_Compute_Api {}
  impl seL4_ArduPilot_ArduPilot_Put_Api for seL4_ArduPilot_ArduPilot_Compute_Api {}
  impl seL4_ArduPilot_ArduPilot_Get_Api for seL4_ArduPilot_ArduPilot_Compute_Api {}
  impl seL4_ArduPilot_ArduPilot_Full_Api for seL4_ArduPilot_ArduPilot_Compute_Api {}

  pub const fn compute_api() -> seL4_ArduPilot_ArduPilot_Application_Api<seL4_ArduPilot_ArduPilot_Compute_Api> {
    return seL4_ArduPilot_ArduPilot_Application_Api {
      api: seL4_ArduPilot_ArduPilot_Compute_Api {},

      EthernetFramesTx0: None,
      EthernetFramesTx1: None,
      EthernetFramesTx2: None,
      EthernetFramesTx3: None,
      EthernetFramesRx0: None,
      EthernetFramesRx1: None,
      EthernetFramesRx2: None,
      EthernetFramesRx3: None
    }
  }
}