// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;
use vstd::prelude::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct PreState_thermostat_mt_mmm_mmm {
    pub In_lastMonitorMode: Isolette_Data_Model::Monitor_Mode,
    pub api_current_tempWstatus: Isolette_Data_Model::TempWstatus_i,
    pub api_interface_failure: Isolette_Data_Model::Failure_Flag_i,
    pub api_internal_failure: Isolette_Data_Model::Failure_Flag_i,
  }

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct PostState_thermostat_mt_mmm_mmm {
    pub lastMonitorMode: Isolette_Data_Model::Monitor_Mode,
    pub api_monitor_mode: Isolette_Data_Model::Monitor_Mode,
  }

}
