// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_read_port1: Option<u8>,
  pub api_read_port2: Option<u8>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_read_port1(container.api_read_port1);
  put_read_port2(container.api_read_port2);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  read_port1: Option<u8>,
  read_port2: Option<u8>)
{
  put_read_port1(read_port1);
  put_read_port2(read_port2);
}

/// setter for IN EventPort
pub fn put_read_port1(value: Option<u8>)
{
  *extern_api::IN_read_port1.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventPort
pub fn put_read_port2(value: Option<u8>)
{
  *extern_api::IN_read_port2.lock().unwrap_or_else(|e| e.into_inner()) = value
}
