// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;
use vstd::prelude::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct PreState_producer_producer {
  }

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct PostState_producer_producer {
    pub api_p_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
    pub api_p_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
    pub api_p_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>,
    pub api_p_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
    pub api_p_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
    pub api_p_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  }

}
