#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <test_scheduler.scheduler_config.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// The metaprogram emits a binary with the same format as this struct, which is
// patched into the scheduler's ELF at system build time.  sdfgen_helper.py parses
// this file (and only this file) to build the matching Python serializer, so any
// struct it must serialize has to be declared here rather than in
// test_scheduler.scheduler_config.h.

typedef struct user_schedule {
    uint64_t timeslices[MAX_SCHEDULE_SLOTS];
    uint32_t timeslice_ch[MAX_SCHEDULE_SLOTS];
    bool is_user_partition[MAX_SCHEDULE_SLOTS];
    uint32_t num_timeslices;
} user_schedule_t;