export MICROKIT_SDK := "/home/robertvanvossen/dev/collins/provers/microkit/sdk/microkit-source/release/microkit-sdk-1.4.1"
export MICROKIT_BOARD := "zcu102"
export MICROKIT_CONFIG := "debug"
export SYSTEM_MAKEFILE := "custom.mk"

build:
    make

verus:
    make verus

test:
    make test

clean:
    make clean

send:
    scp build/loader.img hardware-test:/home/gitlab-runner/tftp_root/boot_files/zynqmp/loader.img
