// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait consumer_consumer_Api {}

  pub trait consumer_consumer_Put_Api: consumer_consumer_Api {
  }

  pub trait consumer_consumer_Get_Api: consumer_consumer_Api {
    #[verifier::external_body]
    fn unverified_get_myStructArray(
      &mut self,
      value: &Ghost<Option<Gumbo_Structs_Arrays::MyStructArray_i>>) -> (res : Option<Gumbo_Structs_Arrays::MyStructArray_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myStructArray();
    }

    #[verifier::external_body]
    fn unverified_get_MyArrayStruct(
      &mut self,
      value: &Ghost<Option<Gumbo_Structs_Arrays::MyArrayStruct>>) -> (res : Option<Gumbo_Structs_Arrays::MyArrayStruct>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_MyArrayStruct();
    }

    #[verifier::external_body]
    fn unverified_get_MyArrayInt32(
      &mut self,
      value: &Ghost<Option<Gumbo_Structs_Arrays::MyArrayInt32>>) -> (res : Option<Gumbo_Structs_Arrays::MyArrayInt32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_MyArrayInt32();
    }
  }

  pub trait consumer_consumer_Full_Api: consumer_consumer_Put_Api + consumer_consumer_Get_Api {}

  pub struct consumer_consumer_Application_Api<API: consumer_consumer_Api> {
    pub api: API,

    pub ghost myStructArray: Option<Gumbo_Structs_Arrays::MyStructArray_i>,
    pub ghost MyArrayStruct: Option<Gumbo_Structs_Arrays::MyArrayStruct>,
    pub ghost MyArrayInt32: Option<Gumbo_Structs_Arrays::MyArrayInt32>
  }

  impl<API: consumer_consumer_Put_Api> consumer_consumer_Application_Api<API> {
  }

  impl<API: consumer_consumer_Get_Api> consumer_consumer_Application_Api<API> {
    pub fn get_myStructArray(&mut self) -> (res : Option<Gumbo_Structs_Arrays::MyStructArray_i>)
      ensures
        old(self).myStructArray == self.myStructArray,
        res == self.myStructArray,
        old(self).MyArrayStruct == self.MyArrayStruct,
        old(self).MyArrayInt32 == self.MyArrayInt32,
    {
      self.api.unverified_get_myStructArray(&Ghost(self.myStructArray))
    }
    pub fn get_MyArrayStruct(&mut self) -> (res : Option<Gumbo_Structs_Arrays::MyArrayStruct>)
      ensures
        old(self).myStructArray == self.myStructArray,
        old(self).MyArrayStruct == self.MyArrayStruct,
        res == self.MyArrayStruct,
        old(self).MyArrayInt32 == self.MyArrayInt32,
    {
      self.api.unverified_get_MyArrayStruct(&Ghost(self.MyArrayStruct))
    }
    pub fn get_MyArrayInt32(&mut self) -> (res : Option<Gumbo_Structs_Arrays::MyArrayInt32>)
      ensures
        old(self).myStructArray == self.myStructArray,
        old(self).MyArrayStruct == self.MyArrayStruct,
        old(self).MyArrayInt32 == self.MyArrayInt32,
        res == self.MyArrayInt32,
    {
      self.api.unverified_get_MyArrayInt32(&Ghost(self.MyArrayInt32))
    }
  }

  pub struct consumer_consumer_Initialization_Api;
  impl consumer_consumer_Api for consumer_consumer_Initialization_Api {}
  impl consumer_consumer_Put_Api for consumer_consumer_Initialization_Api {}

  pub const fn init_api() -> consumer_consumer_Application_Api<consumer_consumer_Initialization_Api> {
    return consumer_consumer_Application_Api {
      api: consumer_consumer_Initialization_Api {},

      myStructArray: None,
      MyArrayStruct: None,
      MyArrayInt32: None
    }
  }

  pub struct consumer_consumer_Compute_Api;
  impl consumer_consumer_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Put_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Get_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Full_Api for consumer_consumer_Compute_Api {}

  pub const fn compute_api() -> consumer_consumer_Application_Api<consumer_consumer_Compute_Api> {
    return consumer_consumer_Application_Api {
      api: consumer_consumer_Compute_Api {},

      myStructArray: None,
      MyArrayStruct: None,
      MyArrayInt32: None
    }
  }
}