#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool fanCmd_is_empty(void);
bool get_fanCmd_poll(sb_event_counter_t *numDropped, TempControl_SysVerif_FanCmd *data);
bool get_fanCmd(TempControl_SysVerif_FanCmd *data);
bool put_fanAck(const TempControl_SysVerif_FanAck *data);
