// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_producer_p_p_producer_write_port(value: *mut vest_1prod_1cons::ArrayOfByte) -> bool;
  fn get_sched_state(value: *mut hamr::SchedState) -> bool;
  fn get_sched_schedule(value: *mut hamr::Schedule) -> bool;
}

pub fn unsafe_get_producer_p_p_producer_write_port() -> vest_1prod_1cons::ArrayOfByte
{
  unsafe {
    let value: *mut vest_1prod_1cons::ArrayOfByte = &mut [0; vest_1prod_1cons::vest_1prod_1cons_ArrayOfByte_DIM_0];
    get_producer_p_p_producer_write_port(value);
    return *value;
  }
}

pub fn unsafe_get_sched_state() -> hamr::SchedState
{
  unsafe {
    let value: *mut hamr::SchedState = &mut hamr::SchedState::default();
    get_sched_state(value);
    return *value;
  }
}

pub fn unsafe_get_sched_schedule() -> hamr::Schedule
{
  unsafe {
    let value: *mut hamr::Schedule = &mut hamr::Schedule::default();
    get_sched_schedule(value);
    return *value;
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_producer_p_p_producer_write_port: Mutex<Option<vest_1prod_1cons::ArrayOfByte>> = Mutex::new(None);
  pub static ref IN_sched_state: Mutex<Option<hamr::SchedState>> = Mutex::new(None);
  pub static ref IN_sched_schedule: Mutex<Option<hamr::Schedule>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_producer_p_p_producer_write_port.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_sched_state.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_sched_schedule.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_producer_p_p_producer_write_port(value: *mut vest_1prod_1cons::ArrayOfByte) -> bool
{
  unsafe {
    let guard = IN_producer_p_p_producer_write_port.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_sched_state(value: *mut hamr::SchedState) -> bool
{
  unsafe {
    let guard = IN_sched_state.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_sched_schedule(value: *mut hamr::Schedule) -> bool
{
  unsafe {
    let guard = IN_sched_schedule.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}
