#include "monitor_process_monitor_thread.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void monitor_process_monitor_thread_initialize(void);
void monitor_process_monitor_thread_notify(microkit_channel channel);
void monitor_process_monitor_thread_timeTriggered(void);

volatile sb_queue_int32_t_1_t *p1_t1_write_port_queue_1;
sb_queue_int32_t_1_Recv_t p1_t1_write_port_recv_queue;
volatile sb_queue_int32_t_1_t *p2_t2_write_port_queue_1;
sb_queue_int32_t_1_Recv_t p2_t2_write_port_recv_queue;

#define PORT_FROM_MON 54

int32_t last_p1_t1_write_port_payload;

bool get_p1_t1_write_port(int32_t *data) {
  sb_event_counter_t numDropped;
  int32_t fresh_data;
  bool isFresh = sb_queue_int32_t_1_dequeue((sb_queue_int32_t_1_Recv_t *) &p1_t1_write_port_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_p1_t1_write_port_payload = fresh_data;
  }
  *data = last_p1_t1_write_port_payload;
  return isFresh;
}

int32_t last_p2_t2_write_port_payload;

bool get_p2_t2_write_port(int32_t *data) {
  sb_event_counter_t numDropped;
  int32_t fresh_data;
  bool isFresh = sb_queue_int32_t_1_dequeue((sb_queue_int32_t_1_Recv_t *) &p2_t2_write_port_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_p2_t2_write_port_payload = fresh_data;
  }
  *data = last_p2_t2_write_port_payload;
  return isFresh;
}

void init(void) {
  sb_queue_int32_t_1_Recv_init(&p1_t1_write_port_recv_queue, (sb_queue_int32_t_1_t *) p1_t1_write_port_queue_1);

  sb_queue_int32_t_1_Recv_init(&p2_t2_write_port_recv_queue, (sb_queue_int32_t_1_t *) p2_t2_write_port_queue_1);

  monitor_process_monitor_thread_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      monitor_process_monitor_thread_timeTriggered();
      break;
    default:
      monitor_process_monitor_thread_notify(channel);
  }
}
