// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * assumes B_Input_Range
  *   B input range
  * @param api_Input incoming data port
  */
pub fn compute_spec_B_Input_Range_assume(api_Input: i32) -> bool
{
  api_Input < 20i32
}

/** CEP-T-Assm: Top-level assume contracts for b's compute entrypoint
  *
  * @param api_Input incoming data port
  */
pub fn compute_CEP_T_Assm(api_Input: i32) -> bool
{
  let r0: bool = compute_spec_B_Input_Range_assume(api_Input);

  return r0;
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for b
  *
  * @param api_Input incoming data port
  */
pub fn compute_CEP_Pre(api_Input: i32) -> bool
{
  // CEP-Assm: assume clauses of b's compute entrypoint
  let r0: bool = compute_CEP_T_Assm(api_Input);

  return r0;
}

/** Compute Entrypoint Contract
  *
  * guarantee B_Output_Range
  *   B output range
  * @param api_Input incoming data port
  * @param api_Output outgoing data port
  */
pub fn compute_spec_B_Output_Range_guarantee(
  api_Input: i32,
  api_Output: i32) -> bool
{
  api_Output < api_Input + 15i32
}

/** CEP-T-Guar: Top-level guarantee contracts for b's compute entrypoint
  *
  * @param api_Input incoming data port
  * @param api_Output outgoing data port
  */
pub fn compute_CEP_T_Guar(
  api_Input: i32,
  api_Output: i32) -> bool
{
  let r0: bool = compute_spec_B_Output_Range_guarantee(api_Input, api_Output);

  return r0;
}

/** CEP-Post: Compute Entrypoint Post-Condition for b
  *
  * @param api_Input incoming data port
  * @param api_Output outgoing data port
  */
pub fn compute_CEP_Post(
  api_Input: i32,
  api_Output: i32) -> bool
{
  // CEP-Guar: guarantee clauses of b's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_Input, api_Output);

  return r0;
}
