# Do not edit this file as it will be overwritten if HAMR codegen is rerun

# Test scheduler configuration.
# Usage: make CONFIG=test_scheduler.mk
export MSD := $(TOP_DIR)/test_scheduler.meta.py
export SCHEDULER_C := $(TOP_DIR)/scheduler/src/test_scheduler.scheduler.c
export SCHEDULER_CONFIG_HEADERS := $(TOP_DIR)/scheduler/include/test_scheduler.user_config.h