# Set the static memory allocated for R2U2 (run `$ cargo clean` if these values are changed)
[env]
R2U2_MAX_OUTPUT_VERDICTS = { value = "64", force = true }
R2U2_MAX_SPECS = { value = "32", force = true}
R2U2_MAX_SIGNALS = { value = "64", force = true }
R2U2_MAX_ATOMICS = { value = "64", force = true }
R2U2_MAX_BZ_INSTRUCTIONS = { value = "64", force = true }
R2U2_MAX_TL_INSTRUCTIONS = { value = "64", force = true }
R2U2_TOTAL_QUEUE_SLOTS = { value = "64", force = true }