// #Sireum

package base.Gumbo_Structs_Arrays

import org.sireum._
import art.Art
import base._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait ConsumerThr_i_consumer_consumer_TestApi {

  def BeforeEntrypoint(): Unit = {
    Art.initTest(Arch.Sys_i_Instance_consumer_consumer)
  }

  def AfterEntrypoint(): Unit = {
    Art.finalizeTest(Arch.Sys_i_Instance_consumer_consumer)
  }

  def testCompute(): Unit = {
    Art.manuallyClearOutput()
    Art.testCompute(Arch.Sys_i_Instance_consumer_consumer)
  }

  def testInitialise(): Unit = {
    Art.manuallyClearOutput()
    Art.testInitialise(Arch.Sys_i_Instance_consumer_consumer)
  }

  /** helper function to set the values of all input ports.
   * @param myStructArray payloads for event data port myStructArray.
   *   ART currently supports single element event data queues so
   *   only the last element of myStructArray will be used
   * @param MyArrayStruct payloads for event data port MyArrayStruct.
   *   ART currently supports single element event data queues so
   *   only the last element of MyArrayStruct will be used
   * @param MyArrayInt32 payloads for event data port MyArrayInt32.
   *   ART currently supports single element event data queues so
   *   only the last element of MyArrayInt32 will be used
   */
  def put_concrete_inputs(myStructArray : ISZ[Gumbo_Structs_Arrays.MyStructArray_i],
                          MyArrayStruct : ISZ[Gumbo_Structs_Arrays.MyArrayStruct],
                          MyArrayInt32 : ISZ[Gumbo_Structs_Arrays.MyArrayInt32]): Unit = {
    for(v <- myStructArray){
      put_myStructArray(v)
    }
    for(v <- MyArrayStruct){
      put_MyArrayStruct(v)
    }
    for(v <- MyArrayInt32){
      put_MyArrayInt32(v)
    }
  }


  // setter for in EventDataPort
  def put_myStructArray(value : Gumbo_Structs_Arrays.MyStructArray_i): Unit = {
    Art.insertInInfrastructurePort(Arch.Sys_i_Instance_consumer_consumer.operational_api.myStructArray_Id, Gumbo_Structs_Arrays.MyStructArray_i_Payload(value))
  }

  // setter for in EventDataPort
  def put_MyArrayStruct(value : Gumbo_Structs_Arrays.MyArrayStruct): Unit = {
    Art.insertInInfrastructurePort(Arch.Sys_i_Instance_consumer_consumer.operational_api.MyArrayStruct_Id, Gumbo_Structs_Arrays.MyArrayStruct_Payload(value))
  }

  // setter for in EventDataPort
  def put_MyArrayInt32(value : Gumbo_Structs_Arrays.MyArrayInt32): Unit = {
    Art.insertInInfrastructurePort(Arch.Sys_i_Instance_consumer_consumer.operational_api.MyArrayInt32_Id, Gumbo_Structs_Arrays.MyArrayInt32_Payload(value))
  }

}
