// #Sireum

package base.Gumbo_Structs_Arrays

import org.sireum._
import art._
import base.SystemTestSuiteSlang.runtimeMonitorStream
import base._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object ProducerThr_i_producer_producer_SystemTestAPI {
  /** helper method to set the values of all incoming ports
    */
  def put_concrete_inputs(): Unit = {
  }



  def fetchContainer(): base.Gumbo_Structs_Arrays.ProducerThr_i_producer_producer_PostState_Container_PS = {
    if (runtimeMonitorStream.contains(Arch.Sys_i_Instance_producer_producer.id)) {
      val (_, postContainer_) = runtimeMonitorStream.get(Arch.Sys_i_Instance_producer_producer.id).get
      return postContainer_.asInstanceOf[base.Gumbo_Structs_Arrays.ProducerThr_i_producer_producer_PostState_Container_PS]
    }
    else {
      assert(F, s"No post state recorded for ${Arch.Sys_i_Instance_producer_producer.name}")
      halt(s"No post state recorded for ${Arch.Sys_i_Instance_producer_producer.name}")
    }
  }

  def check_concrete_outputs(api_MyArrayStruct: Option[Gumbo_Structs_Arrays.MyArrayStruct],
                             api_myStructArray: Option[Gumbo_Structs_Arrays.MyStructArray_i]): Unit = {
    var failureReasons: ISZ[ST] = ISZ()

    val actual_MyArrayStruct = get_api_MyArrayStruct()
    if (api_MyArrayStruct != actual_MyArrayStruct) {
      failureReasons = failureReasons :+ st"'MyArrayStruct' did not match expected.  Expected: $api_MyArrayStruct, Actual: $actual_MyArrayStruct"
    }
    val actual_myStructArray = get_api_myStructArray()
    if (api_myStructArray != actual_myStructArray) {
      failureReasons = failureReasons :+ st"'myStructArray' did not match expected.  Expected: $api_myStructArray, Actual: $actual_myStructArray"
    }

    assert(failureReasons.isEmpty, st"${(failureReasons, "\n")}".render)
  }

  def get_api_MyArrayStruct(): Option[Gumbo_Structs_Arrays.MyArrayStruct] = {
    return fetchContainer().api_MyArrayStruct
  }

  def get_api_myStructArray(): Option[Gumbo_Structs_Arrays.MyStructArray_i] = {
    return fetchContainer().api_myStructArray
  }
}