// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on tst's outgoing event data port currentTemp
  *
  * guarantee Sensor_Temperature_Range
  */
pub fn I_Guar_currentTemp(currentTemp: TempControl_SysVerif::Temperature) -> bool
{
  (currentTemp.degrees >= -40i32) &
    (currentTemp.degrees <= 122i32)
}

/** I-Guar: Integration constraint on tst's outgoing event data port currentTemp
  *
  * guarantee Sensor_Temperature_Range
  */
pub fn I_Guar_Guard_currentTemp(currentTemp: Option<TempControl_SysVerif::Temperature>) -> bool
{
  implies!(
    currentTemp.is_some(),
    I_Guar_currentTemp(currentTemp.unwrap())
  )
}

/** Initialize EntryPointContract
  *
  * guarantee initializes
  * @param api_currentTemp outgoing event data port
  */
pub fn initialize_initializes(api_currentTemp: Option<TempControl_SysVerif::Temperature>) -> bool
{
  api_currentTemp.unwrap().degrees == 72i32
}

/** IEP-Guar: Initialize Entrypoint for tst
  *
  * @param api_currentTemp outgoing event data port
  */
pub fn initialize_IEP_Guar(api_currentTemp: Option<TempControl_SysVerif::Temperature>) -> bool
{
  initialize_initializes(api_currentTemp)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_currentTemp outgoing event data port
  */
pub fn initialize_IEP_Post(api_currentTemp: Option<TempControl_SysVerif::Temperature>) -> bool
{
  // I-Guar-Guard: Integration constraints for tst's outgoing ports"
  I_Guar_Guard_currentTemp(api_currentTemp)&& 

  initialize_IEP_Guar(api_currentTemp)
}

/** CEP-Post: Compute Entrypoint Post-Condition for tst
  *
  * @param api_currentTemp outgoing event data port
  */
pub fn compute_CEP_Post(api_currentTemp: Option<TempControl_SysVerif::Temperature>) -> bool
{
  // I-Guar-Guard: Integration constraints for tst's outgoing ports
  let r0: bool = I_Guar_Guard_currentTemp(api_currentTemp);

  return r0;
}
