// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct struct_i {
    pub size: i32,
    pub elements: ArrayOfInts
  }

  impl Default for struct_i {
    fn default() -> Self
    {
      Self { size: 0, elements: [0; event_data_2_prod_2_cons_struct::event_data_2_prod_2_cons_struct_ArrayOfInts_DIM_0] }
    }
  }
}