// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn put_level(value: *mut i32) -> bool;
  fn put_boolean_value(value: *mut bool) -> bool;
  fn put_character_value(value: *mut u8) -> bool;
  fn put_signed_8_value(value: *mut i8) -> bool;
  fn put_signed_16_value(value: *mut i16) -> bool;
  fn put_unsigned_8_value(value: *mut u8) -> bool;
  fn put_unsigned_16_value(value: *mut u16) -> bool;
  fn put_sample(value: *mut i32) -> bool;
  fn put_flag(value: *mut bool) -> bool;
  fn put_operating_state(value: *mut Exhaustive_Monitor::OperatingState) -> bool;
  fn put_samples(value: *mut Exhaustive_Monitor::Samples) -> bool;
  fn put_telemetry(value: *mut Exhaustive_Monitor::Telemetry_i) -> bool;
  fn put_pulse() -> bool;
}

pub fn unsafe_put_level(value: &i32) -> bool
{
  unsafe {
    return put_level(value as *const i32 as *mut i32);
  }
}

pub fn unsafe_put_boolean_value(value: &bool) -> bool
{
  unsafe {
    return put_boolean_value(value as *const bool as *mut bool);
  }
}

pub fn unsafe_put_character_value(value: &u8) -> bool
{
  unsafe {
    return put_character_value(value as *const u8 as *mut u8);
  }
}

pub fn unsafe_put_signed_8_value(value: &i8) -> bool
{
  unsafe {
    return put_signed_8_value(value as *const i8 as *mut i8);
  }
}

pub fn unsafe_put_signed_16_value(value: &i16) -> bool
{
  unsafe {
    return put_signed_16_value(value as *const i16 as *mut i16);
  }
}

pub fn unsafe_put_unsigned_8_value(value: &u8) -> bool
{
  unsafe {
    return put_unsigned_8_value(value as *const u8 as *mut u8);
  }
}

pub fn unsafe_put_unsigned_16_value(value: &u16) -> bool
{
  unsafe {
    return put_unsigned_16_value(value as *const u16 as *mut u16);
  }
}

pub fn unsafe_put_sample(value: &i32) -> bool
{
  unsafe {
    return put_sample(value as *const i32 as *mut i32);
  }
}

pub fn unsafe_put_flag(value: &bool) -> bool
{
  unsafe {
    return put_flag(value as *const bool as *mut bool);
  }
}

pub fn unsafe_put_operating_state(value: &Exhaustive_Monitor::OperatingState) -> bool
{
  unsafe {
    return put_operating_state(value as *const Exhaustive_Monitor::OperatingState as *mut Exhaustive_Monitor::OperatingState);
  }
}

pub fn unsafe_put_samples(value: &Exhaustive_Monitor::Samples) -> bool
{
  unsafe {
    return put_samples(value as *const Exhaustive_Monitor::Samples as *mut Exhaustive_Monitor::Samples);
  }
}

pub fn unsafe_put_telemetry(value: &Exhaustive_Monitor::Telemetry_i) -> bool
{
  unsafe {
    return put_telemetry(value as *const Exhaustive_Monitor::Telemetry_i as *mut Exhaustive_Monitor::Telemetry_i);
  }
}

pub fn unsafe_put_pulse() -> bool
{
  unsafe {
    return put_pulse();
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref OUT_level: Mutex<Option<i32>> = Mutex::new(None);
  pub static ref OUT_boolean_value: Mutex<Option<bool>> = Mutex::new(None);
  pub static ref OUT_character_value: Mutex<Option<u8>> = Mutex::new(None);
  pub static ref OUT_signed_8_value: Mutex<Option<i8>> = Mutex::new(None);
  pub static ref OUT_signed_16_value: Mutex<Option<i16>> = Mutex::new(None);
  pub static ref OUT_unsigned_8_value: Mutex<Option<u8>> = Mutex::new(None);
  pub static ref OUT_unsigned_16_value: Mutex<Option<u16>> = Mutex::new(None);
  pub static ref OUT_sample: Mutex<Option<i32>> = Mutex::new(None);
  pub static ref OUT_flag: Mutex<Option<bool>> = Mutex::new(None);
  pub static ref OUT_operating_state: Mutex<Option<Exhaustive_Monitor::OperatingState>> = Mutex::new(None);
  pub static ref OUT_samples: Mutex<Option<Exhaustive_Monitor::Samples>> = Mutex::new(None);
  pub static ref OUT_telemetry: Mutex<Option<Exhaustive_Monitor::Telemetry_i>> = Mutex::new(None);
  pub static ref OUT_pulse: Mutex<Option<u8>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *OUT_level.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_boolean_value.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_character_value.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_signed_8_value.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_signed_16_value.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_unsigned_8_value.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_unsigned_16_value.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_sample.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_flag.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_operating_state.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_samples.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_telemetry.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_pulse.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn put_level(value: *mut i32) -> bool
{
  unsafe {
    *OUT_level.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_boolean_value(value: *mut bool) -> bool
{
  unsafe {
    *OUT_boolean_value.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_character_value(value: *mut u8) -> bool
{
  unsafe {
    *OUT_character_value.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_signed_8_value(value: *mut i8) -> bool
{
  unsafe {
    *OUT_signed_8_value.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_signed_16_value(value: *mut i16) -> bool
{
  unsafe {
    *OUT_signed_16_value.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_unsigned_8_value(value: *mut u8) -> bool
{
  unsafe {
    *OUT_unsigned_8_value.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_unsigned_16_value(value: *mut u16) -> bool
{
  unsafe {
    *OUT_unsigned_16_value.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_sample(value: *mut i32) -> bool
{
  unsafe {
    *OUT_sample.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_flag(value: *mut bool) -> bool
{
  unsafe {
    *OUT_flag.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_operating_state(value: *mut Exhaustive_Monitor::OperatingState) -> bool
{
  unsafe {
    *OUT_operating_state.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_samples(value: *mut Exhaustive_Monitor::Samples) -> bool
{
  unsafe {
    *OUT_samples.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_telemetry(value: *mut Exhaustive_Monitor::Telemetry_i) -> bool
{
  unsafe {
    *OUT_telemetry.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_pulse() -> bool
{
  unsafe {
    *OUT_pulse.lock().unwrap_or_else(|e| e.into_inner()) = Some(0u8);
    return true;
  }
}
