// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

#[cfg(test)]
pub fn get_EthernetFramesTx() -> Option<SW::RawEthernetMessage> 
 {
   return extern_api::OUT_EthernetFramesTx.lock().unwrap().clone()
 }

#[cfg(test)]
pub fn put_EthernetFramesRx(value: SW::RawEthernetMessage) 
 {
   *extern_api::IN_EthernetFramesRx.lock().unwrap() = Some(value)
 }