// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct struct_i {
    pub currentEvent: i32,
    pub totalEventsSent: i32,
  }

  impl Default for struct_i {
    fn default() -> Self
    {
      Self { currentEvent: 0, totalEventsSent: 0 }
    }
  }

}

// Memory layout as HAMR computes it
const _: () = assert!(core::mem::size_of::<struct_i>() == 8);
const _: () = assert!(core::mem::align_of::<struct_i>() == 4);
const _: () = assert!(core::mem::offset_of!(struct_i, currentEvent) == 0);
const _: () = assert!(core::mem::offset_of!(struct_i, totalEventsSent) == 4);