// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_in_val(value: *mut i32) -> bool;
  fn get_evt() -> bool;
}

pub fn unsafe_get_in_val() -> i32
{
  unsafe {
    let value: *mut i32 = &mut 0;
    get_in_val(value);
    return *value;
  }
}

pub fn unsafe_get_evt() -> bool
{
  unsafe {
    return get_evt();
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_in_val: Mutex<Option<i32>> = Mutex::new(None);
  pub static ref IN_evt: Mutex<Option<u8>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_in_val.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_evt.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_in_val(value: *mut i32) -> bool
{
  unsafe {
    let guard = IN_in_val.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_evt() -> bool
{
  unsafe {
    match *IN_evt.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        return true;
      },
      None => return false,
    }
  }
}
