// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Place-assertion spec functions of property `internal_failure_heat_off` -- one per
//! point its decoration binds (unbound points carry `true`, design D5).

#![allow(non_snake_case)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::assertions::*;
use crate::system_state::SystemState;

verus! {

/** property internal_failure_heat_off, bound 'after oi' (place after_oi)
  */
pub open spec fn sys_assert_internal_failure_heat_off_after_oi(st: SystemState) -> bool
{
  sysProp_lower_is_not_higher_than_upper(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus)
}

/** property internal_failure_heat_off, bound 'at ts_oi_done' (place post_join_1)
  */
pub open spec fn sys_assert_internal_failure_heat_off_post_join_1(st: SystemState) -> bool
{
  sysProp_lower_is_not_higher_than_upper(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus)
}

/** property internal_failure_heat_off, bound 'before drf' (place before_drf)
  */
pub open spec fn sys_assert_internal_failure_heat_off_before_drf(st: SystemState) -> bool
{
  sysProp_lower_is_not_higher_than_upper(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus)
}

/** property internal_failure_heat_off, bound 'after drf' (place after_drf)
  */
pub open spec fn sys_assert_internal_failure_heat_off_after_drf(st: SystemState) -> bool
{
  sysProp_lower_is_not_higher_than_upper(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus)
}

/** property internal_failure_heat_off, bound 'after mri' (place after_mri)
  */
pub open spec fn sys_assert_internal_failure_heat_off_after_mri(st: SystemState) -> bool
{
  (sysProp_REQ_MRI_7(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus, st.reg_interface_failure) && sysProp_REQ_MRI_8(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus, st.lower_desired_temp, st.upper_desired_temp, st.reg_interface_failure)) &&
    sysProp_lower_is_lower_temp(st.lower_desired_temp, st.upper_desired_temp)
}

/** property internal_failure_heat_off, bound 'after mrm' (place after_mrm)
  *   internal failure keeps mode out of Normal (REQ_MRM_3 / Maintain_Init)
  */
pub open spec fn sys_assert_internal_failure_heat_off_after_mrm(st: SystemState) -> bool
{
  ((sysProp_REQ_MRI_7(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus, st.reg_interface_failure) && sysProp_REQ_MRI_8(st.lower_desired_tempWstatus, st.upper_desired_tempWstatus, st.lower_desired_temp, st.upper_desired_temp, st.reg_interface_failure)) &&
    sysProp_lower_is_lower_temp(st.lower_desired_temp, st.upper_desired_temp)) &&
    sysProp_InternalFailureImpliesRegulatorNotNormal(st.internal_failure, st.regulator_mode)
}

/** property internal_failure_heat_off, bound 'after mhs' (place after_mhs)
  */
pub open spec fn sys_assert_internal_failure_heat_off_after_mhs(st: SystemState) -> bool
{
  sysProp_InternalFailureHeatOff(st.internal_failure, st.heat_control)
}

} // verus!
