#include "consumer_consumer.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void consumer_consumer_initialize(void);
void consumer_consumer_notify(microkit_channel channel);
void consumer_consumer_timeTriggered(void);

volatile sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_t *myArrayInt32_DataPort_queue_1;
sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_Recv_t myArrayInt32_DataPort_recv_queue;
volatile sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_t *myStructArray_EventDataPort_queue_1;
sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_Recv_t myStructArray_EventDataPort_recv_queue;
volatile sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_t *myArrayStruct_EventDataPort_queue_1;
sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_Recv_t myArrayStruct_EventDataPort_recv_queue;
volatile sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_t *myArrayStruct_DataPort_queue_1;
sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_Recv_t myArrayStruct_DataPort_recv_queue;
volatile sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_t *myStructArray_DataPort_queue_1;
sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_Recv_t myStructArray_DataPort_recv_queue;
volatile sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_t *myArrayInt32_EventDataPort_queue_1;
sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_Recv_t myArrayInt32_EventDataPort_recv_queue;

#define PORT_FROM_MON 58

Gubmo_Structs_Arrays_MyArrayInt32 last_myArrayInt32_DataPort_payload;

bool get_myArrayInt32_DataPort(Gubmo_Structs_Arrays_MyArrayInt32 *data) {
  sb_event_counter_t numDropped;
  Gubmo_Structs_Arrays_MyArrayInt32 fresh_data;
  bool isFresh = sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_dequeue((sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_Recv_t *) &myArrayInt32_DataPort_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    memcpy(&last_myArrayInt32_DataPort_payload, &fresh_data, Gubmo_Structs_Arrays_MyArrayInt32_BYTE_SIZE);
  }
  memcpy(data, &last_myArrayInt32_DataPort_payload, Gubmo_Structs_Arrays_MyArrayInt32_BYTE_SIZE);
  return isFresh;
}

bool myStructArray_EventDataPort_is_empty(void) {
  return sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_is_empty(&myStructArray_EventDataPort_recv_queue);
}

bool get_myStructArray_EventDataPort_poll(sb_event_counter_t *numDropped, Gubmo_Structs_Arrays_MyStructArray_i *data) {
  return sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_dequeue((sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_Recv_t *) &myStructArray_EventDataPort_recv_queue, numDropped, data);
}

bool get_myStructArray_EventDataPort(Gubmo_Structs_Arrays_MyStructArray_i *data) {
  sb_event_counter_t numDropped;
  return get_myStructArray_EventDataPort_poll (&numDropped, data);
}

bool myArrayStruct_EventDataPort_is_empty(void) {
  return sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_is_empty(&myArrayStruct_EventDataPort_recv_queue);
}

bool get_myArrayStruct_EventDataPort_poll(sb_event_counter_t *numDropped, Gubmo_Structs_Arrays_MyArrayStruct *data) {
  return sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_dequeue((sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_Recv_t *) &myArrayStruct_EventDataPort_recv_queue, numDropped, data);
}

bool get_myArrayStruct_EventDataPort(Gubmo_Structs_Arrays_MyArrayStruct *data) {
  sb_event_counter_t numDropped;
  return get_myArrayStruct_EventDataPort_poll (&numDropped, data);
}

Gubmo_Structs_Arrays_MyArrayStruct last_myArrayStruct_DataPort_payload;

bool get_myArrayStruct_DataPort(Gubmo_Structs_Arrays_MyArrayStruct *data) {
  sb_event_counter_t numDropped;
  Gubmo_Structs_Arrays_MyArrayStruct fresh_data;
  bool isFresh = sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_dequeue((sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_Recv_t *) &myArrayStruct_DataPort_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    memcpy(&last_myArrayStruct_DataPort_payload, &fresh_data, Gubmo_Structs_Arrays_MyArrayStruct_BYTE_SIZE);
  }
  memcpy(data, &last_myArrayStruct_DataPort_payload, Gubmo_Structs_Arrays_MyArrayStruct_BYTE_SIZE);
  return isFresh;
}

Gubmo_Structs_Arrays_MyStructArray_i last_myStructArray_DataPort_payload;

bool get_myStructArray_DataPort(Gubmo_Structs_Arrays_MyStructArray_i *data) {
  sb_event_counter_t numDropped;
  Gubmo_Structs_Arrays_MyStructArray_i fresh_data;
  bool isFresh = sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_dequeue((sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_Recv_t *) &myStructArray_DataPort_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_myStructArray_DataPort_payload = fresh_data;
  }
  *data = last_myStructArray_DataPort_payload;
  return isFresh;
}

bool myArrayInt32_EventDataPort_is_empty(void) {
  return sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_is_empty(&myArrayInt32_EventDataPort_recv_queue);
}

bool get_myArrayInt32_EventDataPort_poll(sb_event_counter_t *numDropped, Gubmo_Structs_Arrays_MyArrayInt32 *data) {
  return sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_dequeue((sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_Recv_t *) &myArrayInt32_EventDataPort_recv_queue, numDropped, data);
}

bool get_myArrayInt32_EventDataPort(Gubmo_Structs_Arrays_MyArrayInt32 *data) {
  sb_event_counter_t numDropped;
  return get_myArrayInt32_EventDataPort_poll (&numDropped, data);
}

void init(void) {
  sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_Recv_init(&myArrayInt32_DataPort_recv_queue, (sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_t *) myArrayInt32_DataPort_queue_1);

  sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_Recv_init(&myStructArray_EventDataPort_recv_queue, (sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_t *) myStructArray_EventDataPort_queue_1);

  sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_Recv_init(&myArrayStruct_EventDataPort_recv_queue, (sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_t *) myArrayStruct_EventDataPort_queue_1);

  sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_Recv_init(&myArrayStruct_DataPort_recv_queue, (sb_queue_Gubmo_Structs_Arrays_MyArrayStruct_1_t *) myArrayStruct_DataPort_queue_1);

  sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_Recv_init(&myStructArray_DataPort_recv_queue, (sb_queue_Gubmo_Structs_Arrays_MyStructArray_i_1_t *) myStructArray_DataPort_queue_1);

  sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_Recv_init(&myArrayInt32_EventDataPort_recv_queue, (sb_queue_Gubmo_Structs_Arrays_MyArrayInt32_1_t *) myArrayInt32_EventDataPort_queue_1);

  consumer_consumer_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      consumer_consumer_timeTriggered();
      break;
    default:
      consumer_consumer_notify(channel);
  }
}
