// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait monitor_process_monitor_thread_Api {}

  pub trait monitor_process_monitor_thread_Put_Api: monitor_process_monitor_thread_Api {
  }

  pub trait monitor_process_monitor_thread_Get_Api: monitor_process_monitor_thread_Api {
    #[verifier::external_body]
    fn unverified_get_producer_p_p1_producer_write_port(
      &mut self,
      value: &Ghost<Option<i8>>) -> (res : Option<i8>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_producer_p_p1_producer_write_port();
    }

    #[verifier::external_body]
    fn unverified_get_producer_p_p2_producer_write_port(
      &mut self,
      value: &Ghost<Option<i8>>) -> (res : Option<i8>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_producer_p_p2_producer_write_port();
    }
  }

  pub trait monitor_process_monitor_thread_Full_Api: monitor_process_monitor_thread_Put_Api + monitor_process_monitor_thread_Get_Api {}

  pub struct monitor_process_monitor_thread_Application_Api<API: monitor_process_monitor_thread_Api> {
    pub api: API,

    pub ghost producer_p_p1_producer_write_port: Option<i8>,
    pub ghost producer_p_p2_producer_write_port: Option<i8>
  }

  impl<API: monitor_process_monitor_thread_Put_Api> monitor_process_monitor_thread_Application_Api<API> {
  }

  impl<API: monitor_process_monitor_thread_Get_Api> monitor_process_monitor_thread_Application_Api<API> {
    pub fn get_producer_p_p1_producer_write_port(&mut self) -> (res : Option<i8>)
      ensures
        old(self).producer_p_p1_producer_write_port == self.producer_p_p1_producer_write_port,
        res == self.producer_p_p1_producer_write_port,
        old(self).producer_p_p2_producer_write_port == self.producer_p_p2_producer_write_port,
    {
      self.api.unverified_get_producer_p_p1_producer_write_port(&Ghost(self.producer_p_p1_producer_write_port))
    }
    pub fn get_producer_p_p2_producer_write_port(&mut self) -> (res : Option<i8>)
      ensures
        old(self).producer_p_p1_producer_write_port == self.producer_p_p1_producer_write_port,
        old(self).producer_p_p2_producer_write_port == self.producer_p_p2_producer_write_port,
        res == self.producer_p_p2_producer_write_port,
    {
      self.api.unverified_get_producer_p_p2_producer_write_port(&Ghost(self.producer_p_p2_producer_write_port))
    }
  }

  pub struct monitor_process_monitor_thread_Initialization_Api;
  impl monitor_process_monitor_thread_Api for monitor_process_monitor_thread_Initialization_Api {}
  impl monitor_process_monitor_thread_Put_Api for monitor_process_monitor_thread_Initialization_Api {}

  pub const fn init_api() -> monitor_process_monitor_thread_Application_Api<monitor_process_monitor_thread_Initialization_Api> {
    return monitor_process_monitor_thread_Application_Api {
      api: monitor_process_monitor_thread_Initialization_Api {},

      producer_p_p1_producer_write_port: None,
      producer_p_p2_producer_write_port: None
    }
  }

  pub struct monitor_process_monitor_thread_Compute_Api;
  impl monitor_process_monitor_thread_Api for monitor_process_monitor_thread_Compute_Api {}
  impl monitor_process_monitor_thread_Put_Api for monitor_process_monitor_thread_Compute_Api {}
  impl monitor_process_monitor_thread_Get_Api for monitor_process_monitor_thread_Compute_Api {}
  impl monitor_process_monitor_thread_Full_Api for monitor_process_monitor_thread_Compute_Api {}

  pub const fn compute_api() -> monitor_process_monitor_thread_Application_Api<monitor_process_monitor_thread_Compute_Api> {
    return monitor_process_monitor_thread_Application_Api {
      api: monitor_process_monitor_thread_Compute_Api {},

      producer_p_p1_producer_write_port: None,
      producer_p_p2_producer_write_port: None
    }
  }
}