#include <stdint.h>
#include <microkit.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#define PORT_TO_TSP_TST_MON 61
#define PORT_TO_TCP_TCT_MON 59
#define PORT_TO_FP_FT_MON 57
#define PORT_TO_DOMAIN_MONITOR_PROCESS_DOMAIN_MONITOR_THREAD_MON 55

void init(void) {}

void notified(microkit_channel channel) {
  switch(channel) {
    case PORT_TO_TSP_TST_MON:
      microkit_notify(PORT_TO_TSP_TST_MON);
      break;
    case PORT_TO_TCP_TCT_MON:
      microkit_notify(PORT_TO_TCP_TCT_MON);
      break;
    case PORT_TO_FP_FT_MON:
      microkit_notify(PORT_TO_FP_FT_MON);
      break;
    case PORT_TO_DOMAIN_MONITOR_PROCESS_DOMAIN_MONITOR_THREAD_MON:
      microkit_notify(PORT_TO_DOMAIN_MONITOR_PROCESS_DOMAIN_MONITOR_THREAD_MON);
      break;
  }
}
