#pragma once

#if __has_include("libvmm/util/util.h")
#include <libvmm/util/util.h>
#elif __has_include("util.h")
#include <util.h>
#elif __has_include("sddf/util/util.h")
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#endif

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool tsp_tst_currentTemp_is_empty(void);
bool get_tsp_tst_currentTemp_poll(sb_event_counter_t *numDropped, TempControl_SysVerif_Temperature *data);
bool get_tsp_tst_currentTemp(TempControl_SysVerif_Temperature *data);
bool tcp_tct_fanCmd_is_empty(void);
bool get_tcp_tct_fanCmd_poll(sb_event_counter_t *numDropped, TempControl_SysVerif_FanCmd *data);
bool get_tcp_tct_fanCmd(TempControl_SysVerif_FanCmd *data);
bool fp_ft_fanAck_is_empty(void);
bool get_fp_ft_fanAck_poll(sb_event_counter_t *numDropped, TempControl_SysVerif_FanAck *data);
bool get_fp_ft_fanAck(TempControl_SysVerif_FanAck *data);
bool tcp_tct_setPoint_is_empty(void);
bool get_tcp_tct_setPoint_poll(sb_event_counter_t *numDropped, TempControl_SysVerif_SetPoint *data);
bool get_tcp_tct_setPoint(TempControl_SysVerif_SetPoint *data);
bool get_sched_state(hamr_SchedState *data);
bool get_sched_schedule(hamr_Schedule *data);
