#![cfg(test)]

// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

use crate::bridge::operator_interface_oip_oit_GUMBOX as GUMBOX;

pub fn put_display_temperature(value: Isolette_Data_Model::Temp_i)
{
  *extern_api::IN_display_temperature.lock().unwrap() = Some(value)
}

pub fn put_regulator_status(value: Isolette_Data_Model::Status)
{
  *extern_api::IN_regulator_status.lock().unwrap() = Some(value)
}

pub fn put_monitor_status(value: Isolette_Data_Model::Status)
{
  *extern_api::IN_monitor_status.lock().unwrap() = Some(value)
}

pub fn put_alarm_control(value: Isolette_Data_Model::On_Off)
{
  *extern_api::IN_alarm_control.lock().unwrap() = Some(value)
}

pub fn get_lower_desired_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  return extern_api::OUT_lower_desired_tempWstatus.lock().unwrap().expect("Not expecting None")
}

pub fn get_upper_desired_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  return extern_api::OUT_upper_desired_tempWstatus.lock().unwrap().expect("Not expecting None")
}

pub fn get_lower_alarm_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  return extern_api::OUT_lower_alarm_tempWstatus.lock().unwrap().expect("Not expecting None")
}

pub fn get_upper_alarm_tempWstatus() -> Isolette_Data_Model::TempWstatus_i
{
  return extern_api::OUT_upper_alarm_tempWstatus.lock().unwrap().expect("Not expecting None")
}

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn Isolette_Data_Model_ValueStatus_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::ValueStatus>
{
  prop_oneof![
    Just(Isolette_Data_Model::ValueStatus::Valid),
    Just(Isolette_Data_Model::ValueStatus::Invalid)
  ]
}

pub fn Isolette_Data_Model_Regulator_Mode_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Regulator_Mode>
{
  prop_oneof![
    Just(Isolette_Data_Model::Regulator_Mode::Init_Regulator_Mode),
    Just(Isolette_Data_Model::Regulator_Mode::Normal_Regulator_Mode),
    Just(Isolette_Data_Model::Regulator_Mode::Failed_Regulator_Mode)
  ]
}

pub fn Isolette_Data_Model_Status_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Status>
{
  prop_oneof![
    Just(Isolette_Data_Model::Status::Init_Status),
    Just(Isolette_Data_Model::Status::On_Status),
    Just(Isolette_Data_Model::Status::Failed_Status)
  ]
}

pub fn Isolette_Data_Model_On_Off_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::On_Off>
{
  prop_oneof![
    Just(Isolette_Data_Model::On_Off::Onn),
    Just(Isolette_Data_Model::On_Off::Off)
  ]
}

pub fn Isolette_Data_Model_Monitor_Mode_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Monitor_Mode>
{
  prop_oneof![
    Just(Isolette_Data_Model::Monitor_Mode::Init_Monitor_Mode),
    Just(Isolette_Data_Model::Monitor_Mode::Normal_Monitor_Mode),
    Just(Isolette_Data_Model::Monitor_Mode::Failed_Monitor_Mode)
  ]
}

pub fn Isolette_Environment_Heat_strategy_default() -> impl Strategy<Value = Isolette_Environment::Heat>
{
  prop_oneof![
    Just(Isolette_Environment::Heat::Dummy_Head_Enum)
  ]
}

pub fn Isolette_Data_Model_Temp_i_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Temp_i>
{
  Isolette_Data_Model_Temp_i_stategy_cust(
    any::<i32>()
  )
}

pub fn Isolette_Data_Model_Temp_i_stategy_cust<i32_strategy: Strategy<Value = i32>> (degrees_strategy: i32_strategy) -> impl Strategy<Value = Isolette_Data_Model::Temp_i>
{
  (degrees_strategy).prop_map(|(degrees)| {
    Isolette_Data_Model::Temp_i { degrees }
  })
}

pub fn Isolette_Data_Model_PhysicalTemp_i_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::PhysicalTemp_i>
{
  Isolette_Data_Model_PhysicalTemp_i_stategy_cust(
    any::<i32>()
  )
}

pub fn Isolette_Data_Model_PhysicalTemp_i_stategy_cust<i32_strategy: Strategy<Value = i32>> (degrees_strategy: i32_strategy) -> impl Strategy<Value = Isolette_Data_Model::PhysicalTemp_i>
{
  (degrees_strategy).prop_map(|(degrees)| {
    Isolette_Data_Model::PhysicalTemp_i { degrees }
  })
}

pub fn Isolette_Data_Model_TempWstatus_i_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::TempWstatus_i>
{
  Isolette_Data_Model_TempWstatus_i_stategy_cust(
    any::<i32>(),
    Isolette_Data_Model_ValueStatus_strategy_default()
  )
}

pub fn Isolette_Data_Model_TempWstatus_i_stategy_cust
  <i32_strategy: Strategy<Value = i32>, 
   Isolette_Data_Model_ValueStatus_strategy: Strategy<Value = Isolette_Data_Model::ValueStatus>> (
  degrees_strategy: i32_strategy,
  status_strategy: Isolette_Data_Model_ValueStatus_strategy) -> impl Strategy<Value = Isolette_Data_Model::TempWstatus_i>
{
  (degrees_strategy, status_strategy).prop_map(|(degrees, status)| {
    Isolette_Data_Model::TempWstatus_i { degrees, status }
  })
}

pub fn Isolette_Data_Model_Failure_Flag_i_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Failure_Flag_i>
{
  Isolette_Data_Model_Failure_Flag_i_stategy_cust(
    any::<bool>()
  )
}

pub fn Isolette_Data_Model_Failure_Flag_i_stategy_cust<bool_strategy: Strategy<Value = bool>> (flag_strategy: bool_strategy) -> impl Strategy<Value = Isolette_Data_Model::Failure_Flag_i>
{
  (flag_strategy).prop_map(|(flag)| {
    Isolette_Data_Model::Failure_Flag_i { flag }
  })
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> Result<(), TestCaseError>
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::operator_interface_oip_oit_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_lower_alarm_tempWstatus = get_lower_alarm_tempWstatus();
  let api_lower_desired_tempWstatus = get_lower_desired_tempWstatus();
  let api_upper_alarm_tempWstatus = get_upper_alarm_tempWstatus();
  let api_upper_desired_tempWstatus = get_upper_desired_tempWstatus();

  // [CheckPost]: invoke the oracle function
  prop_assert!(
    GUMBOX::initialize_IEP_Post(
      api_lower_alarm_tempWstatus,
      api_lower_desired_tempWstatus,
      api_upper_alarm_tempWstatus,
      api_upper_desired_tempWstatus
    ),
    "Postcondition failed: incorrect output behavior"
  );

  // Return Ok(()) if all assertions pass
  Ok(())
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        $crate::bridge::test_api::testInitializeCB()?;
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_alarm_control incoming data port
  * @param api_display_temperature incoming data port
  * @param api_monitor_status incoming data port
  * @param api_regulator_status incoming data port
  */
pub fn testComputeCB(
  api_alarm_control: Isolette_Data_Model::On_Off,
  api_display_temperature: Isolette_Data_Model::Temp_i,
  api_monitor_status: Isolette_Data_Model::Status,
  api_regulator_status: Isolette_Data_Model::Status) -> Result<(), TestCaseError>
{
  // Initialize the app
  crate::operator_interface_oip_oit_initialize();

  // [PutInPorts]: Set values on the input ports
  put_alarm_control(api_alarm_control);
  put_display_temperature(api_display_temperature);
  put_monitor_status(api_monitor_status);
  put_regulator_status(api_regulator_status);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::operator_interface_oip_oit_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_lower_alarm_tempWstatus = get_lower_alarm_tempWstatus();
  let api_lower_desired_tempWstatus = get_lower_desired_tempWstatus();
  let api_upper_alarm_tempWstatus = get_upper_alarm_tempWstatus();
  let api_upper_desired_tempWstatus = get_upper_desired_tempWstatus();

  // [CheckPost]: invoke the oracle function
  prop_assert!(
    GUMBOX::compute_CEP_Post(
      api_alarm_control,
      api_display_temperature,
      api_monitor_status,
      api_regulator_status,
      api_lower_alarm_tempWstatus,
      api_lower_desired_tempWstatus,
      api_upper_alarm_tempWstatus,
      api_upper_desired_tempWstatus
    ),
    "Postcondition failed: incorrect output behavior"
  );

  // Return Ok(()) if all assertions pass
  Ok(())
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_alarm_control: $api_alarm_control_strat:expr,
    api_display_temperature: $api_display_temperature_strat:expr,
    api_monitor_status: $api_monitor_status_strat:expr,
    api_regulator_status: $api_regulator_status_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_alarm_control, api_display_temperature, api_monitor_status, api_regulator_status)
        in ($api_alarm_control_strat, $api_display_temperature_strat, $api_monitor_status_strat, $api_regulator_status_strat)
      ) {
        $crate::bridge::test_api::testComputeCB(
          api_alarm_control,
          api_display_temperature,
          api_monitor_status,
          api_regulator_status
        )?;
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_alarm_control incoming data port
  * @param api_display_temperature incoming data port
  * @param api_monitor_status incoming data port
  * @param api_regulator_status incoming data port
  */
pub fn testComputeCBwLV(
  api_alarm_control: Isolette_Data_Model::On_Off,
  api_display_temperature: Isolette_Data_Model::Temp_i,
  api_monitor_status: Isolette_Data_Model::Status,
  api_regulator_status: Isolette_Data_Model::Status) -> Result<(), TestCaseError>
{
  // Initialize the app
  crate::operator_interface_oip_oit_initialize();

  // [PutInPorts]: Set values on the input ports
  put_alarm_control(api_alarm_control);
  put_display_temperature(api_display_temperature);
  put_monitor_status(api_monitor_status);
  put_regulator_status(api_regulator_status);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::operator_interface_oip_oit_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let api_lower_alarm_tempWstatus = get_lower_alarm_tempWstatus();
  let api_lower_desired_tempWstatus = get_lower_desired_tempWstatus();
  let api_upper_alarm_tempWstatus = get_upper_alarm_tempWstatus();
  let api_upper_desired_tempWstatus = get_upper_desired_tempWstatus();

  // [CheckPost]: invoke the oracle function
  prop_assert!(
    GUMBOX::compute_CEP_Post(
      api_alarm_control,
      api_display_temperature,
      api_monitor_status,
      api_regulator_status,
      api_lower_alarm_tempWstatus,
      api_lower_desired_tempWstatus,
      api_upper_alarm_tempWstatus,
      api_upper_desired_tempWstatus
    ),
    "Postcondition failed: incorrect output behavior"
  );

  // Return Ok(()) if all assertions pass
  Ok(())
}

#[macro_export]
macro_rules!
testComputeCBwLV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_alarm_control: $api_alarm_control_strat:expr,
    api_display_temperature: $api_display_temperature_strat:expr,
    api_monitor_status: $api_monitor_status_strat:expr,
    api_regulator_status: $api_regulator_status_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_alarm_control, api_display_temperature, api_monitor_status, api_regulator_status)
        in ($api_alarm_control_strat, $api_display_temperature_strat, $api_monitor_status_strat, $api_regulator_status_strat)
      ) {
        $crate::bridge::test_api::testComputeCBwLV(
          api_alarm_control,
          api_display_temperature,
          api_monitor_status,
          api_regulator_status
        )?;
      }
    }
  };
}