#include "monitor_process_monitor_thread.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void monitor_process_monitor_thread_initialize(void);
void monitor_process_monitor_thread_notify(microkit_channel channel);
void monitor_process_monitor_thread_timeTriggered(void);

volatile sb_queue_uint8_t_1_t *producer_p_p1_producer_write_port_queue_1;
sb_queue_uint8_t_1_Recv_t producer_p_p1_producer_write_port_recv_queue;
volatile sb_queue_uint8_t_1_t *producer_p_p2_producer_write_port_queue_1;
sb_queue_uint8_t_1_Recv_t producer_p_p2_producer_write_port_recv_queue;

#define PORT_FROM_MON 52

bool producer_p_p1_producer_write_port_is_empty(void) {
  return sb_queue_uint8_t_1_is_empty(&producer_p_p1_producer_write_port_recv_queue);
}

bool get_producer_p_p1_producer_write_port_poll(sb_event_counter_t *numDropped) {
  uint8_t eventPortPayload;
  uint8_t *data = &eventPortPayload;
  return sb_queue_uint8_t_1_dequeue((sb_queue_uint8_t_1_Recv_t *) &producer_p_p1_producer_write_port_recv_queue, numDropped, data);
}

bool get_producer_p_p1_producer_write_port() {
  sb_event_counter_t numDropped;
  return get_producer_p_p1_producer_write_port_poll (&numDropped);
}

bool producer_p_p2_producer_write_port_is_empty(void) {
  return sb_queue_uint8_t_1_is_empty(&producer_p_p2_producer_write_port_recv_queue);
}

bool get_producer_p_p2_producer_write_port_poll(sb_event_counter_t *numDropped) {
  uint8_t eventPortPayload;
  uint8_t *data = &eventPortPayload;
  return sb_queue_uint8_t_1_dequeue((sb_queue_uint8_t_1_Recv_t *) &producer_p_p2_producer_write_port_recv_queue, numDropped, data);
}

bool get_producer_p_p2_producer_write_port() {
  sb_event_counter_t numDropped;
  return get_producer_p_p2_producer_write_port_poll (&numDropped);
}

void init(void) {
  sb_queue_uint8_t_1_Recv_init(&producer_p_p1_producer_write_port_recv_queue, (sb_queue_uint8_t_1_t *) producer_p_p1_producer_write_port_queue_1);

  sb_queue_uint8_t_1_Recv_init(&producer_p_p2_producer_write_port_recv_queue, (sb_queue_uint8_t_1_t *) producer_p_p2_producer_write_port_queue_1);

  monitor_process_monitor_thread_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      monitor_process_monitor_thread_timeTriggered();
      break;
    default:
      monitor_process_monitor_thread_notify(channel);
  }
}
