// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait consumer_consumer_Api {}

  pub trait consumer_consumer_Put_Api: consumer_consumer_Api {
    #[verifier::external_body]
    fn unverified_put_sample_alert(&mut self)
    {
      extern_api::unsafe_put_sample_alert();
    }
  }

  pub trait consumer_consumer_Get_Api: consumer_consumer_Api {
    #[verifier::external_body]
    fn unverified_get_sample(
      &mut self,
      value: &Ghost<Option<i32>>) -> (res : Option<i32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_sample();
    }

    #[verifier::external_body]
    fn unverified_peek_sample(
      &self,
      value: &Ghost<Option<i32>>) -> (res : Option<i32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_peek_sample();
    }

    #[verifier::external_body]
    fn unverified_peek_sample_alert(
      &self,
      value: &Ghost<Option<u8>>) -> (res : bool)
      ensures
        res == value@.is_some(),
    {
      return extern_api::unsafe_peek_sample_alert();
    }
  }

  pub trait consumer_consumer_Full_Api: consumer_consumer_Put_Api + consumer_consumer_Get_Api {}

  pub struct consumer_consumer_Application_Api<API: consumer_consumer_Api> {
    pub api: API,

    pub ghost sample: Option<i32>,
    pub ghost sample_alert: Option<u8>,
  }

  impl<API: consumer_consumer_Put_Api> consumer_consumer_Application_Api<API> {
    pub fn put_sample_alert(&mut self)
      ensures
        old(self).sample == final(self).sample,
        final(self).sample_alert == Some(0u8),
    {
      self.api.unverified_put_sample_alert();
      proof { self.sample_alert = Some(0u8); }
    }
  }

  impl<API: consumer_consumer_Get_Api> consumer_consumer_Application_Api<API> {
    pub fn get_sample(&mut self) -> (res : Option<i32>)
      ensures
        old(self).sample == final(self).sample,
        res == final(self).sample,
        old(self).sample_alert == final(self).sample_alert,
    {
      self.api.unverified_get_sample(&Ghost(self.sample))
    }
    pub fn peek_sample(&self) -> (res : Option<i32>)
      ensures
        res == self.sample,
    {
      self.api.unverified_peek_sample(&Ghost(self.sample))
    }
    pub fn peek_sample_alert(&self) -> (res : bool)
      ensures
        res == self.sample_alert.is_some(),
    {
      self.api.unverified_peek_sample_alert(&Ghost(self.sample_alert))
    }
  }

  pub struct consumer_consumer_Initialization_Api;
  impl consumer_consumer_Api for consumer_consumer_Initialization_Api {}
  impl consumer_consumer_Put_Api for consumer_consumer_Initialization_Api {}

  pub const fn init_api() -> consumer_consumer_Application_Api<consumer_consumer_Initialization_Api> {
    return consumer_consumer_Application_Api {
      api: consumer_consumer_Initialization_Api {},

      sample: None,
      sample_alert: None
    }
  }

  pub struct consumer_consumer_Compute_Api;
  impl consumer_consumer_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Put_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Get_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Full_Api for consumer_consumer_Compute_Api {}

  pub const fn compute_api() -> consumer_consumer_Application_Api<consumer_consumer_Compute_Api> {
    return consumer_consumer_Application_Api {
      api: consumer_consumer_Compute_Api {},

      sample: None,
      sample_alert: None
    }
  }

}