// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_producer_producer_p_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
  pub api_producer_producer_p_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
  pub api_producer_producer_p_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  pub api_producer_producer_p_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
  pub api_producer_producer_p_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
  pub api_producer_producer_p_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_producer_producer_p_myArrayInt32_DataPort(container.api_producer_producer_p_myArrayInt32_DataPort);
  put_producer_producer_p_myArrayStruct_DataPort(container.api_producer_producer_p_myArrayStruct_DataPort);
  put_producer_producer_p_myStructArray_DataPort(container.api_producer_producer_p_myStructArray_DataPort);
  put_producer_producer_p_myArrayInt32_EventDataPort(container.api_producer_producer_p_myArrayInt32_EventDataPort);
  put_producer_producer_p_myArrayStruct_EventDataPort(container.api_producer_producer_p_myArrayStruct_EventDataPort);
  put_producer_producer_p_myStructArray_EventDataPort(container.api_producer_producer_p_myStructArray_EventDataPort);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  producer_producer_p_myArrayInt32_DataPort: Gubmo_Structs_Arrays::MyArrayInt32,
  producer_producer_p_myArrayStruct_DataPort: Gubmo_Structs_Arrays::MyArrayStruct,
  producer_producer_p_myStructArray_DataPort: Gubmo_Structs_Arrays::MyStructArray_i,
  producer_producer_p_myArrayInt32_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayInt32>,
  producer_producer_p_myArrayStruct_EventDataPort: Option<Gubmo_Structs_Arrays::MyArrayStruct>,
  producer_producer_p_myStructArray_EventDataPort: Option<Gubmo_Structs_Arrays::MyStructArray_i>)
{
  put_producer_producer_p_myArrayInt32_DataPort(producer_producer_p_myArrayInt32_DataPort);
  put_producer_producer_p_myArrayStruct_DataPort(producer_producer_p_myArrayStruct_DataPort);
  put_producer_producer_p_myStructArray_DataPort(producer_producer_p_myStructArray_DataPort);
  put_producer_producer_p_myArrayInt32_EventDataPort(producer_producer_p_myArrayInt32_EventDataPort);
  put_producer_producer_p_myArrayStruct_EventDataPort(producer_producer_p_myArrayStruct_EventDataPort);
  put_producer_producer_p_myStructArray_EventDataPort(producer_producer_p_myStructArray_EventDataPort);
}

/// setter for IN DataPort
pub fn put_producer_producer_p_myArrayInt32_DataPort(value: Gubmo_Structs_Arrays::MyArrayInt32)
{
  *extern_api::IN_producer_producer_p_myArrayInt32_DataPort.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_producer_producer_p_myArrayStruct_DataPort(value: Gubmo_Structs_Arrays::MyArrayStruct)
{
  *extern_api::IN_producer_producer_p_myArrayStruct_DataPort.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN DataPort
pub fn put_producer_producer_p_myStructArray_DataPort(value: Gubmo_Structs_Arrays::MyStructArray_i)
{
  *extern_api::IN_producer_producer_p_myStructArray_DataPort.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN EventDataPort
pub fn put_producer_producer_p_myArrayInt32_EventDataPort(value: Option<Gubmo_Structs_Arrays::MyArrayInt32>)
{
  *extern_api::IN_producer_producer_p_myArrayInt32_EventDataPort.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_producer_producer_p_myArrayStruct_EventDataPort(value: Option<Gubmo_Structs_Arrays::MyArrayStruct>)
{
  *extern_api::IN_producer_producer_p_myArrayStruct_EventDataPort.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_producer_producer_p_myStructArray_EventDataPort(value: Option<Gubmo_Structs_Arrays::MyStructArray_i>)
{
  *extern_api::IN_producer_producer_p_myStructArray_EventDataPort.lock().unwrap_or_else(|e| e.into_inner()) = value
}
