// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait consumer_consumer_Api {}

  pub trait consumer_consumer_Put_Api: consumer_consumer_Api {
  }

  pub trait consumer_consumer_Get_Api: consumer_consumer_Api {
    #[verifier::external_body]
    fn unverified_get_myBoolean(
      &mut self,
      value: &Ghost<Option<bool>>) -> (res : Option<bool>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myBoolean();
    }

    #[verifier::external_body]
    fn unverified_get_myBoolean_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myBoolean_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myCharacter(
      &mut self,
      value: &Ghost<Option<u8>>) -> (res : Option<u8>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myCharacter();
    }

    #[verifier::external_body]
    fn unverified_get_myCharacter_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myCharacter_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myString(
      &mut self,
      value: &Ghost<Option<Base_Types::String>>) -> (res : Option<Base_Types::String>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myString();
    }

    #[verifier::external_body]
    fn unverified_get_myString_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myString_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myInt8(
      &mut self,
      value: &Ghost<Option<i8>>) -> (res : Option<i8>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myInt8();
    }

    #[verifier::external_body]
    fn unverified_get_myInt8_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myInt8_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myInt16(
      &mut self,
      value: &Ghost<Option<i16>>) -> (res : Option<i16>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myInt16();
    }

    #[verifier::external_body]
    fn unverified_get_myInt16_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myInt16_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myInt32(
      &mut self,
      value: &Ghost<Option<i32>>) -> (res : Option<i32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myInt32();
    }

    #[verifier::external_body]
    fn unverified_get_myInt32_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myInt32_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myInt64(
      &mut self,
      value: &Ghost<Option<i64>>) -> (res : Option<i64>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myInt64();
    }

    #[verifier::external_body]
    fn unverified_get_myInt64_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myInt64_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt8(
      &mut self,
      value: &Ghost<Option<u8>>) -> (res : Option<u8>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myUInt8();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt8_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myUInt8_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt16(
      &mut self,
      value: &Ghost<Option<u16>>) -> (res : Option<u16>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myUInt16();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt16_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myUInt16_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt32(
      &mut self,
      value: &Ghost<Option<u32>>) -> (res : Option<u32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myUInt32();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt32_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myUInt32_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt64(
      &mut self,
      value: &Ghost<Option<u64>>) -> (res : Option<u64>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myUInt64();
    }

    #[verifier::external_body]
    fn unverified_get_myUInt64_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myUInt64_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myFloat32(
      &mut self,
      value: &Ghost<Option<f32>>) -> (res : Option<f32>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myFloat32();
    }

    #[verifier::external_body]
    fn unverified_get_myFloat32_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myFloat32_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myFloat64(
      &mut self,
      value: &Ghost<Option<f64>>) -> (res : Option<f64>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myFloat64();
    }

    #[verifier::external_body]
    fn unverified_get_myFloat64_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myFloat64_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myEnum(
      &mut self,
      value: &Ghost<Option<Aadl_Datatypes::MyEnum>>) -> (res : Option<Aadl_Datatypes::MyEnum>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myEnum();
    }

    #[verifier::external_body]
    fn unverified_get_myEnum_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myEnum_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myStruct(
      &mut self,
      value: &Ghost<Option<Aadl_Datatypes::MyStruct_i>>) -> (res : Option<Aadl_Datatypes::MyStruct_i>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myStruct();
    }

    #[verifier::external_body]
    fn unverified_get_myStruct_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myStruct_num_invalid();
    }

    #[verifier::external_body]
    fn unverified_get_myArray1(
      &mut self,
      value: &Ghost<Option<Aadl_Datatypes::MyArrayOneDim>>) -> (res : Option<Aadl_Datatypes::MyArrayOneDim>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_myArray1();
    }

    #[verifier::external_body]
    fn unverified_get_myArray1_num_invalid(&self) -> u64
    {
      return extern_api::unsafe_get_myArray1_num_invalid();
    }
  }

  pub trait consumer_consumer_Full_Api: consumer_consumer_Put_Api + consumer_consumer_Get_Api {}

  pub struct consumer_consumer_Application_Api<API: consumer_consumer_Api> {
    pub api: API,

    pub ghost myBoolean: Option<bool>,
    pub ghost myCharacter: Option<u8>,
    pub ghost myString: Option<Base_Types::String>,
    pub ghost myInt8: Option<i8>,
    pub ghost myInt16: Option<i16>,
    pub ghost myInt32: Option<i32>,
    pub ghost myInt64: Option<i64>,
    pub ghost myUInt8: Option<u8>,
    pub ghost myUInt16: Option<u16>,
    pub ghost myUInt32: Option<u32>,
    pub ghost myUInt64: Option<u64>,
    pub ghost myFloat32: Option<f32>,
    pub ghost myFloat64: Option<f64>,
    pub ghost myEnum: Option<Aadl_Datatypes::MyEnum>,
    pub ghost myStruct: Option<Aadl_Datatypes::MyStruct_i>,
    pub ghost myArray1: Option<Aadl_Datatypes::MyArrayOneDim>,
  }

  impl<API: consumer_consumer_Put_Api> consumer_consumer_Application_Api<API> {
  }

  impl<API: consumer_consumer_Get_Api> consumer_consumer_Application_Api<API> {
    pub fn get_myBoolean(&mut self) -> (res : Option<bool>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        res == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myBoolean(&Ghost(self.myBoolean))
    }/// The number of messages received on myBoolean that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myBoolean_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myBoolean_num_invalid()
    }
    pub fn get_myCharacter(&mut self) -> (res : Option<u8>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        res == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myCharacter(&Ghost(self.myCharacter))
    }/// The number of messages received on myCharacter that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myCharacter_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myCharacter_num_invalid()
    }
    pub fn get_myString(&mut self) -> (res : Option<Base_Types::String>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        res == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myString(&Ghost(self.myString))
    }/// The number of messages received on myString that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myString_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myString_num_invalid()
    }
    pub fn get_myInt8(&mut self) -> (res : Option<i8>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        res == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myInt8(&Ghost(self.myInt8))
    }/// The number of messages received on myInt8 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myInt8_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myInt8_num_invalid()
    }
    pub fn get_myInt16(&mut self) -> (res : Option<i16>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        res == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myInt16(&Ghost(self.myInt16))
    }/// The number of messages received on myInt16 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myInt16_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myInt16_num_invalid()
    }
    pub fn get_myInt32(&mut self) -> (res : Option<i32>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        res == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myInt32(&Ghost(self.myInt32))
    }/// The number of messages received on myInt32 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myInt32_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myInt32_num_invalid()
    }
    pub fn get_myInt64(&mut self) -> (res : Option<i64>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        res == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myInt64(&Ghost(self.myInt64))
    }/// The number of messages received on myInt64 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myInt64_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myInt64_num_invalid()
    }
    pub fn get_myUInt8(&mut self) -> (res : Option<u8>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        res == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myUInt8(&Ghost(self.myUInt8))
    }/// The number of messages received on myUInt8 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myUInt8_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myUInt8_num_invalid()
    }
    pub fn get_myUInt16(&mut self) -> (res : Option<u16>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        res == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myUInt16(&Ghost(self.myUInt16))
    }/// The number of messages received on myUInt16 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myUInt16_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myUInt16_num_invalid()
    }
    pub fn get_myUInt32(&mut self) -> (res : Option<u32>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        res == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myUInt32(&Ghost(self.myUInt32))
    }/// The number of messages received on myUInt32 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myUInt32_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myUInt32_num_invalid()
    }
    pub fn get_myUInt64(&mut self) -> (res : Option<u64>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        res == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myUInt64(&Ghost(self.myUInt64))
    }/// The number of messages received on myUInt64 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myUInt64_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myUInt64_num_invalid()
    }
    pub fn get_myFloat32(&mut self) -> (res : Option<f32>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        res == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myFloat32(&Ghost(self.myFloat32))
    }/// The number of messages received on myFloat32 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myFloat32_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myFloat32_num_invalid()
    }
    pub fn get_myFloat64(&mut self) -> (res : Option<f64>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        res == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myFloat64(&Ghost(self.myFloat64))
    }/// The number of messages received on myFloat64 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myFloat64_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myFloat64_num_invalid()
    }
    pub fn get_myEnum(&mut self) -> (res : Option<Aadl_Datatypes::MyEnum>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        res == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myEnum(&Ghost(self.myEnum))
    }/// The number of messages received on myEnum that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myEnum_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myEnum_num_invalid()
    }
    pub fn get_myStruct(&mut self) -> (res : Option<Aadl_Datatypes::MyStruct_i>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        res == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
    {
      self.api.unverified_get_myStruct(&Ghost(self.myStruct))
    }/// The number of messages received on myStruct that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myStruct_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myStruct_num_invalid()
    }
    pub fn get_myArray1(&mut self) -> (res : Option<Aadl_Datatypes::MyArrayOneDim>)
      ensures
        old(self).myBoolean == final(self).myBoolean,
        old(self).myCharacter == final(self).myCharacter,
        old(self).myString == final(self).myString,
        old(self).myInt8 == final(self).myInt8,
        old(self).myInt16 == final(self).myInt16,
        old(self).myInt32 == final(self).myInt32,
        old(self).myInt64 == final(self).myInt64,
        old(self).myUInt8 == final(self).myUInt8,
        old(self).myUInt16 == final(self).myUInt16,
        old(self).myUInt32 == final(self).myUInt32,
        old(self).myUInt64 == final(self).myUInt64,
        old(self).myFloat32 == final(self).myFloat32,
        old(self).myFloat64 == final(self).myFloat64,
        old(self).myEnum == final(self).myEnum,
        old(self).myStruct == final(self).myStruct,
        old(self).myArray1 == final(self).myArray1,
        res == final(self).myArray1,
    {
      self.api.unverified_get_myArray1(&Ghost(self.myArray1))
    }/// The number of messages received on myArray1 that were dropped because they held
    /// an invalid bit pattern (an out-of-range enum, a bool that is neither 0 nor 1, or a
    /// string with no terminating NUL)
    pub fn get_myArray1_num_invalid(&self) -> u64
    {
      self.api.unverified_get_myArray1_num_invalid()
    }
  }

  pub struct consumer_consumer_Initialization_Api;
  impl consumer_consumer_Api for consumer_consumer_Initialization_Api {}
  impl consumer_consumer_Put_Api for consumer_consumer_Initialization_Api {}

  pub const fn init_api() -> consumer_consumer_Application_Api<consumer_consumer_Initialization_Api> {
    return consumer_consumer_Application_Api {
      api: consumer_consumer_Initialization_Api {},

      myBoolean: None,
      myCharacter: None,
      myString: None,
      myInt8: None,
      myInt16: None,
      myInt32: None,
      myInt64: None,
      myUInt8: None,
      myUInt16: None,
      myUInt32: None,
      myUInt64: None,
      myFloat32: None,
      myFloat64: None,
      myEnum: None,
      myStruct: None,
      myArray1: None
    }
  }

  pub struct consumer_consumer_Compute_Api;
  impl consumer_consumer_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Put_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Get_Api for consumer_consumer_Compute_Api {}
  impl consumer_consumer_Full_Api for consumer_consumer_Compute_Api {}

  pub const fn compute_api() -> consumer_consumer_Application_Api<consumer_consumer_Compute_Api> {
    return consumer_consumer_Application_Api {
      api: consumer_consumer_Compute_Api {},

      myBoolean: None,
      myCharacter: None,
      myString: None,
      myInt8: None,
      myInt16: None,
      myInt32: None,
      myInt64: None,
      myUInt8: None,
      myUInt16: None,
      myUInt32: None,
      myUInt64: None,
      myFloat32: None,
      myFloat64: None,
      myEnum: None,
      myStruct: None,
      myArray1: None
    }
  }

}