[package]
name = "sel4_low_level_ethernet_driver"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "seL4_LowLevelEthernetDriver_LowLevelEthernetDriver"
# crate-type = ["cdylib"]      # Creates dynamic lib
crate-type = ["staticlib"] # Creates static lib
