#pragma once

#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

typedef enum {
  R2U2_VERDICT_UNKNOWN,
  R2U2_VERDICT_FALSE,
  R2U2_VERDICT_TRUE
} r2u2_verdict_status_t;

void handle_samples_match_until_producer_pauses_verdict(r2u2_verdict_status_t verdict);

void r2u2_monitor_initialize(void);
void r2u2_monitor_pre_timeTriggered(void);
void r2u2_monitor_post_timeTriggered(void);
