name: HAMR-codegen

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'micro-examples/**'
      - 'isolette/**'
      - 'open-platform-models/isolate-ethernet-simple/**'
  schedule:
    - cron: "0 2 * * 6" # every sunday at 2am
    
jobs:
  ci:
    runs-on: ubuntu-latest
    container: 
      image: jasonbelt/microkit_provers:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    name: HAMR-codegen
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: INSPECTA-models
          submodules: recursive
          ref: main
          fetch-depth: 1
          fetch-tags: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          repository: sireum/kekinian
          submodules: recursive
          ref: master
          fetch-depth: 1
          fetch-tags: false
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v4
        with:
          path: Sireum/bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v4
        with:
          path: Sireum/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v4
        with:
          path: Sireum/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-coursier
      - name: Cache OSATE
        id: cache-osate
        uses: actions/cache@v4
        with:
          path: Sireum/bin/linux/osate
          key: ${{ runner.os }}-${{ hashFiles('Sireum/hamr/codegen/jvm/src/main/resources/phantom_versions.properties') }}-osate
      - name: Build
        shell: bash
        run: |
          rm -rf INSPECTA-models/.git # free up disk space
          
          export HOME=/home/microkit
          export PROVERS_DIR=${HOME}/provers
          export LIONSOS=${PROVERS_DIR}/lionsos
          export MICROKIT_BOARD=qemu_virt_aarch64
          export MICROKIT_SDK=${PROVERS_DIR}/microkit-sdk-1.4.1
          export SIREUM_HOME=${PROVERS_DIR}/Sireum
          export VERUS_Z3_PATH=${PROVERS_DIR}/verus/z3
          export VERUS_DIR=${PROVERS_DIR}/verus
          export PATH=${VERUS_DIR}:${SIREUM_HOME}/bin:${HOME}/.cargo/bin:$PATH
          
          rm -rf ${PROVERS_DIR}/Sireum # remove bootstrap version
          export SIREUM_HOME=$(pwd)/Sireum
          export PATH=${SIREUM_HOME}/bin:${PATH}

          ${SIREUM_HOME}/bin/build.cmd setup
          rm -rf ${SIREUM_HOME}/out
          
          sireum -v
          
          export OSATE_HOME=${SIREUM_HOME}/bin/linux/osate
          sireum slang run ${SIREUM_HOME}/hamr/codegen/bin/build.cmd install-osate-gumbo

          INSPECTA-models/.github/workflows/hamr/hamr-ci.cmd
