// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::monitor_process_monitor_thread_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::monitor_process_monitor_thread_initialize();

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_pulse incoming event port
  * @param api_flag incoming event data port
  * @param api_operating_state incoming event data port
  * @param api_sample incoming event data port
  * @param api_samples incoming event data port
  * @param api_telemetry incoming event data port
  * @param api_boolean_value incoming data port
  * @param api_character_value incoming data port
  * @param api_level incoming data port
  * @param api_signed_16_value incoming data port
  * @param api_signed_8_value incoming data port
  * @param api_unsigned_16_value incoming data port
  * @param api_unsigned_8_value incoming data port
  */
pub fn testComputeCB(
  api_pulse: Option<u8>,
  api_flag: Option<bool>,
  api_operating_state: Option<Exhaustive_Monitor::OperatingState>,
  api_sample: Option<i32>,
  api_samples: Option<Exhaustive_Monitor::Samples>,
  api_telemetry: Option<Exhaustive_Monitor::Telemetry_i>,
  api_boolean_value: bool,
  api_character_value: u8,
  api_level: i32,
  api_signed_16_value: i16,
  api_signed_8_value: i8,
  api_unsigned_16_value: u16,
  api_unsigned_8_value: u8) -> HarnessResult
{
  // Initialize the app
  crate::monitor_process_monitor_thread_initialize();

  // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved
  //                from the component state
  let In_sprevious_level: i32 = get_sprevious_level();

  // [PutInPorts]: Set values on the input ports
  put_pulse(api_pulse);
  put_flag(api_flag);
  put_operating_state(api_operating_state);
  put_sample(api_sample);
  put_samples(api_samples);
  put_telemetry(api_telemetry);
  put_boolean_value(api_boolean_value);
  put_character_value(api_character_value);
  put_level(api_level);
  put_signed_16_value(api_signed_16_value);
  put_signed_8_value(api_signed_8_value);
  put_unsigned_16_value(api_unsigned_16_value);
  put_unsigned_8_value(api_unsigned_8_value);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::monitor_process_monitor_thread_timeTriggered();

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_pulse, container.api_flag, container.api_operating_state, container.api_sample, container.api_samples, container.api_telemetry, container.api_boolean_value, container.api_character_value, container.api_level, container.api_signed_16_value, container.api_signed_8_value, container.api_unsigned_16_value, container.api_unsigned_8_value)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_pulse: $api_pulse_strat:expr,
    api_flag: $api_flag_strat:expr,
    api_operating_state: $api_operating_state_strat:expr,
    api_sample: $api_sample_strat:expr,
    api_samples: $api_samples_strat:expr,
    api_telemetry: $api_telemetry_strat:expr,
    api_boolean_value: $api_boolean_value_strat:expr,
    api_character_value: $api_character_value_strat:expr,
    api_level: $api_level_strat:expr,
    api_signed_16_value: $api_signed_16_value_strat:expr,
    api_signed_8_value: $api_signed_8_value_strat:expr,
    api_unsigned_16_value: $api_unsigned_16_value_strat:expr,
    api_unsigned_8_value: $api_unsigned_8_value_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (
          (api_pulse, api_flag, api_operating_state, api_sample, api_samples, api_telemetry, api_boolean_value, api_character_value, api_level, api_signed_16_value),
          (api_signed_8_value, api_unsigned_16_value, api_unsigned_8_value)
        ) in (
          ($api_pulse_strat, $api_flag_strat, $api_operating_state_strat, $api_sample_strat, $api_samples_strat, $api_telemetry_strat, $api_boolean_value_strat, $api_character_value_strat, $api_level_strat, $api_signed_16_value_strat),
          ($api_signed_8_value_strat, $api_unsigned_16_value_strat, $api_unsigned_8_value_strat)
        )
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_pulse, api_flag, api_operating_state, api_sample, api_samples, api_telemetry, api_boolean_value, api_character_value, api_level, api_signed_16_value, api_signed_8_value, api_unsigned_16_value, api_unsigned_8_value) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param In_sprevious_level pre-state state variable
  * @param api_pulse incoming event port
  * @param api_flag incoming event data port
  * @param api_operating_state incoming event data port
  * @param api_sample incoming event data port
  * @param api_samples incoming event data port
  * @param api_telemetry incoming event data port
  * @param api_boolean_value incoming data port
  * @param api_character_value incoming data port
  * @param api_level incoming data port
  * @param api_signed_16_value incoming data port
  * @param api_signed_8_value incoming data port
  * @param api_unsigned_16_value incoming data port
  * @param api_unsigned_8_value incoming data port
  */
pub fn testComputeCBwGSV(
  In_sprevious_level: i32,
  api_pulse: Option<u8>,
  api_flag: Option<bool>,
  api_operating_state: Option<Exhaustive_Monitor::OperatingState>,
  api_sample: Option<i32>,
  api_samples: Option<Exhaustive_Monitor::Samples>,
  api_telemetry: Option<Exhaustive_Monitor::Telemetry_i>,
  api_boolean_value: bool,
  api_character_value: u8,
  api_level: i32,
  api_signed_16_value: i16,
  api_signed_8_value: i8,
  api_unsigned_16_value: u16,
  api_unsigned_8_value: u8) -> HarnessResult
{
  // Initialize the app
  crate::monitor_process_monitor_thread_initialize();

  // [PutInPorts]: Set values on the input ports
  put_pulse(api_pulse);
  put_flag(api_flag);
  put_operating_state(api_operating_state);
  put_sample(api_sample);
  put_samples(api_samples);
  put_telemetry(api_telemetry);
  put_boolean_value(api_boolean_value);
  put_character_value(api_character_value);
  put_level(api_level);
  put_signed_16_value(api_signed_16_value);
  put_signed_8_value(api_signed_8_value);
  put_unsigned_16_value(api_unsigned_16_value);
  put_unsigned_8_value(api_unsigned_8_value);

  // [SetInStateVars]: set the pre-state values of state variables
  put_sprevious_level(In_sprevious_level);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::monitor_process_monitor_thread_timeTriggered();

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCBwGSV_container(container: PreStateContainer_wGSV) -> HarnessResult
{
  return testComputeCBwGSV(container.In_sprevious_level, container.api_pulse, container.api_flag, container.api_operating_state, container.api_sample, container.api_samples, container.api_telemetry, container.api_boolean_value, container.api_character_value, container.api_level, container.api_signed_16_value, container.api_signed_8_value, container.api_unsigned_16_value, container.api_unsigned_8_value)
}

#[macro_export]
macro_rules!
testComputeCBwGSV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    In_sprevious_level: $In_sprevious_level_strat:expr,
    api_pulse: $api_pulse_strat:expr,
    api_flag: $api_flag_strat:expr,
    api_operating_state: $api_operating_state_strat:expr,
    api_sample: $api_sample_strat:expr,
    api_samples: $api_samples_strat:expr,
    api_telemetry: $api_telemetry_strat:expr,
    api_boolean_value: $api_boolean_value_strat:expr,
    api_character_value: $api_character_value_strat:expr,
    api_level: $api_level_strat:expr,
    api_signed_16_value: $api_signed_16_value_strat:expr,
    api_signed_8_value: $api_signed_8_value_strat:expr,
    api_unsigned_16_value: $api_unsigned_16_value_strat:expr,
    api_unsigned_8_value: $api_unsigned_8_value_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (
          (In_sprevious_level, api_pulse, api_flag, api_operating_state, api_sample, api_samples, api_telemetry, api_boolean_value, api_character_value, api_level),
          (api_signed_16_value, api_signed_8_value, api_unsigned_16_value, api_unsigned_8_value)
        ) in (
          ($In_sprevious_level_strat, $api_pulse_strat, $api_flag_strat, $api_operating_state_strat, $api_sample_strat, $api_samples_strat, $api_telemetry_strat, $api_boolean_value_strat, $api_character_value_strat, $api_level_strat),
          ($api_signed_16_value_strat, $api_signed_8_value_strat, $api_unsigned_16_value_strat, $api_unsigned_8_value_strat)
        )
      ) {
        match $crate::test::util::cb_apis::testComputeCBwGSV(In_sprevious_level, api_pulse, api_flag, api_operating_state, api_sample, api_samples, api_telemetry, api_boolean_value, api_character_value, api_level, api_signed_16_value, api_signed_8_value, api_unsigned_16_value, api_unsigned_8_value) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
